### ISSUE TITLE
fix labels, milestones, ... for the new repo's

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#1]
- there is a script for it I believe
- make sure this script is also of jumpscalex_libs
- put the new repo's into our projects

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/63673581-e6ca4f80-c7e4-11e9-868f-fba595f9cfdb.png)

**Comment by despiegk** [comment]
where is script?

**Comment by rkhamis** [comment]
I'll add the script as a tool

**Comment by rkhamis** [comment]
added under `j.clients.github.<github_instance>.bootstrap_labels()`
