### ISSUE TITLE
startupcmd tests are broken

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#102]
running ` j.servers.startupcmd.test()` throw the following error:

```
Tue 24 08:27:58 /BASECLASSES/Attr.py -  57 - __getattr__                        : EXCEPTION: 
    try to get attribute: 'http', instance did not exist, was also not a method or property, was on 'startupcmdfactory'
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/startupcmd/StartupCMDFactory.py in test
    128    http_tmux()
/sandbox/lib/jumpscale/Jumpscale/servers/startupcmd/StartupCMDFactory.py in http_tmux
    45    self.http.delete()
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py in __getattr__
    57    % (name, self._key)
-----------------------------
```
In addition, I noticed there are test files under `tests` that contain more or less the same code in the test function. However, there is no way to run those tests. Tests with this structure should run from inside the `test` function (see the schema factory for reference), but in startupcmds there is no way to run them because the test function already contains other tests/logic.

Also the doctring of the tests needs to be corrected.

**Comment by RafyAmgadBenjamin** [comment]
It is not reproducible anymore and the tests are restructured already.
