### ISSUE TITLE
Rack server need background option  

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#104]
- start rack server will always stuck and there is o background option
```
JSX> rack.start(background=True)                                                                     
Wed 25 07:52:25 <stdin>              -   1 - <module>                           : EXCEPTION: 
    TypeError("start() got an unexpected keyword argument 'background'",)
--TRACEBACK------------------
<stdin> in <module>
    1    
-----------------------------

start() got an unexpected keyword argument 'background'
```
![image](https://user-images.githubusercontent.com/24386802/65584332-06d66580-df81-11e9-8a1f-94e7edf5b185.png)

**Comment by andrewayoub** [comment]
it's not supported at the moment, currently servers added to the rack are added during runtime and stored in memory which means if you try to start the rack in a different process it will be empty (the added servers won't be in the new process).
