### ISSUE TITLE
wallets of a certain tfchain client, appear as children in other clients

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#106]
Create tfchain client `clientone`, and on it create wallet `walletone`.

![Screenshot from 2019-09-25 10-47-16](https://user-images.githubusercontent.com/6323012/65585125-3e91dd00-df82-11e9-852b-229f07b13441.png)

Create tfchain client `clienttwo`. In the autocomplete, you'll be able to see `walletone` even though it doesn't belong to this client. And if you try to select it, it will raise an error.

![Screenshot from 2019-09-25 10-47-50](https://user-images.githubusercontent.com/6323012/65585319-90d2fe00-df82-11e9-8753-ef7badb42356.png)

**Comment by hossnys** [comment]
verified on development c54926e
```
JSX> c = j.clients.tfchain.get('my_client1',network_type="TEST")                                           
JSX> w = c.wallets.get("my_wallet1")                                                                       
JSX> c.wallets                                                                                             
## tfchainwalletfactory TFChainWalletFactory

### children:
 - my_wallet1





JSX> c = j.clients.tfchain.get('my_client2',network_type="TEST")                                           
JSX> w = c.wallets.get("my_wallet")                                                                        
JSX> c.wallets                                                                                             
## tfchainwalletfactory TFChainWalletFactory








```

**Comment by serboctor** [comment]
Refactored the code to use sql like it used to but take the mother_id into consideration.
