### ISSUE TITLE
Recursive deletion is flawed, bugy and inconsistent

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#111]
The docstring of the delete states that `recursive` deletion will be set to True automatically if `there is mother`. This doesn't make sense. Deletion should be recursive if an object has children. ie: when you delete an object, its children for which the object is a mother should be deleted too. 

Also, recursive shouldnt be configurable to begin with, we always want to delete children of any object, otherwise we'll end up with lots of orphan entries in the database with no way to access the,

1. Creating a tfchain client, and a wallet from this client. Delete the client. The wallet doesn't get deleted even though it's a child of the client.
![Screenshot from 2019-09-26 18-40-23](https://user-images.githubusercontent.com/6323012/65708141-332bd800-e08e-11e9-8201-d36faf9fcc99.png)

2. Repeat scenario 1 but force recursive=True. The children will be deleted correctly if you use the delete function on the client object.
![Screenshot from 2019-09-26 18-49-58](https://user-images.githubusercontent.com/6323012/65708363-b3ead400-e08e-11e9-9713-cd51b8562a23.png)

3. Create a client and wallet. Delete the client using `j.clients.tfchain.delete` and set recursive=True. It will raise an error.
![Screenshot from 2019-09-26 18-54-28](https://user-images.githubusercontent.com/6323012/65708573-29ef3b00-e08f-11e9-8b71-ba350849b42a.png)

4. Repeat scenario 3 but don't force recursive deletion. The child wallet won't be deleted.
![Screenshot from 2019-09-26 18-57-09](https://user-images.githubusercontent.com/6323012/65708753-9833fd80-e08f-11e9-9657-b63d7ec375d8.png)

This was tested against `developement` but  I'll do the fixes on `development_save` since it touched the same areas as https://github.com/threefoldtech/jumpscaleX_core/issues/103

**Comment by serboctor** [comment]
The `recursive` flag has been removed. Deleting any object will automatically delete all its children so we don't end up with unaccessible orphans in the database.

**Comment by siddiquagig** [comment]
Got the error, seems it did not delete it 

```JSX> c = j.clients.tfchain.new("myone", network_type="TEST")


JSX> w = c.wallets.new("myone")
JSX> c.delete()
JSX> c = j.clients.tfchain.new("mytwo", network_type="TEST")
JSX> w = c.wallets.new("myone")
JSX> c = j.clients.tfchain.new("myone", network_type="TEST")
JSX> w = c.wallets.new("myone")
JSX> j.clients.tfchain.delete("myone")
Wed 02 15:13:34 /schema/JSXObject.py - 192 - save                                                                                                                                                                                            : EXCEPTION:
    could not save, was not unique.
    {'name': 'myone'}.
--TRACEBACK------------------
<stdin> in <module>
    1
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in new
    44    jsconfig = self._new(name=name, jsxobject=jsxobject, autosave=autosave                                                                                                                                                             , **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in _new
    92    jsxobject.mother_id = mother_id
/sandbox/var/codegen/schema_jumpscale_tfchain_wallet.py in mother_id
    307    self.save()
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py in save
    192    raise j.exceptions.Input(msg)
-----------------------------

None
```

**Comment by siddiquagig** [comment]
Verified now:

![clientwallet](https://user-images.githubusercontent.com/25789724/66042995-01ec5580-e52f-11e9-8417-d828c94104ef.JPG)
