### ISSUE TITLE
j.application.interactive does not behave well

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#113]
![image](https://user-images.githubusercontent.com/6021844/65828806-216d4f00-e29f-11e9-9fe1-f8e1192aa22b.png)

see here
did shortcut for now

**Comment by BolaNasr** [comment]
j.application.interactive behave well now , and i delete useless set

**Comment by abdulgig** [comment]
While verifying, got this error ! The screen shot is attached herewith
![Nic_error](https://user-images.githubusercontent.com/25789764/66308261-bc0d0400-e917-11e9-8718-ed8ec8866379.jpg)

**Comment by BolaNasr** [comment]
@abdulgig  it's not related to our issue

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
