### ISSUE TITLE
After renaming a client, the old name can't be used

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#115]
1. Create a client.
2. Rename the client and save.

Outcome:
- Client is available under both the old and the new name.
- I can't use the old name anymore even though the client has already been renamed.

This is probably because of the children dict on the config class being out of sync with reality.

![Screenshot from 2019-09-30 10-16-16](https://user-images.githubusercontent.com/6323012/65861096-e4bb5980-e36b-11e9-9cc4-1b8e2830fe41.png)

Please remove the skip decorator from this test once fixed. https://github.com/threefoldtech/jumpscaleX_core/pull/112/files#diff-611ea910ed9c665a97c6c3b5edb30889R31

**Comment by serboctor** [comment]
PR ready to be merged, pending @rkhamis's approval
https://github.com/threefoldtech/jumpscaleX_core/pull/119

**Comment by siddiquagig** [comment]
Verified

![image](https://user-images.githubusercontent.com/25789724/67285227-3af16780-f4e8-11e9-8709-8e6c5ced610c.png)


![image](https://user-images.githubusercontent.com/25789724/67285344-6bd19c80-f4e8-11e9-978d-e090d36e5126.png)
