### ISSUE TITLE
error in load method in sshkey client 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#116]
error in load method in sshkey client 

- sshkey_client = j.clients.sshkey.get(name="sshkey_client")
- sshkey_client.load()

![error](https://user-images.githubusercontent.com/21218053/65876975-dc264b80-e38a-11e9-9af4-1c77c1397b3f.png)

**Comment by serboctor** [comment]
Already fixed by this https://github.com/threefoldtech/jumpscaleX_core/commit/456a55a39f2bf933a2a43c63d7083192d28a1015

**Comment by serboctor** [comment]
Already fixed by this https://github.com/threefoldtech/jumpscaleX_core/commit/456a55a39f2bf933a2a43c63d7083192d28a1015. Please pull and try again.

**Comment by siddiquagig** [comment]
Verified:

```
JSX> sshkey_client.load()
 2410 ?        Ss     0:00 /usr/bin/ssh-agent /usr/bin/im-launch env GNOME_SHELL_SESSION_MODE=ubuntu gnome-session --session=ubuntu
11096 pts/1    S+     0:00 /bin/bash -c ps ax | grep 'ssh-agent'
11098 pts/1    S+     0:00 grep ssh-agent
Identity added: /root/.ssh/sshkey_client (/root/.ssh/sshkey_client)
Lifetime set to 86400 seconds

```
