### ISSUE TITLE
why we use duration method in sshkey client 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#117]
- I found duration method in sshkey client, why we use this method. is it used any where in the code or it's usable.

**Comment by serboctor** [comment]
`duration` is not a  method, it's an argument on the sshkey client. It's part of its schema. It is supposed to specify the duration of time the key will be loaded into an agent, when you load it.
I fixed the load function to use it and to work properly.
https://github.com/threefoldtech/jumpscaleX_core/commit/456a55a39f2bf933a2a43c63d7083192d28a1015
