### ISSUE TITLE
Enable CORS into gedis http endpoint

### ISSUE THREAD

**Issue by maxux** [threefoldtech/jumpscaleX_core#120]
We need an easy way to configure CORS on gedis http interface.
When calling gedis via port 9201, this service should allow a configurable `Access-Control-Allow-Origin` header.

This allow control list of which website can remotely query the gedis using ajax. At least we should be able to configure it to `*` to allow everything :p

**Comment by xmonader** [comment]
@maxux from past import xD
https://github.com/threefoldtech/jumpscaleX_core/commit/9f6c75d5f239985dddf26b6ee37bdf97cd8e547e
