### ISSUE TITLE
syncer not working well

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#121]
![image](https://user-images.githubusercontent.com/6021844/66100549-b0ce7700-e5ab-11e9-9f50-6dced3cf3415.png)

shoud work from shell and from kosmos -p ...
the 2nd one blocks it

**Comment by AhmedHanafy725** [comment]
### Verification steps:
1- Create 2 remote machines with ubuntu:18.04
2- install rsync in them both `apt-get install -y rsync`

3- In kosmos shell
```
cl1 = j.clients.ssh.get("test1", addr=<machine1 ip>, port=<machine1 port>)
cl2 = j.clients.ssh.get("test2", addr=<machine2 ip>, port=<machine2 port>)
syncer = j.tools.syncer.get("test")
syncer.sshclients_add([cl1, cl2])
syncer.sync(monitor=True)
```
and wait for syncer to finish.
4- Check both machines, code was copied.
5- Make some changes in code and create new files.
6- Check both machines, changes are found.

**Verified**
