### ISSUE TITLE
SAL: kill process by name doesn't work correctly 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#123]
## Steps 
- create two  processes with different users  too
p1 = tail -f /dev/null
p2 = tail -f /test_file
 - kill process byt killProcessByName(test_file)

## issue 
will kill both p1 and p2

**Comment by Dinaamagdy** [comment]
and kill by user j.sal.process.killUserProcesses(user2), doesn't do anything

**Comment by RafyAmgadBenjamin** [comment]
Related to the first issue it can't be reproduced.

<em> steps </em>
* open terminal 
![image](https://user-images.githubusercontent.com/46320202/66304444-75121500-e8fd-11e9-9d8c-a262999ea9fb.png)

* open another terminal
![image](https://user-images.githubusercontent.com/46320202/66304471-8824e500-e8fd-11e9-9b75-4851a19d2897.png)

* checked the process
![image](https://user-images.githubusercontent.com/46320202/66304509-a38ff000-e8fd-11e9-94eb-f7019dc5bb99.png)

* apply the command
``` j.sal.process.killProcessesByName("test_file") ```

<em>it killed the desired process only </em>
![image](https://user-images.githubusercontent.com/46320202/66304671-0ed9c200-e8fe-11e9-9d4a-af6b1bfe6509.png)

**Comment by RafyAmgadBenjamin** [comment]
<em>the second issue is resolved </em>
![image](https://user-images.githubusercontent.com/46320202/66307893-f53c7880-e905-11e9-8473-c9268e48b414.png)

<em>apply the command</em>
```j.sal.process.killUserProcesses("root") ```

<em>it killed everything related to the user</em>
![image](https://user-images.githubusercontent.com/46320202/66308043-582e0f80-e906-11e9-8384-b0da13604192.png)

**Comment by Pishoy** [comment]
verified
- first issue can no reproduced 
- second verified as below  
```
3BOTDEVEL:host:~: ps aux | grep test
test     16699  0.0  0.0   6212   764 pts/5    S    07:45   0:00 tail -f /dev/null
test     16700  0.0  0.0   6212   720 pts/5    S    07:45   0:00 tail -f /dev/null
root     16702  0.0  0.1  13136  1100 pts/5    S+   07:45   0:00 grep test
3BOTDEVEL:host:~: kosmos "j.sal.process.killUserProcesses('test')" 
3BOTDEVEL:host:~: ps aux | grep test
root     16708  0.0  0.1  13136  1128 pts/5    S+   07:46   0:00 grep test
```
 - jsx version 
```
commit a394ab7f256c39d65b5037496a2c881ea9fa1953 (HEAD -> development, origin/development, origin/HEAD)
Author: Ahmed T. Youssef <xmonader@gmail.com>
Date:   Thu Oct 10 12:56:28 2019 +0200

    use alias for SPA

```
