### ISSUE TITLE
more pleasing usage of gedis_http.js 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#125]
instead of having `executeCommand(actor, cmd, args)` try to allow `client.actors.ACTOR.CMD.execute(args)` in runtime

**Comment by ranatrk** [comment]
In runtime args can be executed in runtime with the old method or with the  following: 
`
client.actors.ACTOR_NAME.ACTOR_CMD(ACTOR_ARGS, FETCHOPTS)
`

Changes: https://github.com/threefoldtech/jumpscaleX_weblibs/commit/a09f2418bb7ca4b2817c4267be13314e232d500e

**Comment by xmonader** [comment]
Looks great! thank you!!

**Comment by AhmedHanafy725** [comment]
### Verification steps:
1- Create html file that contains the script `test.html`
```html
<!DOCTYPE html>
<html lang="">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home</title>


    <script src="http://172.17.0.2/wikistatic/weblibs/gedis/gedis_http.js"></script>

    <script>

        localGedisClient.actors.alerta.list_alerts().then( resp => console.log(resp.json()))
   </script>
</head>

<body />
```
2- Put this file into weblibs `/sandbox/code/github/threefoldtech/jumpscale_weblibs/static/gedis`
3- Start [alerta](https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/alerta#running).
4- Create new alerts.
5- Go to `http://172.17.0.2/weblibs/gedis/test.html` and inspect.

![image](https://user-images.githubusercontent.com/41957921/67663420-2260d180-f96e-11e9-9242-716025a84f93.png)

### Verified
Alerts has been created can be listed using the actor in runtime.
`localGedisClient.actors.alerta.list_alerts()`
