### ISSUE TITLE
Validate images

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#131]
Test installation for both the dev image and the production image.
Update images if needed.

steps for production image:
- run `/tmp/jsx container-install --threebot` and after the installation check that you can start threebot immediatly `j.servers.threebot.default.start()`

steps for developemt:
- run `/tmp/jsx container-install --threebot --develop` and after the installation check that you can start threebot immediatly `j.servers.threebot.default.start()`

Make sure you remove /sandbox/var and /sandbox/cfg before each installation.

**Comment by serboctor** [comment]
Updated the images and tested both scenarios successfully.

**Comment by siddiquagig** [comment]
For both images i am getting this error:

![image](https://user-images.githubusercontent.com/25789724/67007754-1d438d00-f0f9-11e9-9dc7-28e84089246c.png)


Will try on a new  machine now

**Comment by serboctor** [comment]
Can you try removing any old 3bot containers first?

**Comment by siddiquagig** [comment]
I have deleted old 3bot containers and even tried on a fresh ubuntu installation, still its stuck here:

![image](https://user-images.githubusercontent.com/25789724/67157787-3723e080-f342-11e9-8cc3-b91aaa3a5d69.png)

**Comment by siddiquagig** [comment]
Verified both scenarios

Production:
![image](https://user-images.githubusercontent.com/25789724/67158407-bfa57f80-f348-11e9-8ce5-39338df8965a.png)

Development:
![image](https://user-images.githubusercontent.com/25789724/67158686-5d4e7e00-f34c-11e9-80e1-33edec6316fc.png)
