### ISSUE TITLE
Freeflow pages client

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_core#139]
A FreeFlowPages client that would pre-subscribe a 3bot user in a certain list of spaces

**Comment by rkhamis** [comment]
Required for https://github.com/threefoldtech/jumpscaleX_threebot/issues/159

**Comment by john-kheir** [comment]
## Issue
### Steps

1- Get freeflow Client
```
x = j.clients.freeflowpages.get() 
x.base_url = "..."
x.api_key = "..."
```
2- Like a comment, post or wiki with invalid id 
```
x.likes.like(post_id=3435)                                  
{'code': 500, 'message': '', 'name': 'Internal Server Error'}

JSX> x.likes.like(comment_id=2344)                               
{'code': 500, 'message': '', 'name': 'Internal Server Error'}

JSX> x.likes.like(wiki_page_id=12332)                            
{'code': 500, 'message': '', 'name': 'Internal Server Error'}
```
3- Expected Result: you should get 404 with not found message instead of 500

4-  Do another like with the any of the  invalid ids
```
JSX> x.likes.like(post_id=3435)                                                                                                                                                                 
{'id': 17, 'createdBy': {'id': 1, 'guid': 'b9ad4840-cc3b-4408-8483-1be1f0c7e006', 'display_name': 'admn amin', 'url': 'http://10.102.71.171:8280/u/admin/'}, 'createdAt': '2019-11-05 12:38:57'}
```

5- Actual Result: A fake like has been created, Expected Result: still should get 404 with not found message

**Comment by john-kheir** [comment]
Issue fixed

**Comment by despiegk** [comment]
where is the doc, I want to see it working too

**Comment by rkhamis** [comment]
@despiegk https://github.com/threefoldtech/jumpscaleX_libs/blob/master/JumpscaleLibs/clients/freeflow/README.md
