### ISSUE TITLE
BCDB public interface

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#14]
child of https://github.com/threefoldtech/jumpscaleX_threebot/issues/160
- let anyonw use the BCDB as generic blockchain for setting/getting info

**Comment by despiegk** [comment]
walleed is working on it,

**Comment by despiegk** [comment]
we need to make sure is in story or story

**Comment by rkhamis** [comment]
included in scope of issue: https://github.com/threefoldtech/jumpscaleX_threebot/issues/160
