### ISSUE TITLE
Reload bcdb data after changing the seed 

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtech/jumpscaleX_core#140]
* export the current bcdb  ` j.data.bcdb.system.export(exportpath, False)`
* reconfigure nacl with different seed `j.data.nacl.configure(privkey_words=newseed)`
* then import the exported  data

**Comment by andrewayoub** [comment]
Implemented in a separate package here https://github.com/threefoldtech/jumpscaleX_threebot/commit/e9931962626154b5222106a91e7e173f09022213

**Comment by andrewayoub** [comment]
### Verification steps:
1- start threebot server and load registration package, or use the registration package factory instead `j.threebot.package.registration.start()`  
2- get a gedis client to your threebot
3- check your current seed `j.data.nacl.words`
4- call the reseed method using gedis client `gedis_client.actors.registration.reseed("{YOUR_NEW_SEED}")`
5- restart your kosmos shell
6- now you should have the new seed loaded without losing any of your configs stored in bcdb

**Comment by siddiquagig** [comment]
Verified

```
get Gedis client to your threebot
JSX> j.clients.gedis.get(port=8901)
# JSXOBJ:
## .gedis.client
ID: 22
 - name                : main
 - host                : 127.0.0.1
 - port                : 8901
 - namespace           : default
 - threebot_local_profile: default
 - password_           :

- Check Current seed:
JSX> j.data.nacl.default.words
'inhale setup banana proud banner toward rural royal garlic machine design multiply avoid list mix hire celery aware bulb frame drink knee december slender'

- Reseed : 
JSX> gedis.actors.registration.reseed("outside bag garlic surround misery climb stone ordinary obvious account adjust salon despair wave receive actor flee volcano rookie blade mind camera elbow stuff")

```

Then exit out of shell and check the new seed:

![image](https://user-images.githubusercontent.com/25789724/67671658-cc048a80-f98f-11e9-86ac-0e0474009563.png)
