### ISSUE TITLE
Ensure network manager is compatible with 0-OS networking

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#143]
During the testnet phase, we want to make networking as simple as possible for user. The idea proposed was to only allow them to deploy predefined appliances.
Predefined means they don't have to manage their network manually. But in 0-OS, all containers requires to be connected to a network and assigned an IP. So somehow, a network have to be created automatically for them.

The proposed solution for that problem was to automatically expose all the created workloads thought the http/tcp gateways.

This issue is here to see if the current implementation of this gateway is compatible with 0-OS networking and if both can be used together.

The gateway network is composed of 3 machine interconnected with wireguard.
These 3 machines hosts a DNS and a TCP router. The idea is to proxy public internet traffic from these 3 machine into private network on 0-OS node.
The architecture is explained at: https://github.com/threefoldtech/jumpscaleX_threebot/issues/50

Here is the code used by these proxy:
- https://github.com/threefoldtech/jumpscaleX_core/tree/development/JumpscaleCore/tools/wireguard
- https://github.com/threefoldtech/jumpscaleX_libs_extra/blob/master/JumpscaleLibsExtra/tools/tf_gateway/TFGateway.py
- https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/gridnetwork/actors/gridnetwork.py

**Comment by zaibon** [comment]
I've done a first code review of the [gridnetwork](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/gridnetwork/actors/gridnetwork.py) actor and I have not found a way for this to be used with 0-OS.

In 0-OS to create a network you needs the following:
- network IP range
- list of peers of the network (a peer being a node)
  - for each peer/node:
     - subnet of the network IP range
     - optional endpoint
     - public key
     - list of allowed IPs

The gridnetwork doesn't allow me to get any of these information and thus I can't create a valid 0-OS network from it. I also don't seems to understand how I'm supposed to configure the tf-gateway to forward traffic from public internet to a private IP/port inside a node.

**Comment by grimpy** [comment]
inside the gridnetwork you only connect to endpoints which will allow you to connect to any node part of the network it will return you all public informations about the endpoints and nothing about the other connected nodes.

if you want to use the tf-gateway you need to register your double name via the [namemanager](https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threefold/namemanager/actors/namemanager.py#L28)

**Comment by zaibon** [comment]
I tried to use the gridnetwork actor to create a new network and add a peer to it:

```python
JSX> e.actors.gridnetwork.network_add('zaibon_test','172.22.0.0/16')                                                                                                                                                                           
## actors.default.gridnetwork.network_add.16c54214bfcd2a5b61f789be085a1d14
 - res                 : True


JSX> res = e.actors.gridnetwork.network_peer_add('zaibon_test','dev_vm','0UjFRM5xtqU7L3Mc45qc6jJCHN182up2bWqQI8hsIhQ=')                                                                                                                        
JSX> res.endpoints                                                                                                                                                                                                                             
[]

JSX> res.network_private                                                                                                                                                                                                                       
'172.22.0.1/16'

JSX> e.actors.gridnetwork.network_endpoint_add?
network_endpoint_add(self, networkname='', sshclient_name='')
```

So I get stuck at the `network_endpoint_add method`. This method requires a ssh client name. I don't get how this work or how a threebot from a user would know what to pass in this argument.

**Comment by zaibon** [comment]
After a chat with @despiegk to see how we can integrate the current tf_gateway with 0-OS. A new solution has been found instead of trying to directly connect 0-OS networks to tf_gateway nodes.

see :
