### ISSUE TITLE
container-kosmos fails after mac installation

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#144]
@coeneivan is having issues with the container installation.

Steps:
```
/tmp/jsx container-install
/tmp/jsx container-kosmos
```
![tg_image_3500253966](https://user-images.githubusercontent.com/6323012/67668228-2f82be00-f978-11e9-8fcf-91095abef94b.jpeg)

![photo_2019-10-28_10-48-23](https://user-images.githubusercontent.com/6323012/67668212-27c31980-f978-11e9-98fd-692d9911b174.jpg)

**Comment by siddiquagig** [comment]
Its working fine now

**Comment by zaibon** [comment]
@coeneivan can you confirm the issue is solved for you ?

**Comment by coeneivan** [comment]
@zaibon It is indeed solved. Had a conversation with @siddiquagig before he closed it :)
