### ISSUE TITLE
What should I do to be able to change schema used in BCDB ?

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#146]
I would like to know what is the process I need to follow to be able to modify some schema that are used in BCDB?

My flow is simple:
- create a jsx schema
- use this schema in an actor, store some object in BCDB
- modify the schema (bug or new bushiness requirement)

Expected behavior: continue being able to load and use the actor after schema modification.
Actual behavior: actor doesn't load and get error like ` Could not find schema with url:...`

I'm not asking to create something new here. I just need some documentation on how is this supposed to be done.

**Comment by BolaNasr** [comment]
@zaibon  i understand your point good , that's issue in our BCDB because any schema change it's change the md5 of this schema and when you want get data we didn't find because the old md5 doesn't exist yet and for BCDB this url doesn't exist 

shoud get model again with new schema 
**we lose our data** 
Solution: that i did before and it deleted ( make migration from old one to new one)
Work around solution : destroy your bcdb

**Comment by zaibon** [comment]
Something else I tried:
- export the bcdb
- create a new schema version (change the version number of the schema from 1 to 2)
- load the new schema version
- import the data back to bcdb

This didn't work and I can't access the data created from schema version 1 using schema version 2.

>  Solution: that i did before and it deleted ( make migration from old one to new one)

This doesn't exsit anymore ?

>  Work around solution : destroy your bcdb

This is not a solution. I cannot loose data. This is a data base... not a cache.

**Comment by BolaNasr** [comment]
@zaibon 
> This doesn't exsit anymore ?

yes it's deleted

> This is not a solution. I cannot loose data. This is a data base... not a cache.

yes make sense

**Comment by rkhamis** [comment]
We'll add a fix option to the bcdb. Which will upgrade the object to its
latest version of the schema.

**Comment by rkhamis** [comment]
issue will be addressed in: https://github.com/threefoldtech/jumpscaleX_core/issues/155
