### ISSUE TITLE
Server is not properly responding to options method

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/jumpscaleX_core#148]
Browsers automaticly send options headers. The server is not properly responding to this http method. Can we have the server respond correctly to the options request?

<img width="640" alt="image" src="https://user-images.githubusercontent.com/17977313/67931117-87603580-fbc1-11e9-9f97-894aa2d789ac.png">

![image](https://user-images.githubusercontent.com/17977313/67931072-6f88b180-fbc1-11e9-8d80-a89f69e2127a.png)

**Comment by abom** [comment]
Should by resolved by https://github.com/threefoldtech/jumpscaleX_threebot/commit/db28c7889812eb830a392f8ee267c7e7ad828f4f.

**Comment by abom** [comment]
To verify, you can simply call any actor:

```
curl -X OPTIONS https://172.17.0.2/web/gedis/http/myjobs/list_jobs -k -i
```

This should work (not returning method not allowed)
```
HTTP/1.1 200 OK
Server: openresty/1.13.6.2
Date: Thu, 07 Nov 2019 08:48:24 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 0
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: Origin, Accept, Content-Type, X-Requested-With, X-CSRF-Token
```

**Comment by Pishoy** [comment]
verified as above
jsx version 
 
```
3BOTDEVEL:jsx:jumpscaleX_threebot: git log -1
commit a45a1bef5863a0c75900814950ff761f0e466c78 (HEAD -> development, origin/development, origin/HEAD)
Author: serboctor <boctor.sarah@gmail.com>
Date:   Wed Nov 6 17:29:42 2019 +0200

    Fix container destroy typo

```
