### ISSUE TITLE
Remove package from threebot server don't work unless server is restarted

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#149]
### Steps:
1- Start threebot server.
```
cl = j.servers.threebot.local_start_default()
```
2- Add any package (`alerta` for example) and then reload.
```
cl.actors.package_manager.package_add("/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/alerta") 
cl.reload()
```
3- Remove this package and reload.
```
cl.actors.package_manager.package_delete("alerta")
cl.reload()
```
### Expected result:
`alerta` should be removed.

### Actual result:
`alerta` is still loaded.
It is only removed if threebot server is stopped and started it again.

**Comment by rkhamis** [comment]
Pacakges should implement their uninstall function.

**Comment by despiegk** [comment]
I think an wait

**Comment by RafyAmgadBenjamin** [comment]
Fixed:
* in case of ```.conf``` files related to the package we now remove it and reload the ```openresty``` to reload the new configuration 
PR
https://github.com/threefoldtech/jumpscaleX_core/pull/461
* In case a running server or anything related to the current package specifically it will be the responsibility of the  package maker

**Comment by RafyAmgadBenjamin** [comment]
**verification steps:**
* j.servers.threebot.local_start_explorer(background=True)  
* package_manager_gedis= j.clients.gedis.get(name="test26",port=8901, package_name="zerobot.packagemanager") 
* package_manager_gedis.actors.package_manager.package_add(path = '/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/directory')
* check ```https://{local_host}/tfgrid/directory/```, It will be working 
* package_manager_gedis.actors.package_manager.package_delete("tfgrid.directory")    
* check ```https://{local_host}/tfgrid/directory/```, It will be no longer working

**Comment by john-kheir** [comment]
Verified
