### ISSUE TITLE
3bot client using 3bot phonebook [development_threebot_client2]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#15]
- use pub/priv key encryption to let 3bots talk to each other using generic client

BLOCKED. TO BE REVISITED

**Comment by despiegk** [comment]
core is done, encryption needs to be enabled.
j.clients.threebot.client_get ...

there is issue with actors don't load automatically

there is example code in tutorials

**Comment by Hamdy** [comment]
Pull request added 
https://github.com/threefoldtech/jumpscaleX_core/pull/157

**Comment by Hamdy** [comment]
@serboctor 
Issue needs discussion

3 bot server now when starts, it used gedis client
and gedis client needs to send auth command to local gedis server and to do so, it needs 3 bot me instance pre configured

The thing is, we now force a 3 bot me instance to exist before starting 3 bot server using needsexist = True 
but to properly register a me instance we probably need 3bot server running a head and using actors to do so
makes it an Egg & Chiecken problem
one solution is to be forgiven in this case, allow needsexists=False which will create an empty instance with tid=0 which can be used to authenticate gedis client to gedis server locally and makes 3bot server happy 
and then we later can override it from kosmos using j.tools.threebot.init_my_threebot after adding proper packages and we can set it with the right info and it will delete the old empty me instance
another solutions is to skip authentication for local gedis server which I don't like

**Comment by Hamdy** [comment]
@despiegk  will u please take a look ?

**Comment by xmonader** [comment]
I'll move this to the next milestone, no way we can do testing for this in the current milestone.
