### ISSUE TITLE
Content type of .vue file is not application/octet-stream

### ISSUE THREAD

**Issue by coeneivan** [threefoldtech/jumpscaleX_core#150]
The content type of a .vue file is currently text/html and this should be application/octet-stream in order to let the front end parse correctly.

![image](https://user-images.githubusercontent.com/22675385/67954328-0e78d200-fbf1-11e9-8ea0-a9c4a1b1b3e0.png)

**Comment by zaibon** [comment]
@abom : https://github.com/threefoldtech/jumpscaleX_core/commit/a97c79ec6ce983ad31e23f63d3efe070af0dbc19#r35761495

**Comment by abom** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/fd3d45189897f59f36e59230ce329b75002b2083
