### ISSUE TITLE
enable_cors function needs to be reusable

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#153]
```
➜  threefoldtech ag "def enable_cors"
jumpscaleX_core/JumpscaleCore/servers/gevent_rack/ServerRack.py
86:            def enable_cors(fn):

jumpscaleX_core/JumpscaleCore/servers/gedis_http/GedisHTTPFactory.py
21:def enable_cors(fn):

jumpscaleX_threebot/ThreeBotPackages/zerobot/webinterface/bottle/BottleInterfaceFactory.py
14:def enable_cors(fn):

jumpscaleX_threebot/ThreeBotPackages/zerobot/chat/ChatFactory.py
25:def enable_cors(fn):

jumpscaleX_threebot/ThreeBotPackages/zerobot/wiki/BottleWebServerWiki.py
13:def enable_cors(fn):
```

Make enable_cors reusable instead of copying it

**Comment by RafyAmgadBenjamin** [comment]
**The links which have cors:**
* https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/gevent_rack/ServerRack.py

* https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/gedis_http/GedisHTTPFactory.py

* https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/webinterface/bottle/BottleInterfaceFactory.py

* https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/chat/ChatFactory.py

**Comment by abom** [comment]
I think we can keep it here https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/gedis_http/GedisHTTPFactory.py

And just import it in every other place.

**Comment by abom** [comment]
I thought of away to get a enable_cors decorator with optional allowed set of methods, but let's keep it for later.

**Comment by RafyAmgadBenjamin** [comment]
I have reused the enable_cors implemented in GedisHTTPFactory.py and imported it into the other files.

**Comment by Pishoy** [comment]
tested by Rafay
