### ISSUE TITLE
web_resources cleanup

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#156]
/sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/servers/openresty/web_resources

- All of the templates should be in the correct package if not already
- All of the assets should be in the correct package if not already
- All of moon files should be removed

**Comment by RafyAmgadBenjamin** [comment]
***PR***
https://github.com/threefoldtech/jumpscaleX_core/pull/249

**Comment by RafyAmgadBenjamin** [comment]
To verify:
* start ```Wiki package``` and make sure that everything works as its default behavior.
* start ```Chat package``` and make sure that everything works as its default behavior.

**Comment by siddiquagig** [comment]
Verified 

Both are working as per default behaviour.
