### ISSUE TITLE
Adding packages inconsistently doesn't load the actors

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/jumpscaleX_core#159]
Commands:

```
cl = j.servers.threebot.local_start_default(web=True)
cl.actors.package_manager.package_add(git_url="https://github.com/threebotapps/interface.git")
cl.actors.package_manager.package_add(git_url="https://github.com/threebotapps/contacts.git")

```

When running the commands above the UI start and I can access it but the actors don't always start, I then have to restart the 3bot, clear bcdb and sometimes use 'js_init generate'. To make to work.

Looking at the logs with 'tmux at' doesn't show any errors whatsoever.

**Comment by MathiasDeWeerdt** [comment]
It could be related to the order the packages are loaded and the rules NGINX uses. 
If I switch contacts and interface around it seems to be working little bit more consistent.

**Comment by xmonader** [comment]
you need to do cl.reload afterwards.

**Comment by rkhamis** [comment]
@MathiasDeWeerdt please close if this fixes your issue

**Comment by abom** [comment]
This fix will enable fix that when called from gedis http https://github.com/threefoldtech/jumpscaleX_threebot/issues/232.

**Comment by siddiquagig** [comment]
Verified

If it is wanted in the same kosmos session , reload should be used.

![image](https://user-images.githubusercontent.com/25789724/68852649-bd3d0800-06f1-11ea-8bb4-b9f05fa6fca4.png)
