### ISSUE TITLE
3bot registration client

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#16]
- let people register their 3bot on the public BCDB
- let people update their 3bot registration info

**Comment by zaibon** [comment]
For this task https://github.com/threefoldtech/tf_cockpit/issues/12, I need to have the specification regarding how identification will work on the grid with BCDB.
specifically:
- detail about what is the identity of a user and how does that map with current 3bot app
- schema of an identity (I'm interested in the type of all the field)
- Would be nice to have some detailed flow basic uses cases:
 - new user register
 - user with already 3bot app account want to be register on BCDB
- What is the plan regarding migration from IYO to 3bot ?

**Comment by despiegk** [comment]
all done
see examples in tutorials
