### ISSUE TITLE
error in ssh client 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#160]
ssh client ask for password in all methods, even I already added it in the creation of ssh client.  

it works correctly only in `file_copy`  method
```
ssh_client = j.clients.ssh.get(name="ssh_test_client", addr =IP, port=PORT, login=LOGIN, 
passwd=password)
ssh_client.file_copy("/tmp/test", "/tmp/test")
```

 in execute method for example it ask for password
```
ssh_client.execute(cmd="ls /home/")                                                                                                                                                                
dina@192.168.21.144's password:

```

**Comment by ranatrk** [comment]
Should pass interactive parameter: 
` ssh_client.execute("ls /home/", interactive=False) `
because the default of `interactive = True` resulting in asking for the password instead of passing it

**Comment by Pishoy** [comment]
works with me without identify the interactive flag 
```
JSX> ssh_client = j.clients.ssh.get(name="ssh_test_client", addr='172.17.0.1', port=22, login='pishoy', passwd='xxxxx')                                                                                  
JSX> ssh_client.execute(cmd="ls /home")                                                                                                                                                                     
backup	pishoy
Connection to 172.17.0.1 closed.
(0, '', '')

JSX> ssh_client.file_copy("testfileincontainer","/tmp/test")                                                                                                                                                

```
- jsx version 
```
3BOTDEVEL:3bot:jumpscaleX_core: git log -1
commit 33253cf64e9a48fd24dbc7299fc1b0c5a0bf361b (HEAD -> development, origin/development, origin/HEAD)
Author: xmonader <xmonader@gmail.com>
Date:   Sun Nov 10 17:24:35 2019 +0200

    don't start myjobs in jsx wiki-load, depends on 3bot to have it
```
```

**Comment by Dina-Abd-Elrahman** [comment]
interactive option doesn't exist in almost all methods in ssh_client. 

Ex: 
- ssh_authorize.
- download.
- upload.
- portforward_to_local.
- portforward_kill. 

and all of them require password when you execute them.

**Comment by ranatrk** [comment]
Issues that will be addressed:

- [ ]  **ssh_authorize**, **mosh** : will add interactive option
- [ ] **download** , **upload**: use `j.sal.fs.copyDirTree(...)` which do not provide interactive option
- [ ] **portforward_to_local**, **portforward_kill** : cmd executed should had password passed in case of using password

**Comment by xmonader** [comment]
sshclient,  executors tests are passing now

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
