### ISSUE TITLE
Getting two different gedis clients in the same process raises an error

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#163]
```
JSX> explorer = j.clients.gedis.get(name="explorer", port=8901, host="explorer.testnet.grid.tf")
JSX> host = j.clients.gedis.get(name="local", port=8901)
Thu 07 10:21:23 ema/SchemaFactory.py -  95 - get_from_url                       : EXCEPTION: 
    Could not find schema with url:actors.default.html_test.hello.c0fbcc8b0ca07aa6be8fb2609f4afc08
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in get
    113    jsconfig = self._new(name=name, autosave=autosave, **kwargs)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSConfigsBCDB.py in _new
    93    jsconfig = jsconfig_klass(parent=self, jsxobject=jsxobject, **kwargs_to_class)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py in __init__
    63    self._init(**kwargs)
/sandbox/lib/jumpscale/Jumpscale/clients/gedis/GedisClient.py in _init
    44    self.reload()
/sandbox/lib/jumpscale/Jumpscale/clients/gedis/GedisClient.py in reload
    98    self._actorsmeta[actor_name] = j.servers.gedis._cmds_get(key, data)
/sandbox/lib/jumpscale/Jumpscale/servers/gedis/GedisFactory.py in _cmds_get
    31    return GedisCmds(namespace=namespace, name=name, data=data)
/sandbox/lib/jumpscale/Jumpscale/servers/gedis/GedisCmds.py in __init__
    51    self.cmds
/sandbox/lib/jumpscale/Jumpscale/servers/gedis/GedisCmds.py in cmds
    98    self._cmds[cmd.name] = GedisCmd(namespace=self.namespace, cmd=cmd)
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/JSBase.py in __init__
    63    self._init(**kwargs)
/sandbox/lib/jumpscale/Jumpscale/servers/gedis/GedisCmd.py in _init
    29    self.schema_in = j.data.schema.get_from_url(url=cmd.schema_in_url)
/sandbox/lib/jumpscale/Jumpscale/data/schema/SchemaFactory.py in get_from_url
    95    raise j.exceptions.Input("Could not find schema with url:%s" % url)
-----------------------------

None
JSX> 
```

@andrewayoub says it has to do with randomly generated urls for actors' `schema_in` and `schema_out`.

**Comment by serboctor** [comment]
This seems to be related to having two actor files ni the same directory and then getting two clients for two servers that have both actors.

**Comment by serboctor** [comment]
When I get the first client, the two actor files had the same schema for some of the actors, this causes one of the actors to get loaded with the other actor's schema(which was loaded first) because of the md5.
when the other client is loading the actors, it tries to get the schema of the actor that was loaded second in the first client using the schema's url, but it's not found because we don't have it locally because it used the schema of the actor that was loaded first. I feel like the problem is two folds somehow, first that an actor uses the schema of another actor because it has the same md5, and secondly that the second client is affected by how the data is loaded in the first one. I am still investigating and trying to understand the whole flow and what could be changed to fix it.

**Comment by muhamadazmy** [comment]
I don't know the implementation details of actors, or how schemas are loaded. But here are my 2 cents based on @serboctor comment above.

- Schemas should be reusable even if multiple actors are using it. In other words schemas should have global unique IDs (md5sums of the unique URL should work).
- Scheam loaded should make sure that no different schemas has the same hash/url.
- Once loaded, the schema IDs should be globally usable by different actors. In other words, it should not matter which actor loads first, as long as the schema ID is already available and loaded in the schema loader.

Another solution, in case the above procedure is too much changes work (Again, I am ignorant regarding the internals). Is by making sure that `package` name is used as a prefix in the schema URL for example:
- Package A: defines schema with URL `animal.dog` 
- Package B: also defines schema with URL `animal.dog` 
While loaded, the FQDN of the schema should be `A.animal.dog` and `B.animal.dog` so conflict is resolved.

**Comment by serboctor** [comment]
@muhamadazmy the issue is not for schemas that have urls, those kind of schemas are reusable just fine, and their md5s are always unique because the url is unique, and you can use the same schema in different places.
It's for actor schemas like this one https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/zerobot/wiki/actors/html_test.py#L9 
what @andrewayoub and I tried to do, is create a url for these schemas when they're being loaded and linked to actors, but that blow up somewhere else, so we still need to pinpoint all the areas affected by this.

**Comment by muhamadazmy** [comment]
@serboctor I see, but a unique url still can be generated using `package.actor.method.(in or out)` names, no ?

**Comment by serboctor** [comment]
@muhamadazmy the url that @andrewayoub and I added was unique, that wasn't the problem. but it seems that the change affects other parts we weren't aware of. But like I said, we didn't investigate further, yet.
