### ISSUE TITLE
Refactor __repr__ that uses print statement to print ansi colors

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_core#169]
In some places, we use `print` statement inside `__repr__` to print ansi colors, this is too much annoying while e.g. typing in `kosmos` shell, as characters are printed everywhere.

For example in `JSXObject.py`:

```python
    def __repr__(self):
        # FIXME: breaks in some cases in docsites generation needs to be cleanly implemented
        out = self._str_get(ansi=True)
        # # #TODO: *1 when returning the text it does not represent propertly, needs to be in kosmos shell I think
        # # IS UGLY WORKAROUND
        print(out)
        return ""
```

prompt-toolkit support printing formatted text, so, this seems to be resolvable.

**Comment by siddiquagig** [comment]
Works

Typed in kosmos ```bcdb = j.data.bcdb.WebDavProvider```

![image](https://user-images.githubusercontent.com/25789724/69007454-5c166e00-0957-11ea-89e0-5cb9d5d00532.png)

**Comment by abom** [comment]
@siddiquagig Can you please test the colors is printed if you did the following for example?

`j.clients.gedis.main_gedis_threebot`

**Comment by siddiquagig** [comment]
Verified  , colors are printed 

![image](https://user-images.githubusercontent.com/25789724/69028061-43a36380-09ea-11ea-97ba-5469f5c5dbad.png)
