### ISSUE TITLE
BCDB: Create new model with same name, updates the old one [development_fixes]

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#171]
### Steps
1- Create schema with parameter name
```
scm = """ 
        @url = test.schema.1 
         name** = "" (S)
         number = (I)
         """ 
schema = j.data.schema.get_from_text(scm) 
```
2- Create test bcdb.
```
bcdb = j.data.bcdb.get("test")
```
3- Create new model from this schema and set `name="test"`
```
model = bcdb.model_get(schema=schema)
schema_obj = model.new()
schema_obj.name = "test"
schema_obj.number = 10
```
4- Save this model
```
schema_obj.save()
```
5- Create another model with same name
```
schema_obj2 = model.new()
schema_obj2.name = "test"
schema_obj2.number = 55
```
6- Try to save the second model
```
schema_obj2.save()
```

### Expected result
Raise an error as there was a model with same name has been already saved.

### Actual Result 
The old model was updated.
```
JSX> bcdb.get_all()                                                                                                                                                                                         
## .1
ID: 1
 - name                : test
 - number              : 55

[]
```

**Comment by rkhamis** [comment]
@AhmedHanafy725 name is a unique field by default. It makes sense to me that if I create something with the same name, it will use the same instance, since it's the only instance that can exist.

the other option is to raise an error on save.

**Comment by john-kheir** [comment]
@rkhamis Getting what you are saying but then there should be an update option instead of creating a new object (which is confusing) .. I think the safest way to raise an error on save to eliminate confusion .. plus i'm not sure if this behaviour can make a problem in the future when for instance a user2 want to use the schema for the same name of another user

**Comment by RafyAmgadBenjamin** [comment]
* Prevent saving object without a name if it's schema has a name.
* Prevent adding or updating new object with a name that already exists. (it must be unique)
* Adding test scenarios ```18_save.py```
* Fix the tests which were affected by the changes ```4_models.py``` and ```6_sqlitestor_base.py``` 
PR:
https://github.com/threefoldtech/jumpscaleX_core/pull/227

**Comment by xmonader** [comment]
@serboctor  reverted the code.  We need to be properly review the packages and other jsx code that `abuse` this bug. I'll move it to the next milestone to recheck

**Comment by serboctor** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/a6a7ec161201eca4571bf75ec7d2ffd3c0dedf6e

**Comment by xmonader** [comment]
all indexed fields are checked for uniqueness and having a value.

**Comment by AhmedHanafy725** [comment]
branch: development
commit: 5e2e297de52c8d39af7731e3547efdb1e37ca9bc

It is still updating the saved object.
![image](https://user-images.githubusercontent.com/41957921/70700812-fd34e200-1cd3-11ea-9b53-05d98d7073e8.png)

**Comment by serboctor** [comment]
Fixed on `development_fixes` branch.
here https://github.com/threefoldtech/jumpscaleX_core/commit/5041d711bdf70c6afe88ea1d646d7f104663fae9 and here https://github.com/threefoldtech/jumpscaleX_threebot/commit/0acd6abd3ca1243aa3407e345f835f153f30dc21

**Comment by hossnys** [comment]
verified on development_fixes branch

![Screenshot from 2019-12-15 12-55-13](https://user-images.githubusercontent.com/26298009/70861671-38d0e580-1f3a-11ea-9db5-e991b20ffd3e.png)
