### ISSUE TITLE
Make jsx tests run green

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#172]
### Core
- [x] bcdb (#213 , #171) 
- [x] sshkey
- [x] sshagent
- [x] gedis server (https://github.com/threefoldtech/jumpscaleX_core/issues/128)
- [x] coreX server
- [x] smtp server 
- [x] startupcmd (#101)
- [x] threebot server (#208, #209, #211)
- [x] zdb server (#213)
- [x] odoo server (https://github.com/threefoldtech/jumpscaleX_core/issues/222)
- [x] etcd server (#158)

### Libs
- [x] github client
- [x] sal dnsmask (low prio)
- [x] sal ubuntu    (low prio)

### Libs_extra
- [x] openvcloud client (very low prio)
- [x] sal zos (low prio)
- [x] sal mongodb (very low prio)
- [x] radicale server (to check @Hamdy ) 
- [x] capacity tests (to check)
- [x] tools storybot (very low prio)

### Threebot
- [x] wikis (high)
- [ ] phonebook (high)
- [ ] threefold registry (high)
- [ ] package token 
- [ ] workloadmanager (high)
- [ ] directory (high)
- [ ] ffbrowser   (to check) 
- [ ] fileserver (to check)
- [ ] appstore2 (
- [ ] bottle_web (high)
- [ ] bcdb (high) 
- [ ] tftexplorer  (to check)
- [ ] communiy_bot (high)

### Installation
(#198, #189, #185, #184, #182, #180 )

**Comment by AhmedHanafy725** [comment]
#### Libs
Skip `sal dnsmasq` and `github client` as they are low priority and fix `sal ubuntu`

**Comment by AhmedHanafy725** [comment]
#188 this PR fixes sshagent and sshkey tests.

**Comment by AhmedHanafy725** [comment]
#### Libs extra
Skip all running tests as these modules tests are not used (capacity, ovc, ...)

**Comment by AhmedHanafy725** [comment]
wikis is fixed in #228

**Comment by despiegk** [comment]
moved to story 
https://github.com/threefoldtech/home/issues/453

this was not a FR or BUG
