### ISSUE TITLE
error in shell method in ssh client 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#176]
- error in shell method in ssh client. 

ssh_client = j.clients.ssh.get(name="ssh_test_client", addr =ADDR, port=PORT, login=LOGIN, passwd=password)

ssh_client.shell(cmd="ls /")

![ff](https://user-images.githubusercontent.com/21218053/68544485-53a8bb00-03cc-11ea-8c6a-59dd7a730cdc.png)

**Comment by Dina-Abd-Elrahman** [comment]
- shell method is interactive, so i think there is no need for `cmd` option

**Comment by waleedhammam** [comment]
no shell in sshclient anymore
