### ISSUE TITLE
ZDB client documentation

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#179]
For parent issue of #177 docs is needed.

**Comment by andrewayoub** [comment]
added here 
https://github.com/threefoldtech/jumpscaleX_core/blob/95029db1cd80fee217ed6e5bb1d6c4cd3e4d2a6b/JumpscaleCore/clients/stor_zdb/README.md

**Comment by xmonader** [comment]
Thank you so much @andrewayoub

**Comment by siddiquagig** [comment]
Document is clear  on the steps
