### ISSUE TITLE
Installer : install using --branch doesn't work [development_fixes2_installer]

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#182]
## Steps 
try to install from branch  (/tmp/jsx container-install --branch master)

## Issue 
always install from development branch

**Comment by RafyAmgadBenjamin** [comment]
Fixed  PR:
https://github.com/threefoldtech/jumpscaleX_core/pull/388

**when verifying this issue you have to make sure that code already merged  on the branch that you are going to use during installation.**

**Comment by siddiquagig** [comment]
Verified 

![image](https://user-images.githubusercontent.com/25789724/71554570-44dc9d00-2a3a-11ea-9278-06b22f012b8d.png)
