### ISSUE TITLE
BCDB: BCDBFS (can't find object with obj id)

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#183]
![image](https://user-images.githubusercontent.com/64129/68546658-77c2c700-03e1-11ea-81bb-b13716412c97.png)

searching files always fails.

**Comment by xmonader** [comment]
this case happened with inconsistent state of sonic and bcdb on a dirty container.

**Comment by gmachtel** [comment]
To check whether it is a bug, or simply due to the dirty container.

**Comment by john-kheir** [comment]
tried to reproduce with clearing bcdb, and without resetting sonic server data
then searched for sonic, but couldn't reproduce
