### ISSUE TITLE
Test basseclasses

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_core#19]
- [x] kosmos working
- [x] BCDB working as expected with baseclasses
    - [x] indices exist after saving
    - [x] indices behavior working as expected when saving/deleting 
    - [x] indices exist after terminating kosmos/ killing redis
    - [x] Parent -> Child1 -> Child_of_Child1 : deleting Child1 updates Child_of_Child_1
    - [x] Parent -> Child1 -> Child_of_Child1 : deleting Child_of__Child1 updates Child1
- [x] Builder methods
- [x] Client/Server configs
    - [x] new
    - [x] save
    - [x] get (if exists)
    - [x] delete
    - [x] get if deleted (doesn't exist)
    - [x] delete (if doesn't exist)
- [x] Baseclass tests: `j.tutorials.baseclasses.configobjects.test()` , `j.tutorials.basesclasses.world.test()`

**Comment by ranatrk** [comment]
- Builder methods steps (example zdb) :
  - build `j.builders.db.zdb.build(reset=True)`
  - install `j.builders.db.zdb.install(reset=True)`
  - start `j.builders.db.zdb.start(reset=True)`

**Comment by ranatrk** [comment]
Client/Server configs steps:
- new : 
    ```python
    cl = j.clients.tfchain.new("test_tfchain")
    ```
- save:  
    ```python
    cl.save()
    ```
   **note: cl now has new index _id**
- get: 
    ```python
    j.clients.tfchain.get("test_tfchain")
    ```
    __OR__ 
     ```python
    j.clients.tfchain.test_tfchain
    ```
- delete 
    ```python
    cl = j.clients.tfchain.get("test_tfchain")
    cl.delete()
    ``` 
   **note:cl not in list retured by `j.data.bcdb.system.get_all()`**
- get if deleted (doesn't exist)
    ```python
    cl = j.clients.tfchain.get("test_tfchain")
    cl.delete()
    # try j.clients.tfchain.test_tfchain
    ``` 
- delete instance that doesn't exist (no error)
    ```python
    cl = j.clients.tfchain.delete("test_tfchain_2")
    ```

**Comment by ranatrk** [comment]
BCDB indices:
- saving client as previous: cl._id = 4

> Client/Server configs steps:
> 
>     * new :
>       ```python
>       cl = j.clients.tfchain.new("test_tfchain")
>       ```
> 
>     * save:
>       ```python
>       cl.save()
>       ```

- Saving/deleting behavior on bcdb indices:
```python
cl = j.clients.tfchain.new("test_tfchain")
cl.save() # cl._id =  4

cl2 = j.clients.tfchain.new("test_tfchain_2")
cl2.save() # cl2._id =  5

cl2.delete()
cl3 = j.clients.tfchain.new("test_tfchain_3")
cl3.save() # cl3._id = 5

cl.delete()
cl4 = j.clients.tfchain.new("test_tfchain_4")
cl4.save() # cl4._id = 6

# Now exists in bcdb saved: cl3 and cl4
```

- restart kosmos/ kill redis: cl3 and cl4 returned in list when using `j.data.bcdb.system.get_all()` and can be accessed using get()

**Comment by ranatrk** [comment]
**Concern**
Client/Server configs : 
When class inherits from JSConfigsBCDB, the get() creates a new instance and saves it rather than just creating it. This is because the default param of save = True.

**Comment by ranatrk** [comment]
**Concern 2**
Case: Parent -> Child1 -> Child_of_Child1
When deleting instance of Child1 created, Child_of_Child1 will still have mother_id as the id of Child1

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
