### ISSUE TITLE
Features for testing using JS testrunner [development_testrunner]

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscaleX_core#190]
As I can see our way to write test cases is missing some of the important testing features. These features are part of any testing framework like the official `unittest` framework. I'm gonna list them as following:

## Core Features:
- **Runner** it should allow us to run a specific test case at any time without needing to run the whole file **and the most important thing here is, Our runner is gonna break if any test cases is failed or raised an error.** , which shouldn't happen in order to have a final report for all tests.

- **Fixtures** like (setUp/tearDown/setUpClass/TearDownClass). This feature helps us to construct the common logic between multiple test cases, and provides special setup/teardown per testcase if needed.
- **Assertions** There are dozens of assertions provide by the official testing framework `unittest`.

- **Reports** There is a standard way to report the test runner results and our testing way doesnt support that.
- **Skip** It is a major function as we need to skip all test cases related to a specific bug.

I strongly recommend using the standard [`unittest`](https://docs.python.org/3/library/unittest.html) library to develop our test cases.

**Comment by john-kheir** [comment]
In addition, if we went ahead with using the `unittest`, we can make a wrapper  to run these tests using jumpscale (the same way we run the current tests)

**Comment by AhmedHanafy725** [comment]
Test runner is added on b09ad056502f602d98945868bec74f819cfb3c47, 22d400334cb5c92fede0311dbf55273309dbab3e

**Comment by john-kheir** [comment]
Docs and reporting are not done yet

**Comment by AhmedHanafy725** [comment]
Now reporting is done and docs can be found [here](https://github.com/threefoldtech/jumpscaleX_core/blob/development_testrunner/docs/Internals/baseclasses/TestTools.md)
