### ISSUE TITLE
Installer: conflict between --scratch and --delete options

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#198]
/tmp/jsx conainer-install --scratch or  --delete options , seams that they do same things , both of them delete the old container and install everything from the begging
so do we need both options? or there is a difference .

**Comment by serboctor** [comment]
Yes, there's a difference. `--scratch` uses the base image `threefoldtech/base`, while normal installation uses `threefoldtech/3bot`. The base image is completely empty so everything is built and installed from scratch and should take longer time. By default if you pass `--scratch`, the installation will also delete the container if it exists. However, the installation using `--scratch` option is currently broken so I am checking it.

**Comment by serboctor** [comment]
Before testing make sure you remove `3bot` from `/sandbox/var/containers/`

**Comment by Dinaamagdy** [comment]
## Steps 
- create docker with normall 3bot image 
- rm 3bot from /sandbox/var/containers/ 
- try --sratch option will delete container and create another one with base image
- try --delete option will delete conatiner but create from same 3bot image
