### ISSUE TITLE
Testing: Test threebot server

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscaleX_core#199]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/383), We need to test the threebot server.

**Deliverables**
- Update all test cases in TestQuality linked to the testing sheet
- Update all the automation test cases 
- Integrated with ZeroCI

**Estimation Time**
- Start with the exploratory testing to find out the estimation time.

**Comment by Dinaamagdy** [comment]
threefoldtech/jumpscaleX_core#209
threefoldtech/jumpscaleX_core#208
threefoldtech/jumpscaleX_core#211
code:
https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/tests/test_threebot.py#L18
