### ISSUE TITLE
error in isconnected property in ssh client 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#206]
error in isconnected property in ssh client, it raises an error in first time, but in second time it run 
without an error. 

- ssh_client = j.clients.ssh.get(name="ssh_test_client", addr =ADDR, port=PORT, login=USER, passwd=PASSWORD)
- ssh_client.isconnected

![error](https://user-images.githubusercontent.com/21218053/68680818-fdbe4980-056a-11ea-9236-497ac68702c1.png)

**Comment by Dina-Abd-Elrahman** [comment]
- it's working now fine.

**Comment by RafyAmgadBenjamin** [comment]
I have tested it and it was not reproducible
