### ISSUE TITLE
Adding multiple packages results in conflicts

### ISSUE THREAD

**Issue by tobiaschielens** [threefoldtech/jumpscaleX_core#207]
When trying to install tfgrid_directory and farmmanagement on the same system, only the first one installed works. Is it possible that the nginx routing is broken when installing multiple packages?

## Install tfgrid first
cl = j.servers.threebot.local_start_default(web=True)
cl.actors.package_manager.package_add(path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreebotPackages/tfgrid/tfgrid_directory/')
cl.actors.package_manager.package_add(path='/sandbox/code/github/threebotapps/farmmanagement')

POST https://172.17.0.2/web/gedis/http/farms/owned_by -> Works 
GET  https://172.17.0.2/farmmanagement/store.js -> loads the index.html from webinterface

## Install farmmanagement first
cl = j.servers.threebot.local_start_default(web=True)
cl.actors.package_manager.package_add(path='/sandbox/code/github/threebotapps/farmmanagement')
cl.actors.package_manager.package_add(path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreebotPackages/tfgrid/tfgrid_directory/')

POST https://172.17.0.2/web/gedis/http/farms/owned_by -> Actor farms does not exist 
GET  https://172.17.0.2/farmmanagement/store.js -> correctly loads the farmmanagement store.js

Farmmanagement: https://github.com/threebotapps/farmmanagement
TFGrid: https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/ThreeBotPackages/tfgrid

**Comment by xmonader** [comment]
please add the generated nginx config on your system for both packages.

**Comment by tobiaschielens** [comment]
**Cockpit: **
location / {
    alias   /sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/tfgrid_directory/frontend/;
    index  index.html;
    try_files $uri $uri/ //index.html;
}

**Interface:**
location / {
    alias   /sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/webinterface/html/;
    index  index.html;
    try_files $uri $uri/ //index.html;
}

**Farmmanagement:**
location /farmmanagement {
    alias   /sandbox/code/github/threebotapps/farmmanagement/html/;
    index  index.html;
    try_files $uri $uri/ /farmmanagement/index.html;
}

**Webinterface**
location /web/ {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header HOST $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_pass HTTP://127.0.0.1:9999/;
}

**Comment by xmonader** [comment]
It looks like you have two packages for root `/` interface and cockpit. 
- if you restart nginx will refuse to start because of the duplicates
- make sure to call cl.reload to reload actors

**Comment by tobiaschielens** [comment]
TFGrid directory is also trying the register on / together with webinterface. TFGrid should not be serving on /

https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid/tfgrid_directory/package.py#L35

**Comment by xmonader** [comment]
# registering tfgrid_directory first
```
None
JSX> cl.actors.package_manager.package_add(path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/tf
   1 grid_directory')                                                                                                             
b'OK'

JSX> cl.actors.package_manager.package_add(path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/tf
   1 grid_directory/')                                                                                                            
b'OK'

JSX> cl.actors.package_manager.package_add(path='/sandbox/code/github/threebotapps/farmmanagement')                               
b'OK'

JSX> cl.reload()                                                                                                                  
JSX> cl.actors.farms                                                                                                                           
<ea9939732e9fd4cd51fec9d9a06e8ede.GedisClientGenerated object at 0x7f9c3e838828>


```

# registering farmmgmt first

```
JSX>                                                                                                                                           
JSX> cl = j.servers.threebot.local_start_default()                                                                                             
JSX> cl.actors.package_manager.package_add(path='/sandbox/code/github/threebotapps/farmmanagement')                                            
b'OK'

JSX>                                                                                                                                           
JSX> cl.actors.package_manager.package_add(path='/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/tfgrid_director
   1 y/')                                                                                                                                      
b'OK'

JSX> cl.actors.farms                                                                                                                           
Tue 12 16:50:28 <stdin>              -   1 - <module>                           : EXCEPTION: 
    AttributeError("'GedisClientActors' object has no attribute 'farms'",)
--TRACEBACK------------------
<stdin> in <module>
    1    
-----------------------------

'GedisClientActors' object has no attribute 'farms'
JSX> cl.reload()                                                                                                                               
JSX> cl.actors.farms                                                                                                                           
<ea9939732e9fd4cd51fec9d9a06e8ede.GedisClientGenerated object at 0x7f4372e6f828>

JSX>  

```

code on latest development and I cloned your repo in `/sandbox/code/github/threebotapps/farmmanagement`

**Comment by zaibon** [comment]
@tobiaschielens : Indeed, tfgrid directory serving on / was a hack, feel free to remove.
But then I would like to know how can I choose these kind of thing ?
Cause depending on the type of 3bot, we need to be able to serve different things on different path.
As far as I know this is not a supported feature yet ? @xmonader

**Comment by xmonader** [comment]
@zaibon I believe the safest bet is having a custom nginx location the same way we did in the chat package

```
            proxy_location = locations.locations_proxy.new()
            proxy_location.name = "chat"
            proxy_location.path_url = "/chat"
            proxy_location.ipaddr_dest = "0.0.0.0"
            proxy_location.port_dest = 8522
            proxy_location.scheme = "http"

            modrewrite_chat = locations.locations_custom.new()
            modrewrite_chat.name = "chatrewrite"
            modrewrite_chat.config = """rewrite ^/(.*)/chatflow/(.*)$ /chat/session/$2;"""
```
the default is `/chat/session/TOPIC` and we rewrite the urls if they're in the format of `/chatflow/TOPIC` to the default.
