### ISSUE TITLE
Threebot server : no way  to stop default_threebot server

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#209]
## Steps
- cl=j.servers.threebot.local_start_default()
- j.servers.threebot.get().stop()    

## Issue 
will just stop zdb and sonic server .
worrkers , lapis and threebot default will keep running , and can't find way to stop them instead of keyboard interrupt .

**Comment by RafyAmgadBenjamin** [comment]
I have fixed it.
**You can run the command below to stop the default instance of threebot server.**
```j.servers.threebot.default.stop()```

**Comment by siddiquagig** [comment]
Verified on development_103

![image](https://user-images.githubusercontent.com/25789724/72047244-84757580-32d3-11ea-8838-a05c7c721092.png)

Successfully stops all sessions zdb ,sonic server , workers , lapis and threebot default  except your own session

**Comment by serboctor** [comment]
The fix for this broke stopping the server if it was started in the background. The `j.server.threebot.stop` is meant to be used only if you start it using `background=True`. I'll reverted this fix, and may be we can think of something else for the case of `background=False`
