### ISSUE TITLE
Testing: Registery Client 

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#210]
Description
As a part of [this thread](https://github.com/threefoldtech/home/issues/383), We need to test registery client

Deliverables

Automation test cases
Integrated with ZeroCI

**Comment by john-kheir** [comment]
PR: https://github.com/threefoldtech/jumpscaleX_core/pull/219/files
Bugs: https://github.com/threefoldtech/jumpscaleX_core/issues/217
question: https://github.com/threefoldtech/jumpscaleX_threebot/issues/231

**Comment by RafyAmgadBenjamin** [comment]
Fixed #217 and #221 
PR:
https://github.com/threefoldtech/jumpscaleX_core/pull/244
https://github.com/threefoldtech/jumpscaleX_threebot/pull/256
