### ISSUE TITLE
Threebot server: add_package parameter in local_start_default useless

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#211]
add_package parameter in j.servers.threebot.local_start_default method doesn't have usecase and can't find docs for it, and can't find it inside the method in code
https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/threebot/ThreeBotServersFactory.py#L45
```
local_start_default(self, web=True, packages_add=False, timeout=120) 
 
kosmos -p 'j.servers.threebot.local_start_default()' 
 
tbot_client = j.servers.threebot.local_start_default() 
 
will check if there is already one running, will create client to localhost & return 
gedis client 
:param timeout: you can increase the timeout to make sure you server runs on slow machines 
:return:       ```

**Comment by xmonader** [comment]
package_add param was used in threebot-test command https://github.com/threefoldtech/jumpscaleX_threebot/issues/235
