### ISSUE TITLE
Testing gedis client

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscaleX_core#212]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/383), We need to test the gedis client.

**Deliverables**
- Update all test cases in TestQuality linked to the testing sheet
- Update all the automation test cases 
- Integrated with ZeroCI

**Estimation Time**
- 2H

**Comment by 0xIslamTaha** [comment]
I can see that this [code](https://github.com/threefoldtech/jumpscaleX_libs/blob/client_testing/JumpscaleLibs/clients/test/test_gedis_cleint.py) is nothing more than what we already have [here](https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/tests/test_gedis.py#L68), so it is a must to update the original code if it is already doing what we are looking for.

**Comment by Dina-Abd-Elrahman** [comment]
- gedis client test case added [here](https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/servers/tests/test_gedis.py#L68)

https://github.com/threefoldtech/jumpscaleX_core/commit/2b6031f58a46667224367eba1ca39843bce7beac
