### ISSUE TITLE
Need to be able to enter filtering info when registering using a registry client

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#217]
**While registering i need to be able to enter filtering fields like:**
schema_url
country_code
format 
category
topic
description

**Comment by RafyAmgadBenjamin** [comment]
PR:
https://github.com/threefoldtech/jumpscaleX_core/pull/244
https://github.com/threefoldtech/jumpscaleX_threebot/pull/256

**Comment by despiegk** [comment]
lets just close and make sure is in all to [development_actorsimprovement]

**Comment by hossnys** [comment]
verified

![Screenshot from 2019-11-27 16-39-13](https://user-images.githubusercontent.com/26298009/69732540-7957f300-1134-11ea-842f-e16031aaa6aa.png)

but here as shown on screenshot the doc-string is not updated with all parameters and @RafyAmgadBenjamin  will update it.

![Screenshot from 2019-11-27 16-44-58](https://user-images.githubusercontent.com/26298009/69732957-3fd3b780-1135-11ea-9503-c1c8fa763d8b.png)
