### ISSUE TITLE
name** value should always be present if defined in schema and not allow empty values in object creation.

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#225]
if name** attribute is defined in the schema it should always be present 
- `find_by_name` 
- treating empty value as special case and "preventing" later objects with empty name doesn't make much sense.

**Comment by gmachtel** [comment]
Still issue ? If so, I guess 10.3 is in time to deliver ?

**Comment by xmonader** [comment]
should be enforced already (critical to have).

**Comment by xmonader** [comment]
duplicate of https://github.com/threefoldtech/jumpscaleX_core/issues/171
