### ISSUE TITLE
kosmos shell: auto completion is broken when trying to assign to a variable

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#226]
This is pretty annoying bug that break the UX of the kosmos shell. 
Automcompletion work mostly ok when you just try to autocomplete  a line that start with the `j`
But as soon as you try to autocomplete a line that start with a variable name, autocompletion is broken, stuff get written on the line and you endup completely lost.

Example how to reproduce, in kosmos do:
`bcdb = j.data.bcdb.[TAB]`
When pressing tab you will see how things are boken.

**Comment by abom** [comment]
I think this is the same as https://github.com/threefoldtech/jumpscaleX_core/issues/169.

**Comment by zaibon** [comment]
seems to be fixed indeed  !! Thanks @abom :+1:
