### ISSUE TITLE
Threebot server start takes too much time to start

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#230]
First time you install and start threebot server, it sometimes takes over 10 mins. 
Since we have an image, why not add all the dependencies there?

**Comment by zaibon** [comment]
yeah for the 3bot deployment this is a must. We would like to be able to deploy 3bot as fast as possible. So having a out of the box ready image is something I would love.

I propose that with the next release planned for tonight, we also create a full image that we can use in the 3bot deployement flow.

**Comment by serboctor** [comment]
Added a production image that contains threebot in the `threebotbuilder`  `jsx` command. And changed the deployer to use it.

**Comment by serboctor** [comment]
https://github.com/threefoldtech/jumpscaleX_core/blob/bbe9b02c91e3b56940ae838b20fd2f0c78300f94/docs/Installation/jsx.md#threebotbuilder
