### ISSUE TITLE
Testing  authentication flow on actor level

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscaleX_core#238]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/394), We need to design and automate test cases for the ThreeBot authentication (Actor security).

**Deliverables**
- Design test cases in TestQuality linked to the testing sheet
- Automate the test case 
- Integrated with ZeroCI

**Estimation Time**
- Do the exploratory testing and set the estimation time..

**Comment by john-kheir** [comment]
Development task: https://github.com/threefoldtech/home/issues/382

**Comment by john-kheir** [comment]
blocked till this ticket is done: Development task: https://github.com/threefoldtech/home/issues/382

**Comment by despiegk** [comment]
security needs to be revisted, close this one
