### ISSUE TITLE
Test CRUD actors

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscaleX_core#239]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/394), We need to design and automate test cases for the CRUD actors

**Deliverables**
- Design test cases in TestQuality linked to the testing sheet
- Automate the test case 
- Integrated with ZeroCI

**Estimation Time**
- Do the exploratory testing and set the estimation time..

**Comment by 0xIslamTaha** [comment]
original issue
https://github.com/threefoldtech/home/issues/381

**Comment by rkhamis** [comment]
CRUD actors is removed, so this is obsolete
