### ISSUE TITLE
Test the sonic client

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscaleX_core#241]
**Description**
As a part of [This thread](https://github.com/threefoldtech/home/issues/394), We need to design and automate test cases for the sonic client.

**Deliverables**
- Design test cases in TestQuality linked to the testing sheet
- Automate the test case 
- Integrated with ZeroCI

**Estimation Time**
- Do the exploratory testing and set the estimation time..

**Comment by Dina-Abd-Elrahman** [comment]
- Estimation time :

12 Hours.

**Comment by Dina-Abd-Elrahman** [comment]
-sonic bug:
https://github.com/threefoldtech/jumpscaleX_core/issues/250

**Comment by Dina-Abd-Elrahman** [comment]
### Test cases :

https://github.com/threefoldtech/jumpscaleX_core/blob/client_testing/JumpscaleCore/clients/tests/test_sonic_client.py

### Related issues : 

https://github.com/threefoldtech/jumpscaleX_core/issues/269
https://github.com/threefoldtech/jumpscaleX_core/issues/270
https://github.com/threefoldtech/jumpscaleX_core/issues/271
https://github.com/threefoldtech/jumpscaleX_core/issues/272

### Test quality : 

https://jsx.testquality.com/project/7543/plan/13826/test/209561

**Comment by Dina-Abd-Elrahman** [comment]
- the code is merged, we can close this issue now.
