### ISSUE TITLE
Gedis client bug

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#242]
start threebot server, it starts gedis by default on port 8901

```
client = j.servers.threebot.local_start_default(web=True)
```

it returns the client `threebot`. Do a ping, it pings fine.
```
JSX> client.ping()                                                                                                                                                                                          
True
```
get the same client again but give it the wrong port 
```
client = j.clients.gedis.get("threebot", port=8900)
```

the client is returned without crashing, even though nothing is running on 8900
and when you try to ping, it pings just fine.
It's actually still pinging using the old port 8901.

if you check `client._redis` you'll see it's using port 8901

On top of this bug, if you have a gedis client pointing to a port where nothing is running, if you try to do a `get` it will fail, because the `init` of the object calls the reload which uses redis and the connection will fail. So even if you pass new ports, it will still fail because the object is loaded first then updated. If you try to delete it, it will also fail, because the delete does a get.

**Comment by serboctor** [comment]
Added a small fix to reset redis when the instance is saved https://github.com/threefoldtech/jumpscaleX_core/commit/ce763592013ec9076d22707e2bfeb7821259100b however, if someone changes the port property on the object `cl.port = newvalue` and doesn't save, redis instance wont be reset.

**Comment by abom** [comment]
> however, if someone changes the port property on the object cl.port = newvalue and doesn't save, redis instance wont be reset.

I think in this case, `_update_trigger` of base class can be used, see for [zos client](https://github.com/threefoldtech/jumpscaleX_libs/blob/3ebeb9749da8cae4a97b1645d5581d34d595e5ca/JumpscaleLibs/clients/zero_os/ZeroOSClient.py#L34-L44) as en example.

**Comment by serboctor** [comment]
Added triggers to handle both property change and save https://github.com/threefoldtech/jumpscaleX_core/commit/247286cd7e661f3c403b7ce26b5f08ba156aaa99

**Comment by despiegk** [comment]
great elegant fix, well done
