### ISSUE TITLE
baseclasses fail for configs

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#245]
[development_fixes]
```
kosmos -p 'j.tutorials.baseclasses.configobjects.test()'
kosmos -p 'j.tutorials.baseclasses.world.test()'
```

- [x] test world.test fails

**Comment by ranatrk** [comment]
**(STILL WIP)** Issue with world.test(): in the test of using a generic usable factory
![Screenshot from 2019-12-11 17-56-10](https://user-images.githubusercontent.com/17128393/70641300-198a3d80-1c46-11ea-8f43-dd3848f2f1c8.png)

The World class has 3 children (Ship, Ships, and Cars). Ships and Cars can be accessed using `w.ships` and `w.cars`, but the object_config class Ship cannot be accessed using `w.ship`. This arises after the call of `w._children_recursive_get()` where a recursive call to create instances is done on all children of World and their children.

**Comment by ranatrk** [comment]
When World() is created, an instance of its children are created as well. The Ship instance created is without a name, once it is assigned a name it can be accessed. Looking into baseclass to trace where the issue arises exactly for that.

**Comment by ranatrk** [comment]
@despiegk In world.test(), should World() have childclasses of both object_config_collection(Ships,Cars) and object_config(Ship)? Accessing the children of world arises for the Ship. 
Can you provide more details regarding the logic of this test case please? https://github.com/threefoldtech/jumpscaleX_libs/blob/development/tutorials/base/object_structure/BaseClasses_Object_Structure.py#L116

**Comment by ranatrk** [comment]
Fix: https://github.com/threefoldtech/jumpscaleX_libs/commit/be2115d0180e2c5d154c65a288ff5dc54e556de2
- Changed test to how base classes behave where an empty instance of object_config shouldn't exist where name would be empty. The test now tests scenario where Ships and Cars are children to World and they have their own children and can be accessed
WIP:
- World3 scenario: Contains schematext and childclasses. Issue arises when accessing the childclass Cars using `w2.cars` where the mother_id is not set. Still looking into it.

**Comment by ranatrk** [comment]
The issue with World3 scenario is because the Children Cars and Ships were created before in the test scenario itself alone. They were added without a mother_id because of the 1st scenario.So when they are to be used in the World3 scenario, a new item isn't created that contains the mother_id but the old one is retrieved.
When scenario of World 3 is tested alone without the conflicting scenario run before it, it passed. 
**WIP**  Looking into the mother_id issue mentioned in the test and base classes

**Comment by ranatrk** [comment]
Seperated the two tests for World to avoid the previously mentioned conflicts.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
