### ISSUE TITLE
ZDB client bugs 

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#247]
Similar to https://github.com/threefoldtech/jumpscaleX_core/issues/242

start zdb on the default port 9901, and get the admin client and do a ping. Everything works fine.
Stop zdb, change the port and save. Then try to start zdb, it will fail to start at the port where it gets the client admin, because it uses the old port. 
```
SX> j.servers.zdb.default.start()                                                                                                                                                                          
JSX> client = j.servers.zdb.default.client_admin_get()                                                                          
JSX> client.redis                                                                                                                                                                                           
Redis<ConnectionPool<Connection<host=127.0.0.1,port=9901,db=0>>>
JSX> client.ping()                                                                                                                                                                                          
True
JSX> j.servers.zdb.default.stop()                                                                                                                                                                           
JSX> j.servers.zdb.default.port                                                                                                                                                                             
9901

JSX> j.servers.zdb.default.port = 9900                                                                                                                                                                      
JSX> j.servers.zdb.default.save()                                                                                                                                                                           
JSX> j.servers.zdb.default.start()                                                                                                                                                                          
Sun 17 16:42:04 /redis/connection.py - 543 - connect                            : EXCEPTION: 
    ConnectionError('Error 111 connecting to 127.0.0.1:9901. Connection refused.',)
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/zdb/ZDBServer.py in start
    53    self.client_admin_get()  # should also do a test, so we know if we can't connect
/sandbox/lib/jumpscale/Jumpscale/servers/zdb/ZDBServer.py in client_admin_get
    90    cl = j.clients.zdb.client_admin_get(addr=self.addr, port=self.port, secret=self.adminsecret_, mode=self.mode)
/sandbox/lib/jumpscale/Jumpscale/clients/stor_zdb/ZDBClientFactory.py in client_admin_get
    63    cl.auth()
/sandbox/lib/jumpscale/Jumpscale/clients/stor_zdb/ZDBAdminClientBase.py in auth
    10    self.redis.execute_command("AUTH", self.secret_)
/usr/local/lib/python3.6/dist-packages/redis/client.py in execute_command
    836    conn = self.connection or pool.get_connection(command_name, **options)
/usr/local/lib/python3.6/dist-packages/redis/connection.py in get_connection
    1081    connection.connect()
/usr/local/lib/python3.6/dist-packages/redis/connection.py in connect
    543    raise ConnectionError(self._error_message(e))
-----------------------------

Error 111 connecting to 127.0.0.1:9901. Connection refused.
```
 Another bug: if the client port is updated at any point, the redis instance still point to the old port even though the instance itself has the right port.
```
JSX> j.servers.zdb.default.start() 
JSX> j.servers.zdb.default.port
9900
JSX> j.clients.zdb.admin.ping()
True
JSX> j.clients.zdb.admin.redis
Redis<ConnectionPool<Connection<host=127.0.0.1,port=9900,db=0>>>
JSX> j.clients.zdb.get("admin", port=9901).save()
JSX> j.clients.zdb.admin.redis
Redis<ConnectionPool<Connection<host=127.0.0.1,port=9900,db=0>>>
JSX> j.clients.zdb.admin
# JSXOBJ:
## .zdb.client.1
ID: 91
 - name                : admin
 - addr                : 127.0.0.1
 - port                : 9,901
 - secret_             : 123456
 - nsname              : default
 - admin               : True
 - mode                : SEQ
```
- On top of that, because in the `init` of the zdb client, redis tests the connection and in case of the admin sends an auth, so even if you do a `get` with right port, it will fail, because the object is first retrieved from bcdb with the old values, then tries to update it, so while getting it, it will fail in the init. 

- Also, if you try to delete the instance, it will also crash, because the delete does a get first. 

A proposed solution:
- Here https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/clients/stor_zdb/ZDBClientFactory.py#L60 we need to pass all the other arguments too, in case the server values changed. And make sure to check all places where this function is used, and make sure to pass all arguments, otherwise we'll end up with defaults from the function signature. But even with this change, like I mentioned above, the get will still fail with the old values during the init.
- Make redis a property, like in the gedis client, that uses a variable. Reset the variable when the object is saved. This, however, won't fix all the problems because, we will still have the issues mentioned above related to connecting using redis in the init.

**Comment by serboctor** [comment]
Fix for the second proposed solution https://github.com/threefoldtech/jumpscaleX_core/commit/16c88a2c3112c6e5cdc47dc4ed9549f9bbc18a25 however if someone changes the port property on the object cl.port = newvalue and doesn't save, redis instance wont be reset.

**Comment by despiegk** [comment]
this can wait, we need to work with static 3bot config, ZDB does not need to have changing ports

**Comment by serboctor** [comment]
we're not trying to support different configs, but this bug which is also present in gedis client, caused issues in 3bot deployments on the cockpit/explorer and deployments failed because of it. But sure, it can wait. Now that we are aware of it, we know how to avoid it.

**Comment by serboctor** [comment]
Added triggers to handle both property change and save https://github.com/threefoldtech/jumpscaleX_core/commit/247286cd7e661f3c403b7ce26b5f08ba156aaa99

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
