### ISSUE TITLE
inconsistent behavior for sonic client

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#250]
- sonic client doesn't work correctly every time, sometimes it gives correct output and another time it just return an empty list or zero, inconsistent behavior. 

###### Verification Steps:

```
j.builders.apps.sonic.install()
j.servers.sonic.default.start()
client = j.clients.sonic.get("test", host="127.0.0.1", port=1491, password="123456")

data = { 
         'post:1': "this is some test text hello", 
         'post:2': 'this is a hello world post', 
         'post:3': "hello how is it going?", 
         'post:4': "for the love of god?", 
         'post:5': "for the love lorde?", 
     } 

for articleid, content in data.items(): 
         client.push("forum", "posts", articleid, content) 

```

if i tried query , or suggest or any method, sometimes it return wrong output.

```client.query("forum", "posts", "love")                                                                                                                                                                 
[]
```

**Comment by despiegk** [comment]
can this be reproduced

**Comment by Dina-Abd-Elrahman** [comment]
### case 1 :

![ff](https://user-images.githubusercontent.com/21218053/69134852-d3b3dc80-0ac0-11ea-874c-11b1688c7df8.png)

however it's working correctly if I search for `love` word instead of `hello` 

![error](https://user-images.githubusercontent.com/21218053/69135054-25f4fd80-0ac1-11ea-9ff7-70df55d1357e.png)

**Comment by Dina-Abd-Elrahman** [comment]
### Case 2 :

##### count method : 

after I pushed the data, and use count method the output shouldn't be 0. 

![error](https://user-images.githubusercontent.com/21218053/69135755-4bced200-0ac2-11ea-8faa-b9769c7bc321.png)

**Comment by RafyAmgadBenjamin** [comment]
For case 1:
```hello ``` is a stopping word for sonic so it wouldn't index or search for it.
***here is a list of stopping words for sonic***
https://github.com/valeriansaliou/sonic/blob/master/src/stopwords/eng.rs

For case 2:
***I am getting the right count***
![image](https://user-images.githubusercontent.com/46320202/69242676-05ed3900-0baa-11ea-9dbc-4e8254a7643e.png)

**Comment by Dina-Abd-Elrahman** [comment]
@RafyAmgadBenjamin 6 it's the correct value, it's len(date)+1, and there is separate issue for it ( https://github.com/threefoldtech/jumpscaleX_core/issues/271 )
and it works yes sometimes with me, but not all times, so it's inconsistent, it works once and another one doesn't work.

and for case 1: even i tried `love` for example it doesn't work correctly with me everytime.

**Comment by Dina-Abd-Elrahman** [comment]
- this issue happened again, and it takes approximately `6 mins` to push only small amount of data i think this time is very very big, so can we investigate why this happen.

**Comment by xmonader** [comment]
lots of changes happened till now I'll move to verification, if anything but count doesn't work please tell me.

**Comment by Dina-Abd-Elrahman** [comment]
this  issue happened again, and it takes approximately 2 mins to push only 3 items of data i think this time is very very big, so can we investigate why this happen.
