### ISSUE TITLE
generated CRUD actors for the models in packages with ACL

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#258]
- generate actors per model, if exists don't
- does CRUD
- check the ACLS in the generated code: user/circle vs the ACL in the object

## info

- circles are always defined on the 3bot itself
    - circles can have sub circles
- when user logs in then we have the session, so we know who user is, we should know which circles he is in (local circles)
- global circles are:   $circlename.$digitalmeDoubleName
- ThreeBot circle manager needs to have a function: is member off (but don't show members)

**Comment by xmonader** [comment]
@andrewayoub you is revisiting to make sure it's aligned with https://github.com/threefoldtech/home/issues/399

**Comment by andrewayoub** [comment]
bending on https://github.com/threefoldtech/jumpscaleX_core/issues/256

**Comment by xmonader** [comment]
crud actors are implemented and correctly generated, awaiting ACLs.

**Comment by despiegk** [comment]
will create new FR
