### ISSUE TITLE
release Jumpscale 10.1

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#268]
- [x] make sure there are no branches left which are not on stories in home
- [x] make sure all branches for 10.1 are merged into development
- [ ] run the autotests we have on development
- [x] use jsx threebotbuilder ... to see if it works (builds)
- [x] stories which cannot be finished in 10.1 should be discussed with stakeholders & moved to 10.2
- [ ] once tests done -> development -> master so we are ready for new development branch for 10.2
- [ ] once all of this done then close the 10.1 project because only then its released

**Comment by rkhamis** [comment]
10.1 already released
