### ISSUE TITLE
why count method in sonic client return the len of data +1 ?

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#271]
when we use count method in sonic client it returns the len(data) +1 !!

**Comment by Dina-Abd-Elrahman** [comment]
![error](https://user-images.githubusercontent.com/21218053/69153949-c6f6af00-0ae7-11ea-8a18-fc49ed8a9270.png)

**Comment by xmonader** [comment]
apparently sonic bug https://github.com/valeriansaliou/sonic/issues/188#issuecomment-557918679 nothing to do on our side.
