### ISSUE TITLE
Test git client

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#274]
As a part of [This thread](https://github.com/threefoldtech/home/issues/394), Write scenarios and  automated test cases for git client.

**Deliverables**
- Write test cases in TestQuality and link them to the testing sheet.
- Automate the test cases. 
- Integrate your work with ZeroCI.

**Estimation Time**
- Do the exploratory testing and set the estimation time.

**Comment by Dina-Abd-Elrahman** [comment]
**Estimation Time**
8 Hours.

**Comment by Dina-Abd-Elrahman** [comment]
### Related issues:

https://github.com/threefoldtech/jumpscaleX_core/issues/278
https://github.com/threefoldtech/jumpscaleX_core/issues/279

### Test Quality:
https://jsx.testquality.com/project/7543/plan/13826/test/206488

**Comment by Dina-Abd-Elrahman** [comment]
- Done with test cases, test quality.

**Comment by Dina-Abd-Elrahman** [comment]
- The latest git client testcases.
https://github.com/threefoldtech/jumpscaleX_core/blob/development_actorsimprovement/JumpscaleCore/clients/tests/test_git_client.py
