### ISSUE TITLE
need to change addRemoveFiles method name in git client

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#278]
- addRemoveFiles method just  add all untracked files, so why we don't name it `adduntrackedfiles` or `addallfiles` but this name doesn't make sense. 

https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/clients/git/GitClient.py#L267

**Comment by rkhamis** [comment]
It should add new files and remove deleted ones.

Is this not the current behavior?

please confirm, @Dina-Abd-Elrahman

**Comment by Dina-Abd-Elrahman** [comment]
@rkhamis yes, this is the current behavior.
