### ISSUE TITLE
why we use describe and getBranchOrTag methods in git client, and they are exactly the same ?

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#279]
why we use `describe` and `getBranchOrTag` methods and they are the same ?

https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/clients/git/GitClient.py#L462

https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/clients/git/GitClient.py#L128

**Comment by rkhamis** [comment]
https://git-scm.com/docs/git-describe#_description
