### ISSUE TITLE
protected behaviour of data obj no longer working [development_actorsimprovement]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#281]
![image](https://user-images.githubusercontent.com/6021844/69324802-697a7380-0c49-11ea-9e5a-9fb46e22d129.png)

when inserting data in prop which does not exist it should give error
does not work 
(used to be like this)

**Comment by zaibon** [comment]
yeah indeed I noticed that yesterday too, and I'm also quite sure there is no type checking either. You can perfectly put a string into a field that is define with `(I)`

**Comment by serboctor** [comment]
@zaibon you saw it on development_bcdbautoupdate too? or on development?

**Comment by despiegk** [comment]
we can close also the branch 
all to [development_actorsimprovement]

**Comment by serboctor** [comment]
> we can close also the branch
all to [development_actorsimprovement]

done

**Comment by xmonader** [comment]
@despiegk will reopen this not done yet

**Comment by serboctor** [comment]
As per @despiegk's comment here, I closed and deleted the branch and I added the Attr class to the classes JSXObject inherits from, but havent been able to successfully get an object, it goes into an infinite loop scenarip that I've explained to @xmonader

**Comment by abom** [comment]
I did the same as @serboctor, and removed the reference of `_key` property inside `__getattribute__`, but got another error:


```
Mon 25 14:17:42 /BASECLASSES/Attr.py -  68 - __getattr__                        : EXCEPTION: 
    could not find attribute: _deserialized_items (error was:_deserialized_items)
--TRACEBACK------------------
bcdb_test.py in <module>
    21    model_obj.save()
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py in save
    148    if self._changed:
/sandbox/var/codegen/schema_jumpscale_bcdb_test_house.py in _changed
    242    if "name" in self._deserialized_items:
/sandbox/lib/jumpscale/Jumpscale/core/BASECLASSES/Attr.py in __getattr__
    68    raise j.exceptions.NotFound(msg)
-----------------------------
```


Using this test script and running it using `kosmos -p bcdb_test.py`:

```python
# bcdb_test.py
from Jumpscale import j

bcdb = j.data.bcdb.system

schema_1 = """
@url = jumpscale.bcdb.test.house
name** = "" (S)
active** = "" (B)
enum = "a,b,c" (E)
cost** =  (N)

@url = jumpscale.bcdb.test.room1
name** = "" (S)
"""

model = bcdb.model_get(schema=schema_1)
schema_md5 = model.schema._md5

model_obj = model.new()
model_obj.cost = "10 USD"
model_obj.not_cost = "0 USD"
model_obj.save()
```

Exact changes as a patch:

```
diff --git a/JumpscaleCore/core/BASECLASSES/Attr.py b/JumpscaleCore/core/BASECLASSES/Attr.py
index 869e68e..17f702b 100644
--- a/JumpscaleCore/core/BASECLASSES/Attr.py
+++ b/JumpscaleCore/core/BASECLASSES/Attr.py
@@ -63,8 +63,8 @@ class Attr:
         try:
             r = self.__getattribute__(name)
         except AttributeError as e:
-            whereami = self._key
-            msg = "could not find attribute:%s in %s (error was:%s)" % (name, whereami, e)
+            # whereami = self._key
+            msg = "could not find attribute: %s (error was:%s)" % (name, e)
             raise j.exceptions.NotFound(msg)
 
         return r
diff --git a/JumpscaleCore/data/schema/JSXObject.py b/JumpscaleCore/data/schema/JSXObject.py
index 8560429..d9fb8c0 100644
--- a/JumpscaleCore/data/schema/JSXObject.py
+++ b/JumpscaleCore/data/schema/JSXObject.py
@@ -21,7 +21,7 @@
 from Jumpscale import j
 
 
-class JSXObject(j.baseclasses.object):
+class JSXObject(j.baseclasses.object, j.baseclasses.attr):
     def _init_pre(self, capnpdata=None, datadict={}, schema=None, model=None):
         self._capnp_obj_ = None
         self.id = None
@@ -58,9 +58,9 @@ class JSXObject(j.baseclasses.object):
 
     @property
     def _key(self):
-        if hasattr(self, "id") and self.id:
+        try:
             return "%s:%s" % (self._schema.url, self.id)
-        else:
+        except j.exceptions.NotFound:
             return self._schema.url
 
     @property
```

It seems like the order of `init_*` functions need to be revisited or refactored.

**Comment by abom** [comment]
I found out that instance variables resides in `__dict__` (was set by our custom `__setattr__`), but `__getattr__` raises `AttributeError`, it turns out that we use `__getattribute__` inside, which would raise such error in this case, this is the normal behavior:

https://github.com/threefoldtech/jumpscaleX_core/blob/f8db1b20893edf203371da02be06525d7d7331c5/JumpscaleCore/core/BASECLASSES/Attr.py#L62-L67


See https://docs.python.org/3/reference/datamodel.html#object.__getattr__.

I tried to fix this by using `__dict__[name]` instead, will do some tests and push the code to another branch or so.

**Comment by abom** [comment]
Another note, we handle sub-classes related attribute access inside `Attr` class. Super class should not know any details about sub-class implementation. 

https://github.com/threefoldtech/jumpscaleX_core/blob/f8db1b20893edf203371da02be06525d7d7331c5/JumpscaleCore/core/BASECLASSES/Attr.py#L39-L60

Every sub-class should handle it's own attribute access if it's different, and also it should re-use `Attr` implementation, this way will help in writing proper tests for every base class of e.g. `j.baseclasses.object_config_base`, `j.baseclasses.object_config_base` or `j.baseclasses.object_config_collection`.

**Comment by abom** [comment]
After more testing and investigation, the changes [mentioned earlier](https://github.com/threefoldtech/jumpscaleX_core/issues/281#issuecomment-558258465) broke config objects.

A full patch of the changes is [here](https://gist.github.com/abom/1f4d2eebcef2bfb44397219adc8d7b9c).

After some investigation, the problem is that when getting a new client like:

`cl = j.clients.etcd.new("test1")`

It will always return this client with an empty name, and till now, i could not figure out the root cause.

**Comment by despiegk** [comment]
checking now, have 30 min

**Comment by despiegk** [comment]
- in jsbase you cannot use ATTR
- JSXOBJECT can use ATTR & JSBASE
- JSCONFIG can use ATTR & JSBASE

**Comment by despiegk** [comment]
kristof will check
