### ISSUE TITLE
jsx generate error in multi-level generation

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#287]
Problem: In multi-level generation, jsx generate doesn't append new objects to the the group if it exitsts. It overwrites it.

Example:
when `j.tutorials.worldtest.scheduling` is available 
`j.tutorials.baseclasses.base` gives 

```python
    return eval(code, globals_, locals_) 
  File "<kosmos>", line 1, in <module> 
AttributeError: 'group_j__tutorials' object has no attribute 'baseclasses'
```
and vice versa

**Comment by gmachtel** [comment]
To be checked whether ok now, was part of the actor scheduler. If OK, to close.
