### ISSUE TITLE
Testing both redis and redis config clients

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#288]
Write scenarios and  automated test cases for redis and redis config clients.

**Deliverables**
- Write test cases in TestQuality and link them to the testing sheet.
- Automate the test cases. 
- Integrate your work with ZeroCI.

**Estimation Time**
- Once you explore the clients, please set the estimation time and update the ticket

**Comment by AhmedHanafy725** [comment]
I was working on this ticket yesterday and it will take about more 2 hours.
- For redis client, it has just core client which is too dependent for the system and if it is stopped, it will break all following tests, so it won't be tested.

- For redis config client, `ardb_patch` it takes time to build ardb, also it is not used, so it won't be covered in tests.

**Comment by AhmedHanafy725** [comment]
There was a bug when integrating the tests together specifically getting redis client with password as the returned redis client can be cached which means that the cached redis client don't ask for password.

#### Solution:
Clear the cache of redis client after every test. (thanks @andrewayoub)

**Comment by AhmedHanafy725** [comment]
- Tests is added [here](https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/clients/tests/test_redis_config.py) and merged on `development` branch.
- TestQuality: [link](https://jsx.testquality.com/project/7543/plan/13826/test/211372)
- Testing sheet: [link](https://docs.google.com/spreadsheets/d/1-VjAoOtl4rasbbTdu1KK_th-lvWeAU_lpRqC0KhoPAs/edit#gid=916159529&range=A178)
- Tests are running on zeroCI
