### ISSUE TITLE
Check SALs

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#29]
Check all sals for jsx; **branch**: development
- [x] bcdbfs 
- [x] bind
- [x] btrfs
- [x] ~~coredns (deprecated)~~ 
- [x] disklayout
- [x] dnsmasq
- [x] docker
- [x] flist
- [x] fs
    - [x] https://github.com/threefoldtech/jumpscaleX_core/issues/33
    - [x] https://github.com/threefoldtech/jumpscaleX_core/issues/34
    - [x] https://github.com/threefoldtech/jumpscaleX_core/issues/36
    - [x] https://github.com/threefoldtech/jumpscaleX_core/issues/37
    - [x] https://github.com/threefoldtech/jumpscaleX_core/issues/38
    - [x] https://github.com/threefoldtech/jumpscaleX_core/issues/39
    - [x] fswalker
- [x] hostsfile
- [x] kvm
- [x] netconfig
- [x] nettools
- [x] nfs
- [x] nginx
- [x] nic
- [x] openvswitch
- [x] process
- [x] qemu_img
- [x] rsync (Will be refactored as part of https://github.com/threefoldtech/jumpscaleX_core/issues/35)
- [x] ~~samba (deprecated)~~
- [x] sshd
- [x] ssl
- [x] tls
- [x] ubuntu (also https://github.com/threefoldtech/jumpscaleX_libs/issues/1)
- [x] ufw
- [x] unix
- [x] windows

**Comment by waleedhammam** [comment]
Fix import in `bind`: https://github.com/threefoldtech/jumpscaleX_libs/commit/b6849795e71dc55f0b9008b981354828de6f24c7

**Comment by waleedhammam** [comment]
Fix imports and migrate prefab stuff in `btrfs`: https://github.com/threefoldtech/jumpscaleX_libs/commit/9852586ade78258bace27c61c0056f33bdbddfe4

**Comment by waleedhammam** [comment]
Move docker from tools to sal: https://github.com/threefoldtech/jumpscaleX_libs/commit/f591cbf104922e51635a4b3827d423cd7e2fc80f

**Comment by waleedhammam** [comment]
working on FS sal

**Comment by waleedhammam** [comment]
Fix imports in KVM sal: https://github.com/threefoldtech/jumpscaleX_libs/commit/0e261c4766762ae845785fd8468ca28ed4fd253c

**Comment by serboctor** [comment]
https://github.com/threefoldtech/jumpscaleX_libs/commit/8e14d169796d34746949379cc7827c6b0a57be30
https://github.com/threefoldtech/jumpscaleX_libs/commit/aee459050cb7c599b3f33bf321412a2a26e495cb
https://github.com/threefoldtech/jumpscaleX_libs/commit/7fa6a39e6435acf45d95236cb20f11197c56c830
https://github.com/threefoldtech/jumpscaleX_libs/commit/57b91b1cacc3eb309ebbb0abbf9e7f93078093e1
https://github.com/threefoldtech/jumpscaleX_libs/commit/ed4bdc7a05dcc9644d821b71bc33be1a6358c59a
https://github.com/threefoldtech/jumpscaleX_libs/commit/7247694ae145d41a3a051cf1eb3b6f1e3cc34bad
https://github.com/threefoldtech/jumpscaleX_core/commit/d146fc8f1454af815a9308fc46060a7827828e1d
https://github.com/threefoldtech/jumpscaleX_core/commit/6deeb2ce8b1a60a3c15ca6dd61ba4f9a320a0ac9

**Comment by waleedhammam** [comment]
fix NFS sal: https://github.com/threefoldtech/jumpscaleX_libs/commit/d857c0f0e5ef11569365abdfef9505e276562186

**Comment by waleedhammam** [comment]
add _init in some sals https://github.com/threefoldtech/jumpscaleX_libs/commit/1cb3d3235adef4a0e3f1dacbc143fbc74f4b7e71

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
