### ISSUE TITLE
Testing ssh agent client

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#292]
Write scenarios and  automated test cases for ssh-agent client.

**Deliverables**
- Write test cases in TestQuality and link them to the testing sheet.
- Automate the test cases. 
- Integrate your work with ZeroCI.

**Estimation Time**
- Once you explore the client, please set the estimation time and update the ticket

**Comment by Dina-Abd-Elrahman** [comment]
**Related issues**
https://github.com/threefoldtech/jumpscaleX_core/issues/312

**Test cases** 
https://github.com/threefoldtech/jumpscaleX_core/blob/development_testing_clients/JumpscaleCore/clients/tests/test_sshagent_client.py

**Test Quality**
https://jsx.testquality.com/project/7543/plan/13826/test/212727
