### ISSUE TITLE
Testing mail client

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#293]
Write scenarios and  automated test cases for mail client.

**Deliverables**
- Write test cases in TestQuality and link them to the testing sheet.
- Automate the test cases. 
- Integrate your work with ZeroCI.

**Estimation Time**
- Once you explore the client, please set the estimation time and update the ticket

**Comment by Dina-Abd-Elrahman** [comment]
- Estimate Time:
10 hours.

**Comment by Dina-Abd-Elrahman** [comment]
- Trying to run SMTP server, then started in mail client manual test, and test scenarios.

**Comment by Dina-Abd-Elrahman** [comment]
- Done with test case and test quality for (Email & sendgrid clients).
