### ISSUE TITLE
Corex: issue related to starting 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#299]
To reproduce:
```
corxcl = j.servers.corex.get(name = "corex", password = "132456" ) 
corxclient = j.clients.corex.get(name = "corex",passwd_ = "123456") 
startup = j.servers.startupcmd.get(name = "corex",corex_client_name = "corex")                                                   
startup.executor = "corex"                                                                          
startup.interpreter = "bash"                            
startup.cmd_start = "kosmos -p 'j.servers.threebot.local_start_default()'" 
startup.start()
```

![image](https://user-images.githubusercontent.com/46320202/69961660-fb6d6080-1514-11ea-8dbc-fac91ff9391f.png)

**Comment by Dinaamagdy** [comment]
change cmd to startup.cmd_start = "kosmos -p 'j.servers.threebot.local_start_explorer()'"  
works successfully without error  but when u give  it 'j.servers.threebot.local_start_default()'" which not exist anymore didn't pass error will close this issue and create another one with this error .
verified on development branch
