### ISSUE TITLE
Corex: issue related to stop

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#300]
When I try to stop a process already running:
* it tells me that it is stoped even if it is still running 
![image](https://user-images.githubusercontent.com/46320202/69962027-d0374100-1515-11ea-826d-c3efd7b1102b.png)

* it also throws an exception

**Comment by maxux** [comment]
I don't see how to reproduce, at least with latest version.

```
curl http://[2a02:2788:54:1096:b8c7:ccff:fe48:1eac]:7681/api/processes
{ "processes": [ { "pid": 9, "command": "\/bin\/bash", "state": "running", "id": 22518496, "status": 0 } ] }

curl http://[2a02:2788:54:1096:b8c7:ccff:fe48:1eac]:7681/api/process/stop?id=22518496
{ "status": "success" }

curl http://[2a02:2788:54:1096:b8c7:ccff:fe48:1eac]:7681/api/process/stop?id=22518496
{ "status": "error", "reason": "process already stopped" }
```

I can confirm process is stopped and not responding anymore.
Starting a new bash, doing `ps aux` show only the running process.

Killing this process using `kill -9` result to:
```
{
  "processes": [
    {
      "pid": 20,
      "command": "/bin/bash",
      "state": "stopped",
      "id": 22515360,
      "signal": 9,
      "status": 0
    },
    {
      "pid": 9,
      "command": "/bin/bash",
      "state": "stopped",
      "id": 22518496,
      "status": 0
    }
  ]
}
```

Which sound good.
