### ISSUE TITLE
allow disabling crud actors generation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#304]
[development_crud_disable]
for packages in tfgrid it's not right to allow crud actors to manipulate data in there without proper permissions or without an option at least to disable the generation

**Comment by xmonader** [comment]
@zaibon @despiegk

**Comment by ranatrk** [comment]
Added disable option for crud actors to disable generation of actors. This option can be used by adding to ` disable_crud = true` in the package's `package.toml` file.
https://github.com/threefoldtech/jumpscaleX_core/commit/52ce2a6a29698dbdf4d5dc2b281f1ea661d8d399

**Comment by despiegk** [comment]
do we have some doc somewhere?

**Comment by despiegk** [comment]
lets close today

**Comment by ranatrk** [comment]
> do we have some doc somewhere?

No, ill add some documentation for how to use it

**Comment by siddiquagig** [comment]
Verified


Steps followed:

-  Find/create a package with models directory, with  a model in a toml file

you can use  this package ```/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/zerobot/webplatform```

- include in the package.toml source section disable_crud=true

- load the package from within the shell 

- When trying to access the actors, there will be no actors generated for the crud models only the normal package actors

- To test the other way around on a clean environment, remove the disable option, and try the steps again but this time the actors will be generated for that package
