### ISSUE TITLE
gedis client fails when packages aren't loaded correctly

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#305]
If u load a broken package, and try to get gedis client it'll fail with this error

![image](https://user-images.githubusercontent.com/64129/70053596-72226080-15de-11ea-8417-8e2d438454fc.png)

**Comment by zaibon** [comment]
to reproduce:
```python
#start 3bot server
j.servers.threebot.local_start_default()
# install directory package
j.threebot.packages.tfgrid.directory.install()
j.threebot.packages.tfgrid.directory.start()
```

Then in another shell, get a gedis client to your 3bot
```python
client = j.clients.gedis.get('3bot',port=8901) # this line should trigger the error reported 
```

**Comment by waleedhammam** [comment]
the problem happens due to the new system of shortening the package's models url's

example:
in registry: in models it's defined like `entry.data.1` and somewhere's called with the full name `tfgrid.registry.entry.data.1` so this needs to be unified.

**Comment by john-kheir** [comment]
Verified but didn't try all packages but main packages should be working

**Comment by waleedhammam** [comment]
Reference commit: https://github.com/threefoldtech/jumpscaleX_core/commit/833817478ce89594d2c91741abc42b561b536bd0
