### ISSUE TITLE
BCDB nested schema save error

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#310]
How to reproduce:

- Create a new schema

```python
scm = """@url=myschema.schema.1 
name**=""(S) 
inner_scm = (O) !myschema.inner 
 
@url=myschema.inner 
name**=""(S) 
somevalue = 0 (I) 
"""  
```

- Get the schema from the string
`schema = j.data.schema.get_from_text(scm)`

- Get the model from this schema
`model = j.data.bcdb.system.model_get(scm)`

- Create a new model
`o = model.new()`

- Set the model's values
```python
o.name = "anyname"
o.inner_scm.name = "innername"
o.inner_scm.somevalue = 8
```

- Then save you will have this error

```
JSX> o.save()                                                                                                                                                                                                      
Thu 05 13:00:48 <string>             -   1 - <module>                           : EXCEPTION: 
    AttributeError("'JSXObject2' object has no attribute 'inner_scm_name'",)
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py in save
    164    self.check_empty_indexed_fields()
/sandbox/lib/jumpscale/Jumpscale/data/schema/JSXObject.py in check_empty_indexed_fields
    149    value = eval(f"self.{prop.name}")
<string> in <module>
    1    
-----------------------------

'JSXObject2' object has no attribute 'inner_scm_name'
```

also when making the a model using the inner schema and adding it to the main model it's the same case.

**Comment by waleedhammam** [comment]
fixed at pr: https://github.com/threefoldtech/jumpscaleX_core/pull/311

This was happening because in saving nested schmaes. inner objects are saved like `mainschema_innervaluename` so the check in bcdb saving won't have access to that property, so we have to replace it with "."

- to make it easy replaced `_` with `__` and in the check will replace  `__` to `.` to verify the property is existed

**Comment by Dina-Abd-Elrahman** [comment]
**Verification steps**

- scm = """@url=myschema.schema.1 
name**=""(S) 
inner_scm = (O) !myschema.inner 
 
@url=myschema.inner 
name**=""(S) 
somevalue = 0 (I) 
"""  

- schema = j.data.schema.get_from_text(scm)
- model = j.data.bcdb.system.model_get(scm)
- o = model.new()
- o.name = "anyname"
- o.inner_scm.name = "innername"
- o.inner_scm.somevalue = 8
- o.save()

```
## .schema.1
ID: 8
 - name                : anyname
    ## .inner
     - name                : innername
     - somevalue           : 8
```
