### ISSUE TITLE
need to pass name, path, and passphrase in key_load method in sshagent client

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#312]
- need to pass name, path, and passphrase in key_load method in sshagent client.

https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/clients/sshagent/SSHAgent.py#L45

**Comment by xmonader** [comment]
keyload definition
```python
    def key_load(self, path=None, name=None, passphrase=None, duration=3600 * 24):
```
all of the params are optional

- key_name_get
if name is passed as none it'll check for SSH_KEY_DEFAULT in MyEnv
```python
    def _key_name_get(self, name):
        if not name:
            if MyEnv.config["SSH_KEY_DEFAULT"]:
                name = MyEnv.config["SSH_KEY_DEFAULT"]
            elif MyEnv.interactive:
                name = Tools.ask_string("give name for your sshkey")
            else:
                name = "default"
        return name
```

**Comment by Dina-Abd-Elrahman** [comment]
when we use key_load() like in the code here  https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/clients/sshagent/SSHAgent.py#L45 we don't pass the path and key_default_name. 
so sshagent client starts the default ssh key (id_rsa) in default ssh path (HOME_DIR/.ssh)
`j.core.myenv.sshagent.key_load(path=PATH, name=NAME)`
in sshagent client we need to start sshkey which we pass in `sshagent.key_default_name` and `sshagent.path` so we need to add it
The problem is in the way sshagent client call key_load method not in key_load method itself.

**Comment by despiegk** [comment]
is it an issue?

**Comment by ranatrk** [comment]
fixes on branch [development_fixes]
sshagent can now call `key_load` and pass the following params 
- `path`
- `name`
- `passphrase`

**Comment by hossnys** [comment]
verified on branch [development_fixes]

![Screenshot from 2019-12-12 12-49-41](https://user-images.githubusercontent.com/26298009/70706388-79342780-1cde-11ea-8f8b-895c47c7aa7c.png)

![Screenshot from 2019-12-12 12-52-53](https://user-images.githubusercontent.com/26298009/70706390-79342780-1cde-11ea-8b5f-4ec60e160a06.png)
