### ISSUE TITLE
remove data consistency issues in myworkers [development_fixes]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#323]
issue is that when you restart e.g. a container jobmodel can be empty if redis BCDB but queue on redis maybe not

## todo

- empty queue in redis when job manager starts
- when starting worker: when bcdb model for jobs == empty, empty the queue first
so 2x to be done

**Comment by waleedhammam** [comment]
Commits: https://github.com/threefoldtech/jumpscaleX_core/commit/79f1e602448f9485a9e5ef6874e3e977b279f9d7, https://github.com/threefoldtech/jumpscaleX_threebot/commit/e69c2ef4d283812d86b98c7455bad6a08c5069d0

- fix reset
- add start myjobs through myjobs_ui actor

todo:

- add myjobs server methods to actor to make all calls from the actor not directly to the server

**Comment by waleedhammam** [comment]
Commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/c08dc26c34c81f037ee762186ebabbfe24799b75

- add myjobs server methods to actor to make all calls from the actor not directly to the server

Example usage:
```python
package = j.tools.threebot_packages.get("zerobot.myjobs_ui")
package.actors.myjobs.start()
```


```python
package = j.tools.threebot_packages.get("zerobot.myjobs_ui")
package.actors.myjobs.stop()
```

or in the threebot server shell
```python
j.threebot.packages.zerobot.myjobs_ui.actors.myjobs.stop()
```

**Comment by siddiquagig** [comment]
I am getting this error when starting threebot server on development_myjobs

![image](https://user-images.githubusercontent.com/25789724/70888550-0d153480-1ffa-11ea-8d63-986af061ea90.png)


My code is latest too

**Comment by xmonader** [comment]
@siddiquagig please check on development_fixes

**Comment by waleedhammam** [comment]
Starting my jobs is through 3bot server not and not using actors.

**Comment by siddiquagig** [comment]
Verified 

Steps:
Start threebot server, make sure the workers are spawned without any problems
