### ISSUE TITLE
[BCDB] write/delete shouldn't return ok until the data processor greenlet is done

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#325]
write/delete shouldn't return ok until the data processor greenlet is done

**Comment by despiegk** [comment]
it could be this is ok already, we need to check behaviour

**Comment by xmonader** [comment]
should be ok now

**Comment by Pishoy** [comment]
Hi, how can i verify this ?

**Comment by xmonader** [comment]
@Pishoy try to write to a model (create couple objects) and then try to delete random one .

**Comment by john-kheir** [comment]
Verified 
1- from a kosmos shell, Wrote multiple random objects, then deleted a random well
2- checked from another shell that the deleted object is not there any more
