### ISSUE TITLE
[GEDIS] client authentication needs to get back [development_gedis_authentication]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#326]
Client authentication for gedis should get restored.

**Comment by serboctor** [comment]
nacl test is now fixed on `development`. 
/home/ser/Pictures/Screenshot from 2019-12-18 19-10-54.png

**Comment by zaibon** [comment]
PRs open at https://github.com/threefoldtech/jumpscaleX_core/pull/583 and https://github.com/threefoldtech/jumpscaleX_threebot/pull/394

Need to do a review of the crypto flow use here there.

**Comment by rkhamis** [comment]
PR changed to: https://github.com/threefoldtech/jumpscaleX_core/pull/597

**Comment by xmonader** [comment]
closed in favor of https://github.com/threefoldtech/home/issues/587
