### ISSUE TITLE
SAL.FS: List files and directories in directory without symbolic links.

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#33]
### steps:
1- Create a directory `test_dir` under `/tmp`.
2- Create a file `test_file` inside `test_dir`.
3- Create a symlink for this file in the same directory `sym`.
4- List files and directories in `test_dir` with `followSymlinks=False`, `listSymlinks=False`.
```
j.sal.fs.listFilesAndDirsInDir("/tmp/test_dir", followSymlinks=False, listSymlinks=False)
```

### Expected Result:
Should return only `test_file`.

### Actual Result:
`['/tmp/test_dir/test_file', '/tmp/test_dir/sym']`

**Comment by AhmedHanafy725** [comment]
#29

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/jumpscaleX_core/commit/778e82d924de366df67ea11430b5aa2fad42ce16

**Comment by hossnys** [comment]
verified on branch development 778e82d
```
JSX> j.sal.fs.listFilesAndDirsInDir("/tmp/test_dir", followSymlinks=False, listSymlinks=False)  
['/tmp/test_dir/test_file']

```
