### ISSUE TITLE
myjobs need support for debug mode

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#334]
- [ ] pudb / j.shell support
    - when pudb of j.shell found in method to execute, launch in tmux worker so we can debug

**Comment by Hamdy** [comment]
Added in this branch
https://github.com/threefoldtech/jumpscaleX_core/tree/development_myjobs_debug_mode

Instructions and limitations here : https://github.com/threefoldtech/jumpscaleX_core/blob/development_myjobs_debug_mode/JumpscaleCore/servers/myjobs/README.md#how-to-debug-a-job--function

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
