### ISSUE TITLE
lazy loading for models and actors [development_fixes]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#337]
- gedis actors (each interface e.g. web/gedis) needs to call lazy loading of package
- ~bottle server needs to call lazy loading of package~ continued in  https://github.com/threefoldtech/jumpscaleX_core/issues/353

this is needed or its too slow

**Comment by andrewayoub** [comment]
Lazy loading for actors and Models already done, still we need to do it for bottle locations

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
