### ISSUE TITLE
Can't start openresty server

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#338]
server = j.servers.openresty.get("test")                                                                                                                                                                      
server.start()               
```Wed 11 09:40:45 tupcmd/StartupCMD.py - 113 - _error_raise                       : EXCEPTION: 
    error in startupcmd :lapis
    could not start
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/Jumpscale/servers/openresty/OpenRestyServer.py in start
    168    self.startup_cmd.start()
/sandbox/lib/jumpscale/Jumpscale/servers/startupcmd/StartupCMD.py in start
    664    running = self.wait_running(die=True)
/sandbox/lib/jumpscale/Jumpscale/servers/startupcmd/StartupCMD.py in wait_running
    511    return self._error_raise("could not start")
/sandbox/lib/jumpscale/Jumpscale/servers/startupcmd/StartupCMD.py in _error_raise
    113    raise j.exceptions.Base(msg)
-----------------------------

None
```

**Comment by waleedhammam** [comment]
Works on development
using: 
`server = j.servers.openresty.get("abc") `
`server.start()`

![Screenshot from 2019-12-12 11-04-22](https://user-images.githubusercontent.com/10658229/70697982-39b20f00-1ccf-11ea-814d-4c1a35b706f1.png)

**Comment by hossnys** [comment]
verified on development :
![Screenshot from 2019-12-12 12-43-39](https://user-images.githubusercontent.com/26298009/70705699-2ad25900-1cdd-11ea-859d-175cce805946.png)
