### ISSUE TITLE
check usage gedis

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#339]
- check usage of j.clients.gedis.get
- check is using it right way package_name = ...

**Comment by Dina-Abd-Elrahman** [comment]
**Verification steps**

- started 3bot server on container 
`kosmos "j.servers.threebot.local_start_default()"`

- Tried to connect with gedis client from another container 
`gedis_client = j.clients.gedis.get("test", host="IP",  port=8901, package_name="zerobot.myjobs_ui")`

![ff](https://user-images.githubusercontent.com/21218053/70717944-059f1400-1cf8-11ea-8fff-c778c4bf3738.png)
