### ISSUE TITLE
SAL.FS: list files and directories in directory (filter)

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#34]
### Steps:
1- Create a directory `test_dir/subdir` under `/tmp`.
```
mkdir -p /tmp/test_dir/subdir
```
2- Create a file `test_file.py` in this path `/tmp/test_dir/subdir`.
3- List files and directories in `/tmp/test_dir` with filter `py` files.
```
j.sal.fs.listFilesAndDirsInDir("/tmp/test_dir",filter="*.py")
```

### Expected Result:
Should return only `test_file.py`.

### Actual Result:
`['/tmp/test_dir/subdir', '/tmp/test_dir/subdir/test_file.py']`

**Comment by AhmedHanafy725** [comment]
#29

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/jumpscaleX_core/commit/fa6e0b9af8eb340907dccc6517d09cd54089590e

**Comment by hossnys** [comment]
verified on development  fa6e0b9 :

```
JSX> j.sal.fs.listFilesAndDirsInDir("/tmp/test_dir",filter="*.py")       
['/tmp/test_dir/subdir/test_file.py']

```
