### ISSUE TITLE
fix bcdb tests [development_fixes]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#340]

**Comment by Hamdy** [comment]
Tests now succeeds except for the `unique_data` test because it exposes this bug
https://github.com/threefoldtech/jumpscaleX_core/issues/171

**Comment by Hamdy** [comment]
Working on stabilizing tests, most of them pass except for test 7 &10
working on them now

**Comment by Dina-Abd-Elrahman** [comment]
- all tests passed except ( 07_redis & 08_keys & 10_export & 11_redis_index_lost & 13_vfs & 14_webdav & 15_sonic & 16_fs & 20_performance ) 

- commit_id: 
jumpscale_threebot (9ce6118df6c1ca7ff0f39dd6e8ea2110368df5d0)
jumpscale_core (5759a03ac574a80b6bdccceafd61f8d12ca1fa90)

**Comment by xmonader** [comment]
@Dina-Abd-Elrahman this commit is 4 days ago while there're commits already 22 hours ago. I'll reput it in verification. Please check with @Hamdy

**Comment by Dina-Abd-Elrahman** [comment]
- all tests are good now except ( 07_redis, 10_export, and 13_vfs )

- Commit_ID:
jumpscale_threebot (9ce6118df6c1ca7ff0f39dd6e8ea2110368df5d0)
jumpscale_core (1070b94df67d42ce5bb7a5a21e23a8fe96122cef)

**Comment by Dina-Abd-Elrahman** [comment]
- it's working fine now on  `development_fixes2`
- Commit_ID: `ec98fb8994578ff236061d43b2c374f357f87ee2`
