### ISSUE TITLE
package actors are not loaded after threebot server restart

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_core#346]
If you started threebot server, added some packages, got a client from a different shell, you will be able to access their actors. If you restarted the server, actors get loaded and status is `installed`, but when you try to get a client from another shell, you cannot access package actors.

I guess it's the lazy loading of actors, it happens at first time, but not when the actor state is `installed`.

**Comment by gmachtel** [comment]
Linked to #337

**Comment by xmonader** [comment]
Doesn't seem to happen anymore on development_fixes branch. I started explorer then tried to start the `local_start_default` and I've access to phonebook actor.

**Comment by john-kheir** [comment]
Can't reproduce
