### ISSUE TITLE
lazily load packages [development_fixes]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#353]
bottle server needs tolazily load packages

**Comment by xmonader** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/blob/711a53e7dcd514445c3fff182ad5fff8f5b40d04/ThreeBotPackages/zerobot/webinterface/bottle/gedis.py#L71

**Comment by john-kheir** [comment]
### Verification Steps
1- Try to access an uninstalled package, it should get loaded
2- Then make sure the package is installed
