### ISSUE TITLE
Can't fix the test.. need more info about the test purpose and why the schema is different? 

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#356]
- When debugging the tests i found it is checking this schema which has three @attributes.. so why is this? and can we get more info about the purpose of this test?

### Issue:
1- Running this test throw this error
kosmos 'j.data.schema.test(name="load_from_dir")' ![instance_problem](https://user-images.githubusercontent.com/15011431/70901528-a5fc7d80-2003-11ea-94ee-7ef6b1e03e30.png)

### test:
https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/data/schema/tests/8_load_from_dir.py

### Schema used by the test:
https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/data/schema/tests/schemas_toml/threefoldtoken_wallet.toml
```
@url = threefoldtoken.wallet
@importance = true
@systemprop = 1
jwt = "" (S)                # JWT Token
addr** = ""                   # Address
ipaddr = (ipaddr)           # IP Address
email = "" (S)              # Email address
username = "" (S)           # User name
```

**Comment by BolaNasr** [comment]
@john-kheir  
it works Good at ```development_fixes``` branch but we need to understand  
what this schema mean ? 
```
@importance = true
@systemprop = 1
```
we will close it for now
