### ISSUE TITLE
update baseclasses config tests

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#357]
continuation of #245 
- [x] these 2 tests should be part of our automated test suite

**Comment by AhmedHanafy725** [comment]
Test is added to the automation testsuite.
commit: https://github.com/threefoldtech/jumpscaleX_libs/commit/89bb793facd75cd3af71aaec28c2a317851be3e5
Result is [here]( https://zeroci.grid.tf/repos/threefoldtech%2FjumpscaleX_libs/development_fixes/5df8a0c3461390825995396a)

**Comment by siddiquagig** [comment]
Verified

All tests  which  were required to be integrated are there

![alltests](https://user-images.githubusercontent.com/25789724/71068133-7bd7c680-218f-11ea-9259-a2a024de2c29.jpg)
