### ISSUE TITLE
SAL.FS: checking symbolic links.

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#36]
### Steps:
1- Create a file `test_file`.
2- Create a symbolic link `sym` for `test_file`.
3- Delete `test_file`.
4- Check that the `sym` is a symbolic link with `check_valid=True`.
```
j.sal.fs.isLink("/tmp/sym", check_valid=True)
```
Note:
[how check_valid works](https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/sal/fs/SystemFS.py#L1120) 

### Expected Result:
If `check_valid=True` and the link is broken, it should remove this link.

### The problem:
The decorator is checking that the link is exists and as the link is broken so it doesn't exists and raise an error.
So how the link will be removed?!!

**Comment by AhmedHanafy725** [comment]
#29

**Comment by waleedhammam** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/1b97e1712baa9025333821875acba0b5aa81984c

**Comment by hossnys** [comment]
verified on branch development 1b97e17 as next steps :


```
3BOTDEVEL:3bot:test_dir: touch test
3BOTDEVEL:3bot:test_dir: ln -s test sym 
3BOTDEVEL:3bot:test_dir: rm test
3BOTDEVEL:3bot:test_dir: ls
sym
```


```
JSX> j.sal.fs.isLink("/tmp/test_dir/sym", check_valid=True) 
False
```
```
3BOTDEVEL:3bot:test_dir: ls

```
sym file is removed as it's link is broken.
