### ISSUE TITLE
Error while installing jsx in system

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#362]
### steps
See [installation docs](https://github.com/threefoldtech/jumpscaleX_core/tree/development/docs/Installation#jumpscalex-installation-instructions)
branch: development
commit: 3e47a26c0501f355f7a9c455ef8f1fb64999d0d0

![image](https://user-images.githubusercontent.com/41957921/71071305-0666f880-2185-11ea-8639-ba07df1db584.png)
For full logs: https://build.grid.tf/report/c62bb424-cf13-4cc8-bb5d-88096bf6c1e7

**Comment by RafyAmgadBenjamin** [comment]
Fixed on ```development_fixes``` branch,
https://github.com/threefoldtech/jumpscaleX_core/commit/4f81998db27bc81029dc4dce88a26d8dc8ff7067

**Comment by AhmedHanafy725** [comment]
**Verified**
branch: development
commit: 37dcc01110f184c5caa32d628721c2cf9003fc7b

Full installation log: https://build.grid.tf/report/55493518-2304-4fbc-ba5b-44344e0b2843
