### ISSUE TITLE
Implement TODOs in ThreebotClient [development_fixes]

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_core#366]
- [x] actors_get(...) 
   return actors for one or all packages
- [x] actors_base(...)

**Comment by ranatrk** [comment]
actors_base : https://github.com/threefoldtech/jumpscaleX_core/commit/55ca4c0540b0706f187298593753d7ff1efb20ba

For verification:
`threebot_client = j.clients.threebot.client_get("default")`
- actors_get():
   1. get actors for specific package : `threebot_client.actors_get("PACKAGE_NAME")`
   2. get all actors for all packages: `threebot_client.actors_get()`
- actors_base():
   1. get actors for base package : `threebot_client.actors_base`

**Comment by john-kheir** [comment]
Verified
