### ISSUE TITLE
Fix BCDB rebuild index command 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#374]
![photo_2019-12-20_10-00-15](https://user-images.githubusercontent.com/6323012/71322379-9c758880-24cf-11ea-9d7a-a1d555e784f8.jpg)

**Comment by xmonader** [comment]
Fixed in https://github.com/threefoldtech/jumpscaleX_core/pull/373

**Comment by john-kheir** [comment]
working
