### ISSUE TITLE
SAL.FS: get md5sum for a directory

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#38]
### Steps:
1- Create a directory `/tmp/test_dir`.
2- Create some files under `/tmp/test_dir`.
2- Get md5sum for this directory `/tmp/test_dir`
```
j.sal.fs.getFolderMD5sum("/tmp/test_dir")
```
### Actual Result:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFSDecorators.py", line 213, in wrapper
    return func(*args, **kwargs)
  File "/sandbox/lib/jumpscale/Jumpscale/sal/fs/SystemFS.py", line 1351, in getFolderMD5sum
    files = sorted(self.walk(folder, recurse=1))
AttributeError: 'SystemFS' object has no attribute 'walk'

'SystemFS' object has no attribute 'walk'
```

**Comment by AhmedHanafy725** [comment]
#29

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/jumpscaleX_core/commit/cf1b4e337a1bd179d8f986133ec12b54e9d238f5

**Comment by zgorizzo69** [comment]
I will cehck and add some test

**Comment by hossnys** [comment]
verified on development : 
```
JSX> j.sal.fs.getFolderMD5sum("/tmp/test_dir")    
'ac9c542684f271e7215c00369bbb793e'
```
```
checksumdir -a md5 test_dir/
ac9c542684f271e7215c00369bbb793e
```

**Comment by zgorizzo69** [comment]
> verified on development :
> 
> ```
> JSX> j.sal.fs.getFolderMD5sum("/tmp/test_dir")    
> 'ac9c542684f271e7215c00369bbb793e'
> ```
> 
> ```
> checksumdir -a md5 test_dir/
> ac9c542684f271e7215c00369bbb793e
> ```

also I have added a test file that does that and more kosmos 'j.sal.fs.test("hash")'
