### ISSUE TITLE
Explorer BCDB stress testing [development_fixes2]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#384]
Create a script to create nodes and reservations on explorer.
The script uses `j.clients.threebot.explorer`, which means you can configure your jumpscale to point to localhost and run explorer server and test against it. 

Please don't run it against `explorer.testnet.grid.tf` unless if you've already been clearly instructed to do so and cleared it with @zaibon or @serboctor .

```python3 explorer.py --help
Usage: explorer.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  cleanup          cleanup farms, nodes, and reservations created by...
  send-heartbeats  send heart beats from all the nodes on the explorer
                   every...
  stress-explorer  stress explorer by creating nodes and reservations
```

- `stress-explorer`: creates nodes and reservations on the explorer. 
- `send-heartbeats`: periodically calls uptime actor for all nodes on the explorer.
- `cleanup`: cleans up the objects created by `stress-explorer`. This needs to run on the environment where the objects where created. It doesn't use actors, it uses the bcdb instance and models directly. And make sure no threebotserver is running when you do the cleanup. 

The script can be found here https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_fixes2/scripts/explorer.py#L62

**Comment by serboctor** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/commit/5eb1c56f55cb9ab44609eda81cc3f82cf2fbd15a 

https://github.com/threefoldtech/jumpscaleX_threebot/commit/c97a08f841d8c1ab63e40060b29b741161b75ca2

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
