### ISSUE TITLE
SAL.FS: copy directory tree with overwriting

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#39]
### Steps:
1- Create a directory `test_dir`.
2- Create a file `test_file` with content `first` inside `test_dir`.
3- Create another directory `test_dir2`.
4- Create a file `test_file` with content `second` inside `test_dir2`.
5- Copy `test_dir` to `test_dir2` with `overwriteFiles=False`.
```
j.sal.fs.copyDirTree("test_dir", "test_dir2", overwriteFiles=False)
```
### Expected Result:
`test_file` inside `test_dir2` should contain `second`.

### Actual Result:
`test_file` inside `test_dir2` contains `first`.
`test_file` is overwritten!!

### The problem:
`rsync` argument is `True` by default and it doesn't care for `overwriteFiles` argument value.

**Comment by AhmedHanafy725** [comment]
#29

**Comment by zgorizzo69** [comment]
added test kosmos 'j.sal.fs.test("dir_file")'

**Comment by AhmedHanafy725** [comment]
https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/sal/fs/SystemFS.py#L286
For this line, it means that it will not remove the destination directory before copying if `rsyncdelete=True` and `overwirteFiles=False`, if this the expected behavior please update the docstring, if not please fix.

**Comment by zgorizzo69** [comment]
docstring updated

**Comment by AhmedHanafy725** [comment]
**Verified**
