### ISSUE TITLE
instead of redirect I get chat has ended

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#396]
instead of redirect, I get chat has ended
![image](https://user-images.githubusercontent.com/64129/71619996-e1847380-2bcf-11ea-9083-7edc5de6f9ca.png)

![image](https://user-images.githubusercontent.com/64129/71619973-cc0f4980-2bcf-11ea-8059-b6e21d0a7639.png)

**Comment by Dina-Abd-Elrahman** [comment]
verified
