### ISSUE TITLE
Nested schema tests broken

### ISSUE THREAD

**Issue by andrewayoub** [threefoldtech/jumpscaleX_core#398]
1- setting value for a property in nested schema doesn't work
2- _changed flag isn't working
# example
this code will fail
```
o.cmd.name = "a"
assert o.cmd._changed
assert o.cmd.name == "a"
```
# Steps to reproduce:
run `j.data.schema.test(name="embedded_schema")`

**Comment by xmonader** [comment]
fixed on development
