### ISSUE TITLE
no documention shown when autocompletion

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#4]
![image](https://user-images.githubusercontent.com/6021844/63680336-b2aa5b00-c7f3-11e9-82a2-aea8da842cc1.png)

can we see the docu? when using ? in shell/

**Comment by abom** [comment]
I seems like evaluating a property would just return the value, not the property itself, so the docstring returned will be the value's docstring

```python
    @property
    def object_config(self):
        """
        configuration object as used in kosmos
        with data stored in bcdb
        bcdb can be memory only, which means is not persisted
        :return:
        """
        return JSConfigBCDB
```

![Screenshot from 2019-09-03 12-35-38](https://user-images.githubusercontent.com/511438/64166849-3bef0c80-ce48-11e9-9d9e-7669a80be10a.png)


Will try to find away to identify properties and get its docstring

**Comment by hossnys** [comment]
verified on branch development_shell_docstring_debug 
```
 JSX> j.baseclasses.object_config 




                                                              
──────────────────────────────────────────────────────────────
configuration object as used in kosmos 
with data stored in bcdb 
bcdb can be memory only, which means is not persisted 
:return:                                                      
```
