### ISSUE TITLE
Tools: error when getting code template engine 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#40]
### Steps:
```
j.tools.code.template_engine_get()
```
### Result:
Seems that this module is not moved to the new repos.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/jumpscale_generated.py", line 329, in code
    from Jumpscale.tools.codeloader.CodeTools import CodeTools
  File "/sandbox/lib/jumpscale/Jumpscale/tools/codeloader/CodeTools.py", line 5, in <module>
    from .ClassBase import ClassBase, JSModelBase, JSRootModelBase
ModuleNotFoundError: No module named 'Jumpscale.tools.codeloader.ClassBase'

No module named 'Jumpscale.tools.codeloader.ClassBase'
```

**Comment by zgorizzo69** [comment]
there are some files missing for codeloading (templateEngine.py ClassBse.py etc..) that were previously in jumpscale/tools/codetools
 
where should I put them now ?
 
in jsx_core ? jsx_libs ? jsx_libs_extra ?
 
they all have a tool directory

**Comment by zgorizzo69** [comment]
it is used in systemFs replaceWordsInFiles but nothing is calling that replaceWordsInFiles func
let's remove but I have to keep CodeLoader.py bacause the load function is usd in testTools baseclass
