### ISSUE TITLE
gedis client failed to connect to explorer 3bot

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#404]
![2020-01-08_1722x1253_scrot](https://user-images.githubusercontent.com/303164/71981993-e5de0b80-3223-11ea-91a3-20431526934b.png)

**Comment by serboctor** [comment]
@zaibon I can't reproduce it on `development`. Any info that you can give me to be able to reproduce your state? which version were you using before?
![Screenshot from 2020-01-08 15-52-21](https://user-images.githubusercontent.com/6323012/71983207-f21b9600-322e-11ea-904e-43002ffc7c1b.png)

**Comment by serboctor** [comment]
I dont really see any recent changes in gedis client except this change in the default value of the package name. I undid it in my local code, created a gedis client instance then readded it again, and was able to get the gedis client without any issues. https://github.com/threefoldtech/jumpscaleX_core/commit/ec42c87df209ca24ca9ed36c63ec34ebb1a2139b#diff-c89b60396efd7415c12f0ce1b020606fL24

**Comment by zaibon** [comment]
So does this mean `package_name` argument is now mandatory? if so why is it still marked as optional ?

`JSX> cl = j.clients.gedis.get('explorer',host='explorer.testnet.grid.tf',package_name='tfgrid.directory')`
this line seems to work. But I'm still unable to use `j.clients.threebot` which is what end user are supposed to use.

**Comment by serboctor** [comment]
No, it doesn't mean it's mandatory. Nothing in what I said implies that it's mandatory. The change I linked only changed the default value of package_name in the schema. Can you paste the error you're getting for `j.clients.threebot`

**Comment by zaibon** [comment]
well using package_name is the only way I got to have actors to be loaded in the client. thus why I asked if it was mandatory to make it work. Which seems to be the case for me.

explorer is down again, so I can test anymore right now.

**Comment by serboctor** [comment]
@zaibon I was using `package_name` because that's how you did the call when you posted the first error not because it's mandatory, and I even used the same package. `package_name` already has default value `zerobot.base` in gedisclient.

**Comment by serboctor** [comment]
@zaibon since explorer is down and I also can't test against it. I started explorer locally, and tested both gedis and threebot client, and they both work fine. When explorer is up again, or when you face any errors, please add the stack trace to the ticket and I'll look into it.
![Screenshot from 2020-01-09 17-32-12](https://user-images.githubusercontent.com/6323012/72081048-78ef7200-3306-11ea-979f-b9a4aa8533d9.png)
