### ISSUE TITLE
[BCDB] Can't start kosmos shell

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#408]
![image](https://user-images.githubusercontent.com/46320202/72056883-1f6f4f00-32d6-11ea-88dc-5c250ac50d8a.png)

**To solve this issue in the mean time:**
``` rm  -rf /sandbox/cfg/bcdb```

**Comment by xmonader** [comment]
can't reproduce

**Comment by Dinaamagdy** [comment]
can't reproduce on current development status branch
