### ISSUE TITLE
[THREEBOT] Stoping threebot server after restarting kosmos raises an error

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/jumpscaleX_core#412]
If you start threebot server in the `background` then try to stop it from the same shell you started it from, it stops without any problems.

But if you exit kosmos after starting it in the background, open kosmos again and stop it, it will raise the following error.

![Screenshot from 2020-01-09 17-25-30](https://user-images.githubusercontent.com/6323012/72080372-5b6dd880-3305-11ea-885b-f2c2ca18e329.png)

**Comment by rkhamis** [comment]
no longer happens
