### ISSUE TITLE
implement find on alerthandler

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#420]
code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/tools/alerthandler/AlertHandler.py

use the peewee & text search fields

implement in

- js_alerts cmdline so we can use the find

also implement some proper test in .test()
where we test dedupe, creation of alerts, search

also implement delete

**Comment by abom** [comment]
Trying to do the following now (find already implemented by walking all alerts as they're only 100 element):

* delegate js_alerts to alert handler methods
* remove logging from alert handler

**Comment by abom** [comment]
For the first point mentioned in [the previous comment](https://github.com/threefoldtech/jumpscaleX_core/issues/420#issuecomment-577836169), alert handler itself still didn't implement some operations like printing...etc (trying `kosmos 'j.tools.alerthandler.print()'` won't work, seems like it still not implemented).
