### ISSUE TITLE
dict type check is broken

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#424]
![image](https://user-images.githubusercontent.com/64129/72278350-7fe6ef00-363c-11ea-9b3e-12388be841c3.png)

Suggest this 

```
    assert j.data.types.dict.check("\n") is False
```
to be added in JumpscaleCore/data/types/tests/3_dict.py

**Comment by xmonader** [comment]
Seems to be that's how it's implemented 
https://github.com/threefoldtech/jumpscaleX_core/blob/e06b0e23e9f7e19cb5819b8b5b6b35573d12a6ee/JumpscaleCore/data/types/CollectionTypes.py#L128

@despiegk should it stay that way?

**Comment by despiegk** [comment]
is indeed not well done

```
    def check(self, value):
        if isinstance(value, dict) or isinstance(value, j.baseclasses.dict):
            return True
```

should be it, done now

**Comment by rkhamis** [comment]
Fixed indeed
