### ISSUE TITLE
alerthandler shouldn't use bcdb should only use redis

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#428]
implement alerthandler over redis instead of bcdb so you can keep seeing alerts even when something wrong in bcdb

**Comment by abom** [comment]
Alert handler now uses redis, implemented in `RedisAlertHandler.py` and also, the UI is updated.

**Comment by abom** [comment]
To verify, the functionality is still the same, you can test alerta UI:

* Add alerta_ui package (if not added by default)
* Go to `http://<3bot host>/zerobot/alerta_ui`.


Alerts also now go to `redis`, under a alerts named `alerts`, this can be checked through `redis-cli` or even our `redis` client.

**Comment by Dinaamagdy** [comment]
verified but we need to update all docs in this issue  https://github.com/threefoldtech/home/issues/517
