### ISSUE TITLE
locations_static.new keeps adding new locations with the same name on every run

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#433]
locations_static.new keeps adding new locations with the same name on every run

**Comment by waleedhammam** [comment]
- This happens because inner schema objects are not unique, This will write the file more than one time only.

**Comment by xmonader** [comment]
I think can be done later, it's harmless to keep writing the same location files everyime, only problem it keeps creating locations in bcdb. shouldn't affect the release

**Comment by RafyAmgadBenjamin** [comment]
**fixed**
* **locations proxy**
![image](https://user-images.githubusercontent.com/46320202/72794972-86312880-3c45-11ea-88dc-16fdd9193ec4.png)

* **locations static**
![image](https://user-images.githubusercontent.com/46320202/72794997-90ebbd80-3c45-11ea-9a77-3eaf4ad06fc7.png)

**Comment by RafyAmgadBenjamin** [comment]
PR:
https://github.com/threefoldtech/jumpscaleX_core/pull/448

**Comment by RafyAmgadBenjamin** [comment]
example of how to use:
PR
https://github.com/threefoldtech/jumpscaleX_threebot/pull/352

**Comment by RafyAmgadBenjamin** [comment]
this on branch :  ```development_locations```

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
