### ISSUE TITLE
sonix test bcdb fails on osx [development_bcdb_sqlite]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#44]
![image](https://user-images.githubusercontent.com/6021844/64469618-53bedd00-d135-11e9-8369-c49c42f25c9d.png)

 kosmos 'j.data.bcdb.test(name="sonic")'

**Comment by zgorizzo69** [comment]
development_bcdb_sqlite doesn't exist anymore (merge into development_stabilize) can someone check if  j.data.bcdb.test(name="sonic") works on macos on branch development_stabilize ?

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
