### ISSUE TITLE
3git config file shouldn't be saved in the repo itself [development_fixes103]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#467]
make sure 3gitconfig.toml is ignored in the repos. It should exist in /sandbox/cfg instead

**Comment by abom** [comment]
Now after some investigation, we should maintain a configuration for any `threegit` instance (with location of `j.tools.threegit`).

The main reason is that we can have multiple `threegit` instances with different sub-directories as a source in a single repository, and if there's only a single configuration for every single repository, these sub-directories won't be processed again or they'll be processed again.

**Comment by abom** [comment]
Done in https://github.com/threefoldtech/jumpscaleX_core/pull/477, should not affect current behavior of loading wikis documented at https://github.com/threefoldtech/jumpscaleX_threebot/tree/development/docs/wikis/tech.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
