### ISSUE TITLE
unload gedis actors after package uninstall

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#469]
Make sure to remove gedis actors on package removal

**Comment by RafyAmgadBenjamin** [comment]
Fixed:
**PR**
https://github.com/threefoldtech/jumpscaleX_core/pull/471

**Comment by RafyAmgadBenjamin** [comment]
**verification steps:**

**Loading the package**
* j.servers.threebot.local_start_explorer(background=True)  
* package_manager_gedis= j.clients.gedis.get(name="test29",port=8901, package_name="zerobot.packagemanager") 
* package_manager_gedis.actors.package_manager.package_add(path = '/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/directory')
* test= j.clients.gedis.get(name="test30",port=8901, package_name="tfgrid.directory")
* test.reload()
* test.actors

**Delete package**
* package_manager_gedis.actors.package_manager.package_delete("tfgrid.directory")  
* test.reload()
* test.actors

**Comment by RafyAmgadBenjamin** [comment]
this issue in branch ```development_reload_package```

**Comment by Dinaamagdy** [comment]
verified on development branch
