### ISSUE TITLE
kosmos 'j.data.bcdb.test(name="models")' not working [development_bcdb_sqlite]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#47]

**Comment by zgorizzo69** [comment]
I have this error message  could not find attribute:_test_run in bcdbfactory (error was:'BCDBFactory' object has no attribute '_test_run')
do you have the same error ?

**Comment by zgorizzo69** [comment]
branch development_bcdb_sqlite has been merged into development_stabilize
all the bcdb test passes on that branch including j.data.bcdb.test(name="models")'

**Comment by Pishoy** [comment]
verified
```
3BOTDEVEL:jsx:jumpscaleX_core: kosmos 'j.data.bcdb.test(name="models")' 

 4c8bc3fb57cbe5ed6c70946c339d50d
Sun 15 09:34:25 JSBase.py            - 141 - jumpscale.bcdb.test.house          : ***CLASS INIT 1: jsxobject2
## .bcdb.test.house
id:15
 - name                : test_name_because_there_is_a_unique_constraint_on_it
 - active              : False
 - cost                : 15
 - newprop             : 
 - room                : []

Sun 15 09:34:25 TestTools.py         -  59 - bcdbfactory                        : ALL TESTS OK
Sun 15 09:34:25 BCDBFactory.py       - 486 - bcdbfactory                        : All TESTS DONE
Sun 15 09:34:26 BCDB.py              - 337 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK
Sun 15 09:34:27 BCDB.py              - 337 - bcdb                               : DATAPROCESSOR & SQLITE STOPPED OK

```
3BOTDEVEL:jsx:~: cd /sandbox/code/github/threefoldtech/jumpscaleX_core/
3BOTDEVEL:jsx:jumpscaleX_core: git log -1
commit 1f762dae27e38200c87e707ef393a62d37448907 (HEAD -> development_stabilize, origin/development_stabilize)
Author: Jo De Boeck <deboeck.jo@gmail.com>
Date:   Sun Sep 15 09:34:32 2019 +0200

    Cleanup some imports, use pudb in j.debug
    
    Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>
3BOTDEVEL:jsx:jumpscaleX_core: 
```
