### ISSUE TITLE
Webinterface locations doesn't get created

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#472]
After a fresh start for threebotserver, can't find webinterface locations like wikis, chat and letsencrypt.

![Screenshot from 2020-01-26 16-11-16](https://user-images.githubusercontent.com/10658229/73136468-ace0cc00-4056-11ea-8d7c-b28b44f98e37.png)

**Comment by waleedhammam** [comment]
resolved at: https://github.com/threefoldtech/jumpscaleX_core/commit/6a5d6444aeb10db105cfe9b5e59a5cbdbe506901

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
