### ISSUE TITLE
cannot debug properly in kosmos shell [development_bcdb_lite]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#49]
![image](https://user-images.githubusercontent.com/6021844/64484672-1f6f1d80-d216-11e9-93b2-a6a029cf9830.png)

do
kosmos -p 'j.tutorials.baseclasses.configobjects.test()'

but j.shell() in the script

try to do autocompletion and go into some objects

**Comment by despiegk** [comment]
do on development_bcdb_lite

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/64484723-b8059d80-d216-11e9-8cf8-621698784319.png)

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/64484729-cfdd2180-d216-11e9-9943-7b41b5c9f9bc.png)

**Comment by abom** [comment]
Still trying to find a solution on how to run two apps, also, sometimes  i cannot reproduce this issue.
Can you give me the versions of python, prompt-toolkit and ptpython?

**Comment by abom** [comment]
Running multiple applications concurrently is not handled in prompt-toolkit or ptpython (see https://github.com/prompt-toolkit/python-prompt-toolkit/issues/956#issuecomment-529525953).

Debugging with other debuggers like e.g. `pudb` might help until we can solve this issue.

> Can you give me the versions of python, prompt-toolkit and ptpython?
@despiegk

**Comment by abom** [comment]
Updated the docs with this known issue

https://github.com/threefoldtech/jumpscaleX_core/commit/571af66ea9d1cab65ca55483a2fd6f7af01e7726#diff-5b4eaa77374578866b8a6d876a05e1a6
