### ISSUE TITLE
configure wireguard interface 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#492]
* wireguard crash on Linux and Mac.

**Comment by RafyAmgadBenjamin** [comment]
**fixed**
* I have used the ```class ExecutorSSH``` to be able to connect from the host to the container as there was no way to use ```jumpscale``` from the host unless you have installed **Jumpascale** ```In System```.
* I have updated the subnet mask to allow the ```IP addresses``` to be in the same range.
* Separated peers configurations for Mac and Linux to be able to interface with docker in both cases.

fixed on branch ```development_osx``` 
the commit id 3de604259cfad19b082dc3031655a3a4dd7e38fe

**Comment by RafyAmgadBenjamin** [comment]
PR:
https://github.com/threefoldtech/jumpscaleX_core/pull/506

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
