### ISSUE TITLE
`init_my_threebot` function should allow to use the seed from 3bot connect app

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#494]
https://github.com/threefoldtech/jumpscaleX_core/blob/31b3e09024e4b0b1e83afe93b45dfb2b3668c54a/JumpscaleCore/tools/threebot/ThreebotToolsFactory.py#L51

At the moment `init_my_threebot` is the way to go to register an identity in BCDB.
We also said the user seed (and this key pair) should only be kept on the user phone using the 3bot connect app.
So the `init_my_threebot` function should allow to somehow specify the seed of the 3bot connect app or something so the public key registered in 3bot is the same one as in the 3bot connect app

**Comment by gmachtel** [comment]
I believe idea is to use a derived key.

**Comment by jdelrue** [comment]
So this 'init_my_threebot' is like still doing 'reseed'?

**Comment by zaibon** [comment]
> I believe idea is to use a derived key.

Indeed, but as far as I know to derive a key, 3bot connect system requires to have a domain. Which in this case we do not have since user just execute command from their local jsx container.

> So this 'init_my_threebot' is like still doing 'reseed'?

Not at all. `init_my_threebot` method just register the name, public key and email address into the BCDB phonebook. It doesn't do anything locally in the JSX container. 
This means that all the data stored by JSX in the container **ARE NOT** encrypted with the same key that is published to the phonebook.

**Comment by zaibon** [comment]
let's just go with what we have today, so the flow proposed at https://github.com/threefoldtech/jumpscaleX_core/issues/494#issuecomment-580751581 can be used as is
