### ISSUE TITLE
autocompletion for shell for kosmos broken [development_bcdb_sqlite]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#50]
/sandbox/code/github/threefoldtech/jumpscaleX_libs/tutorials/base/object_structure/BaseClasses_ConfigObjects.py

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/64484927-7a564400-d219-11e9-8ea4-b061b7d1d6d1.png)

**Comment by abom** [comment]
It's working now.

![Screenshot from 2019-09-11 17-35-45](https://user-images.githubusercontent.com/511438/64711881-99bfcc00-d4ba-11e9-9c9f-a79f39acb035.png)

**Comment by Pishoy** [comment]
verified
```
 commit 5a9dcc57248de8e922b811de6ea24838533aa95b (HEAD -> development, origin/development, origin/HEAD)
Author: ahmedelsayed-93 <ahmed.elsayed@gig.tech>
Date:   Mon Sep 16 10:17:42 2019 +0200

    fix sal.fs.isAbsolute method
```
