### ISSUE TITLE
paramterize package install [development_fixes103]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#503]
allow install to have parameters to allow different behaviors in package like installation branch, staging mode, production mode..etc

**Comment by RafyAmgadBenjamin** [comment]
Fixed:
**commits**
* https://github.com/threefoldtech/jumpscaleX_core/issues/503
* https://github.com/threefoldtech/jumpscaleX_threebot/commit/e559fa6ca86c6a7f183b2a4fabce2863c84d7416

**Changes**

* updated ```package_add``` method to take ```install_params``` in ```package_manager.py```.
* updated  ```install``` method ot take ```kwargs``` in ```ThreeBotPackage.py```.
* updated schema in ```ThreeBotPackageFactory.py``` to take ```params``` as dictionary.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
