### ISSUE TITLE
add graphviz dependency to installer

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#504]
add graphviz dependency to installer

**Comment by RafyAmgadBenjamin** [comment]
Fixed :
* graphviz was added to ```apts_list``` which contains all the packages that will be installed using ```apt```.

**Comment by RafyAmgadBenjamin** [comment]
Fixed on mac, I made it be installed using brew.

**Comment by hossnys** [comment]
This fix verified on branch development_logalert but only on in container installation as the fix of in system installation cmake error done on branch development and development_hotfixes.

![Screenshot from 2020-02-09 19-11-01](https://user-images.githubusercontent.com/26298009/74106526-6c15a680-4b70-11ea-8ee6-a8f8439a0bdf.png)
