### ISSUE TITLE
undoing changes in 3git doesn't reflect

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#505]
in any document
- add `??`
- reload
- remove `??`
- reload (won't work)

**Suggested solutions**

- staging changed files always during processing 

- keeping custom index in threegit tool
  - At the beginning on a specific commit, it will process normally and then it will store the git revision in 3git configs.
  - Then assume we have untracked file file1.md, and modified files file2.md, file3.md we can store these files in a list and append it to the 3git config
  - When we process we should check if these files are available in the list or not [can be tracked with git diff], if not available we should reprocess these files. and update this list

```diff
diff --git a/JumpscaleCore/tools/threegit/DocSite.py b/JumpscaleCore/tools/threegit/DocSite.py
index 8a3a7f69..dfc93278 100644
--- a/JumpscaleCore/tools/threegit/DocSite.py
+++ b/JumpscaleCore/tools/threegit/DocSite.py
@@ -265,11 +265,18 @@ class DocSite(j.baseclasses.object):
         else:
             # check changed files and process it using 3git tool
             self.revision = self.threegit.revision
+            if self.threegit.changed_files_revision != self.threegit.revision:
+                self.threegit.changed_files = []
+                self.threegit.changed_files_revision = self.threegit.revision
+
             revision, self._files_changed, old_files = self.threegit.git_client.logChanges(
                 path=self.path, from_revision=self.revision, untracked=True
             )
+            self.threegit.changed_files = list(set(self._files_changed + self.threegit.changed_files._inner_list))
 
-            for item in self._files_changed:
+            print(f"revision: {revision}, changed {self._files_changed}, old {old_files}, hreegit changed {self.threegit.changed_files} ")
+            for item in set(self._files_changed + self.threegit.changed_files._inner_list):
+                print("item is changed: ", item)
                 item = f"{self.threegit.git_client.path}/{item}"
                 if j.sal.fs.exists(item):
                     if j.sal.fs.isFile(item):
diff --git a/JumpscaleCore/tools/threegit/ThreeGit.py b/JumpscaleCore/tools/threegit/ThreeGit.py
index 5ff95359..0f660a8e 100644
--- a/JumpscaleCore/tools/threegit/ThreeGit.py
+++ b/JumpscaleCore/tools/threegit/ThreeGit.py
@@ -33,6 +33,8 @@ class ThreeGit(j.baseclasses.object_config):
         relative_base_path = "" (S)
         dest_path = "" (S)
         revision = "" (S)
+        changed_files = (LS)
+        changed_files_revision = (S)
         """
```

**Comment by abom** [comment]
Undoing changes without a commit?
I mentioned this problem before, we basically use `git`, hence we cannot get the changes using `git diff`unless we commit this changes, then do a revert commit or so.

The should mention this in docs or find another way (maybe maintaining a custom index instead of git).

**Comment by xmonader** [comment]
@abom better solution would be tracking the output dir and do git reset in case of no changes

**Comment by waleedhammam** [comment]
**Suggested approach**

- At the beginning on a specific commit, it will process normally and then it will store the git revision in 3git configs.

- Then assume we have untracked file file1.md, and modified files file2.md, file3.md we can store these files in a list and append it to the 3git config

- When we process we should check if these files are available in the list or not [can be tracked with git diff], if not available we should reprocess these files. and update this list

**Comment by waleedhammam** [comment]
**Commit**

https://github.com/threefoldtech/jumpscaleX_core/commit/7328dc3090a9036214713cd85e98839336fd422c

**Changelog**

- Applied the second scenario in the issue description.

**How to verify**

- Start 3bot server
- load any wiki for example 
  ```bash
  jsx wiki-load -n grid -u https://github.com/threefoldfoundation/info_grid -f
  ```

- Check the wiki is loaded at: https://172.17.0.2/wiki/grid

- modifiy any file for example
  ```bash
  /sandbox/code/github/threefoldfoundation/info_grid/docs/concepts/cloud_units.md
  ```

- reload the wiki
  ```bash
  jsx wiki-reload -n grid
  ```

- Check the changes in https://172.17.0.2/wiki/grid#/concepts/cloud_units

- restore the file to the original state

- reload the wiki
  ```bash
  jsx wiki-reload -n grid
  ```

- Check the changes in https://172.17.0.2/wiki/grid#/concepts/cloud_units make sure it's back to the original state

**Comment by hossnys** [comment]
verified on branch development_fixes103

![Screenshot from 2020-02-10 15-26-27](https://user-images.githubusercontent.com/26298009/74153766-f8c86f00-4c19-11ea-9e51-b6fe0caf9413.png)

![Screenshot from 2020-02-10 15-27-40](https://user-images.githubusercontent.com/26298009/74153769-fbc35f80-4c19-11ea-8a71-edfda750b9a2.png)
