### ISSUE TITLE
ServerRackFactory.py test need to be refactored 

### ISSUE THREAD

**Issue by john-kheir** [threefoldtech/jumpscaleX_core#508]
#### Test Location
/sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/servers/gevent_rack/ServerRackFactory.py
#### Note
More than one step need to be changed

**Comment by serboctor** [comment]
Fixed herehttps://github.com/threefoldtech/jumpscaleX_core/commit/7e4cbcf2e56bf6b376dda98a7f916c9250009b57 and here https://github.com/threefoldtech/jumpscaleX_core/commit/2708efc618520587dd32f09722b7af90a3d1cbdc

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
