### ISSUE TITLE
package_stop  in package manager do nothing 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#510]
## Steps 
- gedis_client = j.clients.gedis.get("pm", port=8901, package_name="zerobot.packagemanager")
package_manager = gedis_client.actors.package_manager
- giturl ="https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_testrunner/ThreeBotPackages/examples/test_package"
- package_manager.package_add(git_url=giturl)
-  check package status = "Installed"
## Issue 
try package_manager.package_stop(p.name), will not do anything and try to get package status will find it still installed

**Comment by xmonader** [comment]
`stop` is typically defined by the package author should be defined in `package.py`
