### ISSUE TITLE
installing jsx in system raised cmake build error [development_hotfixes]

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/jumpscaleX_core#512]
OS : Ubuntu 18.04 fresh machine
branch : development 
when installing jsx in system found this error 
![Screenshot from 2020-02-09 12-14-32](https://user-images.githubusercontent.com/26298009/74100891-3c4cab80-4b3c-11ea-8b5e-0442b81fa6f5.png)

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/jumpscaleX_core/commit/ebb6c155ab05cdd36e113ebb182cf71883d9bdfc on `development_hotfixes`

**Comment by hossnys** [comment]
verified on branch development 

![Screenshot from 2020-02-09 17-34-24](https://user-images.githubusercontent.com/26298009/74105005-b728bd00-4b62-11ea-8f51-7b5224f7aaf4.png)

![Screenshot from 2020-02-09 17-41-21](https://user-images.githubusercontent.com/26298009/74105065-40d88a80-4b63-11ea-98fb-35bb7f27906e.png)
