### ISSUE TITLE
None object has no attribute lpush [development_hotfixes]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#516]
![image](https://user-images.githubusercontent.com/64129/74104641-5ba90000-4b5f-11ea-86e1-7cb8071e3290.png)

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/jumpscaleX_core/commit/3cf05bd3082ace7ce1dfcbac4b0af56fb82c9062

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
