### ISSUE TITLE
threebot-test to work on Mac 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#517]
make sure in mac you can start 2 (3bots) containers 1 is explorer and the other 1 is 3bot. 
- [x] connect containers through 1 of the containers and should access all of them on 172.17.0.X

**Comment by RafyAmgadBenjamin** [comment]
* I have updated the ```wireguard``` on the host.
* I have made the binding ports of the containers to be dynamic when it is written in the ```wireguard``` configuration. 
* I have made the ```wireguard``` configuration in the host have more than a peer each one related to a running container 
* I have made the container IP(container localhost) also dynamic when it is written in the ```wireguard``` configuration.
* Fixed an issue related executing ```sudo``` commands on mac as it creates a folder for sandbox in the root directory which is no longer valid in mac.
* Fixed an issue related to copying the configuration from the container to the host

This is fixed on ```development_osx``` branch

**Comment by RafyAmgadBenjamin** [comment]
I am now working to use our code to get the desired configuration from the docker instead of using the ```docker``` python client.

**Comment by RafyAmgadBenjamin** [comment]
PR:
https://github.com/threefoldtech/jumpscaleX_core/pull/528

**Comment by hossnys** [comment]
verified on branch unstable
steps :
- create two jumpscale containers on mac OS host . 
``` jsx threebot-test -c2```
- install wireguard on host and do this command : 
``` jsx wireguard```
this will configure internal network between host and the created jumpscale containers.
- then if you start threebot server on both containers , you can reach them with https://172.17.0.2 and https://172.17.0.3

![image](https://user-images.githubusercontent.com/26298009/74841832-01175d00-5332-11ea-96d1-c53d4abdb41e.png)

![image](https://user-images.githubusercontent.com/26298009/74841852-07a5d480-5332-11ea-8eb3-0b9ec8e26b40.png)
