### ISSUE TITLE
Error in worker running for first time [unstable]

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#518]
**How to reproduce**

on branch _unstable_

- Fresh installation or delete all data in bcdb/redis using "DO WITH CAUTION WILL DELETE ALL OF YOUR DATA"

  ```bash
  bcdb delete --all
  pkill -9 redis
  ```

- Start 3bot server

  ```bash
  kosmos -p "j.servers.threebot.local_start_explorer(with_shell=False, background=True)" 
  ```

- In tmux workers_1 or workers_2 you will find the following
  
![Screenshot from 2020-02-10 18-18-42](https://user-images.githubusercontent.com/10658229/74168353-46e96c80-4c32-11ea-8758-e43720088cf3.png)

 - Possible cause

  ![Screenshot from 2020-02-10 18-15-17](https://user-images.githubusercontent.com/10658229/74168417-5e285a00-4c32-11ea-99ad-4038aab6871c.png)

  Redis server replies with b'OK' at the first call

**Comment by despiegk** [comment]
this should bever be b'OK'
where is this code, please next time also mention where screenshot is from

I found the code its in BCDBModelClient.get

this means it contacts the threebot server, is this the case?
is the threebot server active?
why is 'OK' coming back this should not be the case

there should be data coming back from the BCDB on the threebotserver

investigate more and let me know please

**Comment by andrewayoub** [comment]
we found that the unwanted `b'OK'` response is coming from `set` method in `RedisServer.py` line 253:
![image](https://user-images.githubusercontent.com/5163693/74342282-ea14c000-4db1-11ea-9172-4517e1d0e33a.png)


after removing the `new` check and return the id in both cases it worked, but I'm not sure if that's a good fix.

**Comment by andrewayoub** [comment]
I pushed the fix here: https://github.com/threefoldtech/jumpscaleX_core/commit/a1b383becd5f77046f43e87261b3039425e06718

**Comment by hossnys** [comment]
verified on branch unstable

![Screenshot from 2020-02-13 09-42-37](https://user-images.githubusercontent.com/26298009/74412128-6efce980-4e45-11ea-9d57-2b02d0e86532.png)

![Screenshot from 2020-02-13 09-46-33](https://user-images.githubusercontent.com/26298009/74412207-92c02f80-4e45-11ea-8419-438301ef8865.png)
