### ISSUE TITLE
myjobs needs change, should not use the return queue but the redis interface to BCDB [development_bcdb_sqlite]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#52]
- even if used as part of shell or test script start in gedis the redis server for BCDB
- make sure the redis server for BCDB (in gevent loop) ONLY listens on localhost by default
- change the process worker to get & set the objects (worker & jobs & actions) from the redis using a redis client
- in mean time also test the RDB tool if it can see the redis server so its easy to troubleshoot
- change the myjobs factory, return data management loop not required

see /sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/servers/myjobs/MyWorkerProcess.py

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/64485225-1a15d100-d21e-11e9-8c13-7e301f075350.png)

**Comment by despiegk** [comment]
also now we have a better indexer (sqlite) we can be more intelligent around finding which jobs to process, or are outdated, or ...

**Comment by grimpy** [comment]
Made some progress today added redis connector to myjobs factory
Made some basic fixes for bcdb aswell

Started implementation of get/set method through redis client

Still not fully working though, all code is pushed so far

**Comment by grimpy** [comment]
Pushed from progress... 

bcdb connector is now working still need to test the full myjobs flow

**Comment by grimpy** [comment]
Tests up untill 8 are working again.
Working on dependencies now

**Comment by grimpy** [comment]
Dependencies is working again aswell

What should be done with test 7

https://github.com/threefoldtech/jumpscaleX_core/blob/development_stabilize/JumpscaleCore/servers/myjobs/tests/7_wait.py#L1

We have return_queues parameters while we in reality don't have returnqueues anymore and a wait method with queue_name.

I can see from the old implementation this was used for grouping jobs together and wait for the entire group.

I would recommend renaming returnqueus to tags and do grouping based on tags instead.

**Comment by Pishoy** [comment]
- fancecode test : was not done as Jo said 
`kosmos -p 'j.servers.myjobs.test("fancycode")'` 

- basic test : passed successfully 

- simple_error and timeout test has the same error as below 
```
kosmos 'j.servers.myjobs.test("simple_error")'
kosmos 'j.servers.myjobs.test("timeout")'
```
![image](https://user-images.githubusercontent.com/21987477/65150015-80230500-da23-11e9-99a5-6cc9a6524ab8.png)
 
- data_process test : passed successfully 
```
kosmos -p 'j.servers.myjobs.test("data_process")'
```
- test and test2 : passed but not exist properly at the end, i have to press ctl+c to exist from test 
```
kosmos -p 'j.servers.myjobs.test("start")'
kosmos -p 'j.servers.myjobs.test("start2")'
```
![image](https://user-images.githubusercontent.com/21987477/65150149-c4aea080-da23-11e9-8ea9-16de3b53a614.png)

 - workers : got below error 
```
kosmos -p 'j.servers.myjobs.test("workers")'
```
![image](https://user-images.githubusercontent.com/21987477/65150402-5ae2c680-da24-11e9-8321-e0e8f558ea01.png)

- wait test:  passed successfully 
```
kosmos -p 'j.servers.myjobs.test("wait")'
```
- tmux test : got error as below 
```
kosmos -p 'j.servers.myjobs.test("tmux")'
```
![image](https://user-images.githubusercontent.com/21987477/65150696-ee1bfc00-da24-11e9-8700-1d41f1383e84.png)

- dependencies test : default one passed but fail when reset flag is True as below   
```
kosmos -p 'j.servers.myjobs.test("dependencies")'
```
passed 
```
kosmos -p 'j.servers.myjobs.test("dependencies",reset=True)'
```
![image](https://user-images.githubusercontent.com/21987477/65150964-71d5e880-da25-11e9-83cd-2457b92c1e9d.png)

**Comment by grimpy** [comment]
fixed the headers in the tests
All test should run with `kosmos -p` flag myjobs does not work withouth

Fixed 8_tmux test wait time was not long enough.
Disabled fancycode test.

All other tests are working. Yes they throw exceptions in your face but they and with ALL TESTS OK which means it works (the exceptions are part of handling exceptions in jobs)

**Comment by Pishoy** [comment]
verified 
```
commit 13c45144fbe09fca9be717408a0d3a3891db6413 (HEAD -> development, origin/development, origin/HEAD)
Author: Waleed Hammam <waleed.hammam@gmail.com>
Date:   Thu Sep 19 13:52:33 2019 +0200

    exculde symlinks from foldermd5sum
    
    symlinks causing differ in the md5checksum of directories.

```
