### ISSUE TITLE
don't auto define appname in logs [unstable]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#520]
instead of auto defining appname in logs we need to let the user think and choose a more meaningful name

**Comment by waleedhammam** [comment]
we already do this, for example in threebotserver we add `j.application.start("threebotserver")`

and when we get logs `js_logs -a threebotserver tail`

also to myworkers, kosmos and builders

if u didn't set it, it will use the default `init`

more info at: https://github.com/threefoldtech/jumpscaleX_core/tree/unstable/docs/logger

example case:

![Screenshot from 2020-02-11 12-54-13](https://user-images.githubusercontent.com/10658229/74230723-a2b50380-4ccd-11ea-80c8-f80f8449ee65.png)
