### ISSUE TITLE
Sonic builder [unstable]

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#529]
Error in sonic builder on unstable in fresh installation [in system]

![Screenshot from 2020-02-12 18-31-43](https://user-images.githubusercontent.com/10658229/74356776-957c3f80-4dc7-11ea-8f32-968f96782afe.png)

**Comment by serboctor** [comment]
This is because of the fixes in this issue where we decided not to build rust unless `reset` is `True`. Maybe it can be modified to make this check only if rust is installed. https://github.com/threefoldtech/jumpscaleX_builders/issues/37

**Comment by serboctor** [comment]
Fixed by this https://github.com/threefoldtech/jumpscaleX_builders/commit/3e1c06d291a8f096dd9577c687ba5f235eceb27b

**Comment by hossnys** [comment]
verified on branch unstable :

```
root@jsx-test:~# curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX_core/unstable/install/jsx.py?$RANDOM > /tmp/jsx;
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34333  100 34333    0     0   279k      0 --:--:-- --:--:-- --:--:--  279k
root@jsx-test:~# chmod +x /tmp/jsx;
root@jsx-test:~# /tmp/jsx install -b unstable

```
![Screenshot from 2020-02-19 17-11-23](https://user-images.githubusercontent.com/26298009/74847412-bcdc8a80-533a-11ea-9ab1-af3d8b3af6e5.png)
