### ISSUE TITLE
bcdb tests need teardown 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#539]
- In the beginning delete bcdb bcdb delete --all 
- run tests , will all pass 
- run tests again will raise error in different tests every run 
- if u delete bcdb and  run again will works successfully 

note: tests fail random , every time u run without clear bcdb different tests will fail.

**Comment by despiegk** [comment]
restructured the way how testing needs to be done:
call
j.data.bcdb._test_model_get()
or
j.data.bcdb._test_bcdb_get()

all the used BCDB's use databases specially made for testing
no existing data will get ruined

**Comment by despiegk** [comment]
see bcdb test story
