### ISSUE TITLE
js_logs: add an option to list current apps

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_core#546]
Listing app names with e.g. `js_logs list-apps`, which will make it easy for people who don't know which app names are running to list their logs.

**Comment by abom** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/a7927011ac0046c2bfad499bc1254391e50d5c43

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/75005654-bb64ac80-5477-11ea-8efc-e392738db66b.png)

why not hook on  j.app.start("logname") why don't you insert into a set in redis the app name
and when u want to list it u do get on that set instead of walking over all log lines? or is because you have only a 1000 key in redis?

**Comment by hossnys** [comment]
verified on branch unstable
```
3BOTDEVEL:3bot:bin: js_logs --help
Usage: js_logs [OPTIONS] COMMAND [ARGS]...

Options:
  -a, --appname TEXT    application name, default: init
  --redis-secret TEXT   redis secret (empty by default)
  --redis-port INTEGER  redis port (defaults to 6379)
  --redis-host TEXT     redis host (defaults to localhost)
  --help                Show this message and exit.

Commands:
  count      tail logs from session
  find       filter by appname, filepath, category, message, pid and/or
             time...
  list-apps  list all app names
  tail       tail logs from session
3BOTDEVEL:3bot:bin: js_logs list-apps
Total of 4) apps:
threebotserver
init
workers_1
workers_2

```

**Comment by abom** [comment]
@hossnys Will re-open the issue, need to update how we list apps as @xmonader suggested, because using redis `keys` command is not recommended.

**Comment by xmonader** [comment]
https://github.com/threefoldtech/jumpscaleX_core/pull/629 fixed in
