### ISSUE TITLE
wiregaurd tests should be not interactive 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#551]
j.tools.wireguard.test()   
will ask about passwaord 
```
  File "/usr/local/lib/python3.6/dist-packages/pssh/clients/native/single.py", line 195, in _init
    return self._connect_init_retry(retries)
  File "/usr/local/lib/python3.6/dist-packages/pssh/clients/native/single.py", line 174, in _connect_init_retry
    return self._init(retries=retries)
  File "/usr/local/lib/python3.6/dist-packages/pssh/clients/native/single.py", line 197, in _init
    raise AuthenticationException(msg, self.host, self.port, ex)
pssh.exceptions.AuthenticationException: ('Authentication error while connecting to %s:%s - %s', 'localhost', 22, AuthenticationException('No authentication methods succeeded',))
2020-02-19T12:35:52Z (<ThreadPool at 0x7fef8133bbe0 0/1/10 hub=<Hub at 0x7fef81332978 thread_ident=0x140666748262208>>, <bound method SSHClient._init of <pssh.clients.native.single.SSHClient object at 0x7fef73380cc0>>) failed with AuthenticationException

root@localhost's password: 
```

**Comment by ranatrk** [comment]
Could not reproduce, running test() didnt ask for any passwords. @Dinaamagdy were there any other steps incolved except running the test?

![Screenshot from 2020-05-07 11-58-18](https://user-images.githubusercontent.com/17128393/81281453-2591f400-905a-11ea-81a8-2a0f4215fc27.png)

**Comment by Dinaamagdy** [comment]
@ranatrk  No , just run test

**Comment by ranatrk** [comment]
I tested again on a fresh installation with 3bot sdk where the only command run was `j.tools.wireguard.test()` and still couldn't reproduce
![Screenshot from 2020-05-07 12-16-47](https://user-images.githubusercontent.com/17128393/81283377-cf728000-905c-11ea-82c5-1464812f7a62.png)

**Comment by ranatrk** [comment]
Was able to reproduce the issue with the current 3sdk installation, will look into it

**Comment by ranatrk** [comment]
This issue occurs when the ssh agent wasnt available during installation and so the loaded keys werent copied to the authorized keys of the container. currently working on checking when loading that there is an ssh agent

**Comment by ranatrk** [comment]
Since there are prerequisite steps needed to be done (creating container and adding ssh keys to it) this test needs to be run manually following the steps in its docstring. https://github.com/threefoldtech/jumpscaleX_core/commit/a26363af4b30b49fedac230748ecd85773595b93

**Comment by AhmedHanafy725** [comment]
I tested with another container beside 3bot container.
### Steps
1- Create privileged testing container.
```bash
docker run -it --name test_wireguard --privileged ubuntu:18.04
```
2- Install needed packages.
```bash 
apt-get install -y ssh iproute2 software-properties-common
```
3- Put sshkey (`id_rsa.pub`) from 3bot container to testing container in `auhorized_keys`.
4- Start  ssh service in the testing container.
```bash
service ssh start
```
5- Create ssh client with `do` name and addr of the testing container.
```python 
j.clients.ssh.get(name="do", addr=<testing container ip>)
```
6- Run the test.
```python
j.tools.wireguard.test() 
```

### Result
Test is working fine.

![image](https://user-images.githubusercontent.com/41957921/82329826-2c1d5580-99e2-11ea-97b1-764f82bc6e64.png)

**Verified**
