### ISSUE TITLE
error in zdb test method 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#552]
Error in zdb test method ( cannot start zdb )

![error](https://user-images.githubusercontent.com/21218053/74836089-5b5ef080-5327-11ea-987a-b6d6f679771b.png)

**Branch**  development_testrunner

**Comment by serboctor** [comment]
Fixed on `unstable` https://github.com/threefoldtech/jumpscaleX_core/commit/7df7562c243ddabd30d583b573c49638cbaf99df

**Comment by hossnys** [comment]
verified on branch unstable :

![Screenshot from 2020-02-19 18-17-04](https://user-images.githubusercontent.com/26298009/74851479-f82f8700-5343-11ea-871e-f212e1d3fcc7.png)
