### ISSUE TITLE
Error in logger if redis is killed

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#554]
we always assert there are 1000 log in redis here https://github.com/threefoldtech/jumpscaleX_core/blob/c57ad7bcb5cfe0e4e47a6a4410e9055d1295b9b1/install/InstallTools.py#L925

but in somecases if there are logs in filesystem and redis is killed this number can be changed

 
![image](https://user-images.githubusercontent.com/10658229/74839965-d677d500-532e-11ea-8005-154ea7973a00.png)

**Comment by waleedhammam** [comment]
Fixed at: https://github.com/threefoldtech/jumpscaleX_core/commit/c3763a393f3ca0a39188bda3323ce51ab66c2e04, it was caused also by redis memory limit excedded

**Comment by Dina-Abd-Elrahman** [comment]
- verified
