### ISSUE TITLE
js_logs: find logs inside filesystem not only redis [development_logalert2]

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_core#556]
Logs in redis are limited to 1000 log only, need to do `find` inside file system.

**Comment by xmonader** [comment]
redis and filesystem searches should be available

**Comment by waleedhammam** [comment]
Commit: https://github.com/threefoldtech/jumpscaleX_core/commit/bd9e2c13d91253278ab13cf21db1ca1420241929

Changelog
- Added search in fs
- Updated docs at https://github.com/threefoldtech/jumpscaleX_core/blob/bd9e2c13d91253278ab13cf21db1ca1420241929/docs/logger/README.md#js_logs
- some fixes for handling errors when redis is not available

- Example:

```bash
js_logs -a threebotserver find_fs --message "index"
```

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
