### ISSUE TITLE
inconsistent behaviour in zbd server test method

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#557]
- zdb server test case working fine inside zdb shell, but doesn't work when I run it like this `kosmos -p 'j.servers.zdb.test()'`

![ff](https://user-images.githubusercontent.com/21218053/74915070-40928780-53cc-11ea-8620-a1483e869b1c.png)

**Comment by serboctor** [comment]
I changed the process name it matches on so this wouldnt happen. It's fixed on `unstable` https://github.com/threefoldtech/jumpscaleX_core/commit/9b4d9994de45886f2c7982c3ca8b9483f1806d0c

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
