### ISSUE TITLE
finish webdav actor

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#56]
/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/webdav/WebdavFactory.py

- [x] add tests
- [x] tests are like examples
- [x] add some docs

### as part of test

- [x] start server (install)
- [x] use webdav client to set/get info (python)
- [x] do also a mount/sync example with rclone

**Comment by despiegk** [comment]
check that the data is in the filemanager

**Comment by ashraffouda** [comment]
so far the packaging for webdav is done, rclone examples already merged  there and this following pr is for the tests using python client, docs for using python client already merged
https://github.com/threefoldtech/jumpscaleX_threebot/pull/30
