### ISSUE TITLE
package delete doen't work 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#561]
## Steps 
- gedis_client = j.clients.gedis.get("pm", port=8901, package_name="zerobot.packagemanager")
package_manager = gedis_client.actors.package_manager
- giturl ="https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_testrunner/ThreeBotPackages/examples/test_package"
- package_manager.package_add(git_url=giturl)
-  check package status = "Installed"
## Issue 
try package_manager.package_delete(p.name), will not do anything and try to get package status will find it still installed and package still exist in package list

**Comment by m-motawea** [comment]
Fixed in PR: https://github.com/threefoldtech/jumpscaleX_core/pull/590

**Comment by Dina-Abd-Elrahman** [comment]
## steps

- gedis_client = j.clients.gedis.get("pm", port=8901, package_name="zerobot.packagemanager")
- package_manager = gedis_client.actors.package_manager
- giturl ="https://github.com/threefoldtech/jumpscaleX_threebot/tree/development_testrunner/ThreeBotPackages/examples/test_package"
- package_manager.package_add(git_url=giturl)
- check if the package is installed, it should be installed ( we can check it using cmd or from portal) 

http://172.17.0.2/zerobot/packagemanager/
```packages = package_manager.packages_list().packages
for package in packages: 
    if "test_package" in package.name: 
    print(package)
```

- try to delete the package:
```package_manager.package_delete(name="jumpscale.test_package")```

and check again if it is installed, shouldn't be exist.
