### ISSUE TITLE
test jsx threebot-test [unstable]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#568]
test behaviour of 

```bash
jsx threebot-test -w -d -c 3
```

## result should be

- 3 containers
- first container is the explorer (master 3bot)
- 2nd & 3e container are registered as 3bot in the first container
- wireguard connection to the first container, routing to the other containers (so only 1 WG connection) only on OSX (test on there as well)
- do a test as part of this method to see if the 2nd container can talk to first container (actor)
- check wiki is up & running on master for threefold_foundation_info
- check admin package we are working on with webix is live on first containter
- test all on unstable

**Comment by rkhamis** [comment]
All tested and running on ubuntu. Still OSX.
Dashboard will be verified as soon as ready

**Comment by alichaddad** [comment]
There is an issue with conflicting ports when starting the third container which I am currently fixing. Tested on Mac.

**Comment by xmonader** [comment]
not valid use case now
