### ISSUE TITLE
Inconsistent load of bcdb schema

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#569]
How to reproduce:

- Add a new field to schema for example `capacity` in this schema https://github.com/threefoldtech/jumpscaleX_threebot/commit/f868e8048059a757d4f895edcafba5434dafa9cd

- Create a new object it won't be there

**Comment by zaibon** [comment]
that was my bad I guess. The field was not yet on the explorer so when getting a client to the explorer the schema sent by the server was missing the field
After updating the schema server side and restarting it. I get the expected results
