### ISSUE TITLE
improve actors for myjobs [development_package_myjobs]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#57]
/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/myjobs/actors/myjobs.py

- [ ] use model.index.sql ... index as much as possible
- [x] have parameters to make it easy to query jobs & workers & actions
- [x] make interface more compelte

first make a mockup then ask Kristof to verify

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/64485809-3a955980-d225-11e9-827d-1859ec62aeaa.png)

- can be done in 2x less code at leas if not 5x
- code of actors should always be novice developer friendly read (even non developers should understand), its just using our SAL/CLIENTS/...

**Comment by xmonader** [comment]
work is on https://github.com/threefoldtech/jumpscaleX_threebot/blob/development_web_blog/ThreeBotPackages/myjobs/actors/myjobs.py , sql.index not used

**Comment by rkhamis** [comment]
obsolete
