### ISSUE TITLE
error in sonic client test method 

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#570]
error in sonic client test method. 

**Branch** unstable, **Commit_ID** 85a7b5da341551b6bfff108a77e15ad216f4db4f

![error](https://user-images.githubusercontent.com/21218053/75358324-6089e580-58bb-11ea-83db-2cc5011445c3.png)

**Comment by rkhamis** [comment]
we don't really use sonic
