### ISSUE TITLE
j.clients.tfgrid_client object is broken if threebot server is not running

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#572]
`j.clients.tfgrid_registry`

![error](https://user-images.githubusercontent.com/21218053/75446334-dfd8f100-596f-11ea-8b6a-c83a16bcdc67.png)

**Comment by john-kheir** [comment]
## Blockers
We can't have a green full run without solving this issue since at the time of running the registry tests, the 3bot is not running and `j.clients.tfgrid_registry` is broken

**Comment by xmonader** [comment]
for the issue picker we shouldn't have any side effect in init at all.
