### ISSUE TITLE
error in  gedis_websock server test method

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#575]
error in  gedis_websock server test method

![ff](https://user-images.githubusercontent.com/21218053/75625631-af3fc400-5bc8-11ea-8b28-e6569bcdd908.png)

**Comment by xmonader** [comment]
websocket not used anymore. need to disable that.

**Comment by Dina-Abd-Elrahman** [comment]
done 69674ff1b16fdc8ff434a4c179e1641d15522832
