### ISSUE TITLE
 inconsistent behavior for rack server test method

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#581]
inconsistent behavior for rack server test method

![ff](https://user-images.githubusercontent.com/21218053/75764958-5ba7b480-5d47-11ea-966d-7c3e372e4801.png)

**Branch** unstable, **Commit_ID** afb93eee52b75c6cafd1abba335e72ca76bfe9ee

**Comment by ashraffouda** [comment]
![Screenshot from 2020-03-18 16-07-31](https://user-images.githubusercontent.com/1689456/76969167-affb8880-6932-11ea-97d0-dff356e76746.png)

not reproducable

**Comment by Dina-Abd-Elrahman** [comment]
not reproducable
