### ISSUE TITLE
make explorer address configurable per network

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#587]
It seems at the moment the address of the explorer for the grid is hardcoded to `explorer.testnet.grid.tf`:
https://github.com/threefoldtech/jumpscaleX_core/blob/cd95aa6b6f8b4c91b979295b3d51a10ae543be1a/install/InstallTools.py#L3538-L3541

This needs to change and make it configurable by the user. He must be able to choose to which network he talks any point in time.

A simple config should allow the user to switch to a different network and everything should just keep working

**Comment by zaibon** [comment]
@xmonader @rkhamis @tobiaschielens @jdelrue 
If you guys have location you know we have hardcoded value for the explorer address, please write them down here.

**Comment by tobiaschielens** [comment]
One for the frontend: https://github.com/threefoldtech/jumpscaleX_threebot/blob/4392ac8c87b43975151cfb344455eefeaba78f43/ThreeBotPackages/threebot/farmmanagement/html/config/farmmanagement.config.local.js#L2

**Comment by xmonader** [comment]
- jumpscaleX_threebot/ThreeBotPackages/zerobot/webplatform/html/config/config.local.js:5:  phonebookActor: "https://explorer.testnet.grid.tf/tfgrid/phonebook/actors/phonebook"
- jumpscaleX_threebot/ThreeBotPackages/threebot/fileserver/threetransfer/config/config.local.js:5:  tfGridApiUrl: "https://explorer.testnet.grid.tf/web/gedis/http"
- jumpscaleX_threebot/ThreeBotPackages/threebot/farmmanagement/html/config/farmmanagement.config.local.js:2:  tfgridUrl: "https://explorer.testnet.grid.tf/tfgrid/directory/actors"
- jumpscaleX_threebot/ThreeBotPackages/threebot/capacity/html/config/capacity.config.local.js:2:  tfApiUrl: "https://explorer.testnet.grid.tf/tfgrid/directory/actors"
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/backup_explorer/sync2local.py:12:cl = j.clients.ssh.get("explorer", addr="explorer.testnet.grid.tf")
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/threebot_provisioning/chatflows/threebot_deploy.py:19:    explorer = j.clients.gedis.get(name="explorer", port=8901, host="explorer.testnet.grid.tf")
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/provision_examples/multi_nodes.py:30:    j.clients.threebot.explorer_addr_set("explorer.testnet.grid.tf")
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/provision_examples/zdb.py:28:    j.clients.threebot.explorer_addr_set("explorer.testnet.grid.tf")
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/provision_examples/k8s_cluster.py:46:    j.clients.threebot.explorer_addr_set("explorer.testnet.grid.tf")
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/provision_examples/ubuntu_ssh_corex.py:31:    j.clients.threebot.explorer_addr_set("explorer.testnet.grid.tf")
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/provision_examples/ubuntu_ssh.py:31:    j.clients.threebot.explorer_addr_set("explorer.testnet.grid.tf")
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/directory/package.py:5:DOMAIN = "explorer.testnet.grid.tf"
- jumpscaleX_threebot/ThreeBotPackages/tfgrid/directory/frontend/config.js:2:  tfApiUrl: 'https://explorer.testnet.grid.tf/tfgrid/directory/actors/'
- compiled directory frontend
- jumpscaleX_weblibs/static/gedis/gedis_http.js:57:const tfGridGedisClient = new GedisHTTPClient(`https://explorer.testnet.grid.tf/gedis/http`)

- jumpscaleX_core/install/InstallTools.py:3545:            config["EXPLORER_ADDR"] = "explorer.testnet.grid.tf"

- jumpscale_weblibs/static/gedis/gedis_http.js:57:const tfGridGedisClient = new GedisHTTPClient(`https://explorer.testnet.grid.tf/gedis/http`)

**Comment by grimpy** [comment]
Does farmanagement cope with a change today?

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/threebot/farmmanagement/actors/farm_management.py#L6

answering my own question since it's using the default client it should switch automaticly

**Comment by Pishoy** [comment]
verifed as below 
```
JSX> j.clients.explorer.default_addr_set("explorer.grid.tf") 

JSX> j.me.configure() 
JSX> j.me.tfgrid_phonebook_register()

```
 - jsx version 
```
root@test105_testnet:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git log -1
commit 35454a9d7800eb7dd478a12c2820d383eb83ad9c (HEAD -> development, origin/development, origin/HEAD)
Author: Jo De Boeck <deboeck.jo@gmail.com>
Date:   Mon May 18 18:28:00 2020 +0200

    fix passing of hru instead of mru in flist deploy
    
    See: #709
    
    Signed-off-by: Jo De Boeck <deboeck.jo@gmail.com>

```
