### ISSUE TITLE
BCDB import erases data from same namespaces

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#588]
There is a call to `resert` in the import method of the BCDB model:  https://github.com/threefoldtech/jumpscaleX_core/blob/9e9d7255486433435905e03429f82383229757fe/JumpscaleCore/data/bcdb/BCDB.py#L265

Normally this should be ok, cause you want a clean 0-db before importing.
The problem comes when you try to import a full export because the code does a listing of all the exported directory and then recursively call import with the path of the directory:
https://github.com/threefoldtech/jumpscaleX_core/blob/9e9d7255486433435905e03429f82383229757fe/JumpscaleCore/data/bcdb/BCDBFactory.py#L371-L393

If there are 2 model using the same 0-db namespace, everytime we do an import it will call the resert method which will delete all the data that has already been imported...
So you endup with only the last exported model available, and all the rest of the data is just gone

**Comment by rkhamis** [comment]
This should be verified on `master` and `development`

**Comment by RafyAmgadBenjamin** [comment]
### Fixing import and export 
#### commits:
* https://github.com/threefoldtech/jumpscaleX_threebot/pull/417/commits/850c377a6c1eba10313bd19a19249754b4d8cc92

* https://github.com/threefoldtech/jumpscaleX_core/pull/604/commits/16af942cee9359828e39c26ab4523b2e1326cf5f

* https://github.com/threefoldtech/jumpscaleX_core/pull/604/commits/705134fa27a51faa78500e4ba7e4457a1b3961e2
#### PR:
* https://github.com/threefoldtech/jumpscaleX_threebot/pull/417
* https://github.com/threefoldtech/jumpscaleX_core/pull/604

**Comment by Dina-Abd-Elrahman** [comment]
- verified
