### ISSUE TITLE
Import export Error

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#596]
## How to reproduce

- Start 3bot server
- create some nodes

- do an export
```
j.data.bcdb.export()
```

- close threebot server

- do an import
example:
```
 j.data.bcdb.import_(path="/sandbox/var/bcdb_exports/10_Mar_2020_14_16_33") 
```

after @zaibon  suggested adding 
https://github.com/threefoldtech/jumpscaleX_core/blob/9bada8d884a4e07f2118e91f89d4a9ced0c7f713/JumpscaleCore/data/bcdb/BCDB.py#L566

you will get the following error 
![Screenshot from 2020-03-10 16-30-45](https://user-images.githubusercontent.com/10658229/76324037-27576980-62ee-11ea-9c72-3a4b0706b30d.png)

**Comment by rkhamis** [comment]
This breaks the storclient interface, the fix done in this commit needs to be refactored to keep all the storclients consistent with the interface:


https://github.com/threefoldtech/jumpscaleX_core/commit/e8ca3d939aa98472300afdcd482e48d8fe38f442

**Comment by zaibon** [comment]
Where is the storclient interface defined ?

**Comment by RafyAmgadBenjamin** [comment]
Fixed:
commits:
cad68ae7c52ee4f54965453238bebef36c80f76c
https://github.com/threefoldtech/jumpscaleX_threebot/commit/60793aceabe356725408f38048fe8ead7abfb9d6

* storeclient related to zdb. 
* validate that the schema is saved with it's the latest state before exporting.
* bug in the name of function ```threebot_zdb_sonic_start``` to be  ```start_servers_threebot_zdb_sonic```.

**Comment by Dina-Abd-Elrahman** [comment]
Verified on unstable branch.

** Scenarios 1 **  ```export and import database```

** Scenarios 2 **  ```change in bcdb and export then import```

## Verification steps:

### Scenarios 1

- Start 3bot server ```j.servers.threebot.start(background=True)```

- Export bcdb ```j.data.bcdb.export()```

- close threebot server

- Import bcdb ```j.data.bcdb.import_(path="/sandbox/var/bcdb_exports/15_Mar_2020_09_28_07/")```


### Scenarios 2

- Start 3bot server ```j.servers.threebot.start(background=True)```

- Add package
 ```gedis = j.clients.gedis.get("pm", port=8901, package_name="zerobot.packagemanager")```
```gedis.actors.package_manager.package_add(path="/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid/registrygeneric")```

- do an export
```j.data.bcdb.export()```

- close threebot server

- Import bcdb ```j.data.bcdb.import_(path="/sandbox/var/bcdb_exports/15_Mar_2020_09_38_07/")```

- check the existence of data 
``` j.data.bcdb.instances.registry.get_all() ```
