### ISSUE TITLE
Threebot server fails after unsuccessful shutdown [development_threebotstart]

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#600]
## How to reproduce

- start 3bot server
- kill it using pkill or any ungraceful way
- try to start again

![Screenshot from 2020-03-11 15-20-58](https://user-images.githubusercontent.com/10658229/76421351-37358300-63ac-11ea-99e4-cccd3c410c5e.png)

the problem here is 3bot server sets a key in redis called `"threebot.starting"`
but if this key is not well cleaned it will cause the server to stuck in loading

**Comment by zaibon** [comment]
The key added in redis has a timeout. So it will eventually go away.

**Comment by waleedhammam** [comment]
@zaibon I see the redis key timeout is set to 120 sec, we only wait for 75 sec so we at least we should make them match,no ?

**Comment by xmonader** [comment]
`-m` flag when you start kosmos to overcome that.

**Comment by waleedhammam** [comment]
@xmonader the same with me, still have to wait a 120 seconds

![Screenshot from 2020-03-12 10-00-03](https://user-images.githubusercontent.com/10658229/76499997-71ecf900-6448-11ea-924f-e4b4455c2d94.png)

**Comment by waleedhammam** [comment]
Also if the master process died..

we will get an error during retrieving the data cause bcdb redis server dead.
it could be in myjobs, .. etc

![Screenshot from 2020-03-12 13-34-14](https://user-images.githubusercontent.com/10658229/76517601-437e1680-6466-11ea-953d-ecef2f011df0.png)

**Comment by waleedhammam** [comment]
well it turns out the problem only happens when background=True

![Screenshot from 2020-03-12 15-07-21](https://user-images.githubusercontent.com/10658229/76530897-0d985c80-647d-11ea-92d2-506818b4a73e.png)

When we try to start 3bot server again when the key is still in redis, it thinks that the server is still running, so configmanager : startupcmds  uses bcdb model client where bcdb redis socket is not up so leads to fail.

so suggesting running bcdb socket at early stage, and before each bcdb usage we check it's up to determine master state or not

- Still investigating

**Comment by waleedhammam** [comment]
PR at: https://github.com/threefoldtech/jumpscaleX_core/pull/609

**Comment by john-kheir** [comment]
Verified
