### ISSUE TITLE
update documentation about packages regarding name [development_packagedocs]

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscaleX_core#615]
https://github.com/threefoldtech/jumpscaleX_core/commit/cfff3e1efcb1b54f0753887eb9c2a14a5bbe6903#diff-6233ec1dfe92461373f9eabb5027657d

**Comment by waleedhammam** [comment]
done at: https://github.com/threefoldtech/jumpscaleX_core/pull/616/files, https://github.com/threefoldtech/jumpscaleX_threebot/pull/433/files

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
