### ISSUE TITLE
openresty log locations

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscaleX_core#619]
openresty access and error logs are now stored in `/sandbox/cfg/nginx/default_openresty_threebot/logs`.
Why is this in the cfg folder and not in `/sandbox/var/log\logs` ?

**Comment by hossnys** [comment]
verified on branch development :

![Screenshot from 2020-03-18 23-53-12](https://user-images.githubusercontent.com/26298009/77011372-659afb80-6974-11ea-9473-1555714b7ffc.png)


![Screenshot from 2020-03-19 00-02-18](https://user-images.githubusercontent.com/26298009/77041466-a457a280-69c2-11ea-9d80-eab2cddd624e.png)

**Comment by robvanmieghem** [comment]
nice, when did this change?

**Comment by xmonader** [comment]
> nice, when did this change?

Was fixed in https://github.com/threefoldtech/jumpscaleX_core/pull/631/files :)
