### ISSUE TITLE
syncer monitoring is broken

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#620]
more info to be added.

**Comment by ashraffouda** [comment]
it is working on ubuntu, need to check for OSX

**Comment by ashraffouda** [comment]
Tested on OSX, and it works fine

**Comment by Dina-Abd-Elrahman** [comment]
- Tested on ubuntu and it working fine.

**Comment by Dina-Abd-Elrahman** [comment]
- tested on OSX and it's working fine.
