### ISSUE TITLE
test basebuilder & threebotbuilder & check install over docker [unstable]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#622]
- [x] fix/test the builders
    - push them under threefoldtech/base2 threefoldtech/3bot2 to docker hub so others can use
- [x] check the docker based installs: jsx container-install
- [x] see that the threefold simulator comes up as notebook
- [ ] see that wireguard comes up on OSX
- [x] run core tests: '''j.tools.basetester.coretest()''" should be ok

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
