### ISSUE TITLE
Issue related to Creating instance [unstable_bcdb_tests]

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#624]
The first instance is created with a default name regardless of the name I have given, the second instance is created with the right name , this issue on ```unstable branch```
![image](https://user-images.githubusercontent.com/46320202/76950764-3902c780-6913-11ea-83ce-047022f07370.png)
![image](https://user-images.githubusercontent.com/46320202/76950775-3f913f00-6913-11ea-9719-6629bea366e0.png)

**Comment by RafyAmgadBenjamin** [comment]
Fixed on ```unstable_bcdb_tests```
![image](https://user-images.githubusercontent.com/46320202/76966135-26e25280-692e-11ea-982f-8b2a5e43409e.png)

![image](https://user-images.githubusercontent.com/46320202/76966165-3366ab00-692e-11ea-88f1-481bf6770e47.png)

![image](https://user-images.githubusercontent.com/46320202/76966193-424d5d80-692e-11ea-855a-871979189551.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified
