### ISSUE TITLE
3bot local_start_explorer doesn't work on unstable

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#636]
![Screenshot from 2020-03-19 13-44-32](https://user-images.githubusercontent.com/10658229/77065124-628e2280-69e9-11ea-8bb2-5ddabd808e1e.png)

**Comment by xmonader** [comment]
Not an issue anymore, explorer deployed on testnet, and production, planbee package doesn't exist.

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/jumpscaleX_core/commit/e18745e2828623504acdc8b5181735a10657d4a5
