### ISSUE TITLE
the installation from unstable is broken

### ISSUE THREAD

**Issue by ahelsayd** [threefoldtech/jumpscaleX_core#638]
```
curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX_core/unstable/install/jsx.py?$RANDOM > /tmp/jsx
chmod +x /tmp/jsx
/tmp/jsx container-install
```
![image](https://user-images.githubusercontent.com/24386820/77073311-bef83e80-69f7-11ea-85e4-9037a368de28.png)

**Comment by Pishoy** [comment]
got this error while installing in ubuntu 18.04.44
![image](https://user-images.githubusercontent.com/21987477/77247516-adeb3f80-6c3a-11ea-8384-f38897d48a9c.png)

**Comment by Pishoy** [comment]
verified
