### ISSUE TITLE
container-shell is broken on unstable

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_core#639]
![screen](https://user-images.githubusercontent.com/8425762/77076595-b48c7380-69fc-11ea-960e-682cc97f52bd.jpg)

**Comment by hossnys** [comment]
verified on branch unstable :
/tmp/jsx container-shell is working fine now 

![Screenshot from 2020-03-22 110-09-29](https://user-images.githubusercontent.com/26298009/77245309-43300900-6c26-11ea-9e1d-eb918833dc98.png)
