### ISSUE TITLE
disk I/O error

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#640]
![image](https://user-images.githubusercontent.com/46320202/77244525-49ba8280-6c1e-11ea-90d2-e2b4edca89ad.png)

![image](https://user-images.githubusercontent.com/46320202/77244528-5048fa00-6c1e-11ea-93ef-4dabe3404803.png)

**Comment by RafyAmgadBenjamin** [comment]
Fixed on ```unstable_bcdb_tests```
commit d59822974bafcfac35f8cdeb3b9c0f20693acb2c

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
