### ISSUE TITLE
jsx installation enhancment unstable branch 

### ISSUE THREAD

**Issue by Pishoy** [threefoldtech/jumpscaleX_core#641]
can we enhance below step to be non-interactive while install jsx

![image](https://user-images.githubusercontent.com/21987477/77247644-b132fb00-6c3b-11ea-87d5-8b6fbff83020.png)

**Comment by waleedhammam** [comment]
This happens because it clones with ssh in interactive mode

Suggested options:

- use -s and non-interactive mode
- Add github to local know hosts (could be tricky if remote changes)
- Disable SSH host key checking For github in installtools

**Comment by Pishoy** [comment]
verified 
```
/tmp/jsx container-install -s
```
