### ISSUE TITLE
BCDB reset is not working 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#645]
![image](https://user-images.githubusercontent.com/46320202/77252602-8b1e5280-6c5d-11ea-8a05-cc6911cc5b62.png)

**Comment by alichaddad** [comment]
Fixed [here](a1d02edb97ae66398871ba2d28e0f1ff2432ac7d)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
