### ISSUE TITLE
3bot takes too long to start after container-install

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#648]
takes too long to start because of installing too many dependencies after container-install

**Comment by rkhamis** [comment]
part of https://github.com/threefoldtech/home/issues/585

**Comment by ahelsayd** [comment]
commit https://github.com/threefoldtech/jumpscaleX_core/commit/e53449c568485bf2559b869ee3de4946ade52dad

**Comment by ahelsayd** [comment]
blocked on this https://github.com/threefoldtech/home/issues/585
part of the problem is image threefoldtech/3bot2 was not build correctly and i need to build it again using the ```container builder``` command which is broken and should be fixed by the above issue

**Comment by rkhamis** [comment]
Fixed by kristof
