### ISSUE TITLE
openresty auto ssl: failback to default cert for local hosts [unstable_ssl]

### ISSUE THREAD

**Issue by abom** [threefoldtech/jumpscaleX_core#650]
Use failback certs with localhost (it always tries to get certs and takes too much time).

Maybe create an issue or a PR at https://github.com/auto-ssl/lua-resty-auto-ssl.

**Comment by abom** [comment]
According to this issue https://github.com/auto-ssl/lua-resty-auto-ssl/issues/26, we need to use `allow_domain` configuration.

**Comment by abom** [comment]
Added at https://github.com/threefoldtech/jumpscaleX_core/pull/661/commits/53b5aad6409e6e1ef836b7a301bc1a794b6a8bbf.

Now `localhost` and domains with `.test` should be filtered.

**Comment by hossnys** [comment]
verified on branch unstable
- add this line to /etc/hosts 
 ```172.17.0.2  3bot.test ```
- then open this link and watch lapis logs to see if any requests for ssl cert will happen or no .

![Screenshot from 2020-03-25 10-27-13](https://user-images.githubusercontent.com/26298009/77516780-a10d5c80-6e83-11ea-8186-d5d22c812c5d.png)
