### ISSUE TITLE
optionally allow 3bot connect for jsx environment [unstable_jsxcontainer]

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_core#652]
3bot login can be enabled/disabled on the jsx env

- [x] allow setting a flag when starting container to enable/disable 3bot login or not. (can be tracked in myenv)
~- [ ] configure $home_url in myenv to be used for callbacks e.g 3bot authentication -should be automatically configured in container-install)~ fixed with nginx configs no need for extra thing

**Comment by waleedhammam** [comment]
PR at: https://github.com/threefoldtech/jumpscaleX_core/pull/653/files
Docs and how to use at: https://github.com/threefoldtech/jumpscaleX_threebot/commit/70950dd6d61cc8301ace5c59a9fe1b2d6c8cd4e1

doc file: https://github.com/threefoldtech/jumpscaleX_threebot/blob/70950dd6d61cc8301ace5c59a9fe1b2d6c8cd4e1/docs/locations.md#threebot-connect

**Comment by Pishoy** [comment]
- `j.tools.threebot.enable_threebotconnect(False)`  verified 
- checking 3bot connect enabling with package location
