### ISSUE TITLE
failed to start threebotserver

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#655]
When doing:

`j.servers.threebot.default.start()`
![image](https://user-images.githubusercontent.com/143869/77313917-608bd280-6d0d-11ea-9b26-daeedaa7c1f2.png)

Branch: unstable

**Comment by grimpy** [comment]
Original error can be reproduced by executing
`j.tools.threebot_packages.delete()`

and start 3botserver afterwards

**Comment by abom** [comment]
Verified here, this fix  by @grimpy is working.

**Comment by hossnys** [comment]
verified on branch unstable :
![Screenshot from 2020-03-23 15-57-42](https://user-images.githubusercontent.com/26298009/77324147-03008180-6d1f-11ea-962c-734849eaea3c.png)
