### ISSUE TITLE
install choice is not remembered

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscaleX_core#66]
(branch development, commit 664469b)

```
Is it ok to continue with SSH-Agent, are you sure?
It's recommended to have a SSH key as used on github loaded in your ssh-agent
If the SSH key is not found, repositories will be cloned using https

if you never used an ssh-agent or github, just say "y"
```

This question is asked in the beginning of the process started by executing `/tmp/jsx container-install` and also asked later in the process when installing InstallTools. There is no reason from a user perspective to ask this again.

**Comment by serboctor** [comment]
The second question is asked actually in a silent context, so it's fixed by fixing the `-s` in this issue https://github.com/threefoldtech/jumpscaleX_core/issues/53

**Comment by hossnys** [comment]
verified  , no more questions asked when add -s option in container install
