### ISSUE TITLE
Make sure localhost:7000 works after jsx threebot on mac

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#665]
- Mac needs wireguard to link the docker container with localhost, make sure localhost:7000  is working and exposed correctly after installation

**Comment by waleedhammam** [comment]
Apparently fixed for a fresh new installation

![Screenshot from 2020-03-26 17-04-41](https://user-images.githubusercontent.com/10658229/77662022-034d8680-6f84-11ea-8807-710997b4d736.png)

in installation it sets the wg configs
![Screenshot from 2020-03-26 16-51-26](https://user-images.githubusercontent.com/10658229/77662059-106a7580-6f84-11ea-8151-3f9073373db7.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
