### ISSUE TITLE
Securing the keys / secrets that are created in your SDK environment

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#667]
Installed the jumpscale / 3bot environment
```
/tmp/jsx container-install
```
Then when done 
```
3bot start
````

3bot.connect login screen
login using 3bot.connect
error (needs to be http / not https)

If I remove the s in the URL - get back tot he 3bot login screen.

**Comment by gmachtel** [comment]
Integrated now in identity and sdk.
