### ISSUE TITLE
monitor not working

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#668]
![image](https://user-images.githubusercontent.com/6021844/77819008-c8f4fe00-70d7-11ea-893a-02e918527fde.png)

made minimal set not to run out of descriptors but did not see changes

super annoying for remote work

**Comment by ashraffouda** [comment]
I tested it every thing is up to date on unstable and works file 
![Screenshot from 2020-03-31 15-22-00](https://user-images.githubusercontent.com/1689456/78031183-7b8cc100-7363-11ea-8ca0-414cbf7f7865.png)

**Comment by ashraffouda** [comment]
![Screenshot from 2020-03-31 15-24-49](https://user-images.githubusercontent.com/1689456/78031408-cd354b80-7363-11ea-9279-75bcc78b4a73.png)

**Comment by ashraffouda** [comment]
```
t = j.clients.ssh.get("client")
t.addr = "<remote machine ip>" 
j.tools.syncer.get("client") 
j.tools.syncer.client.sshclients_add(t)
j.tools.syncer.client.sync(minimal=False) 
```

**Comment by john-kheir** [comment]
There might be some problem on an old installation 
but it works just fine  on a new installation
