### ISSUE TITLE
final install (container) install instruction is incorrect

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscaleX_core#67]
(branch development, commit 664469b)

```
        install succesfull:

        # if you use a container do:
        jsx container-kosmos

        or

        kosmos
```

This is the final information you get after a successful (🎉) installation, started by executing `/tmp/jsx container-install`.

That command lives however, as indicated by how I started the installation process (and as noted in the documentation), under the `/tmp` folder which is not in my `PATH` (is it in anyone's `PATH`???). So I would say either move it to a default _usr_ bin location or modify the installation instruction to the location that started the installation process in the first place.

**Comment by serboctor** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/b8c9cc341779ee18978535a8812bfc680afb4d2c
