### ISSUE TITLE
work with a real object for alert handler

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#674]
work with a real object for alert handler

```
# TODO: create Alert object which has the schema (config base class)
# make sure there is a nice __str__ method which shows logs, message in color
# make sure there is a delete
```
see

- /sandbox/code/github/threefoldtech/jumpscaleX_core/JumpscaleCore/tools/alerthandler/Alert.py

**Comment by dmahmouali** [comment]
https://github.com/threefoldtech/jumpscaleX_core/blob/development/JumpscaleCore/tools/alerthandler/RedisAlertHandler.py
