### ISSUE TITLE
can not delete specific schema using delete function 

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/jumpscaleX_core#679]
![image](https://user-images.githubusercontent.com/46320202/77848924-4a2bbe00-71c8-11ea-8e87-15ef08ea96d2.png)

**Comment by m-motawea** [comment]
implemented in PR: https://github.com/threefoldtech/jumpscaleX_core/pull/865
but parameter is `url` instead of `name`

**Comment by Pishoy** [comment]
verified
