### ISSUE TITLE
Couldn't insert object unique constraint failed (bcdbconfigs baseclass)

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#681]
## How to reproduce

- revert this commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/098c78e9b39fe892a698e092d27ee88c6a0fc7a9

- start 3bot server, exit and start again you will find the following issue with baseclasses configs

- or get instance `client = j.clients.oauth_proxy.get("main")` after you start the server you'll notice it passes the name `default` not `main`

![Screenshot from 2020-03-29 16-04-54](https://user-images.githubusercontent.com/10658229/77851081-1efc9b00-71d7-11ea-8f1a-7254ec25c31b.png)

- This was covered before in oauth2 package which not used anymore when we deleted it the error appeared

**Comment by despiegk** [comment]
resolved on unstable
