### ISSUE TITLE
package add works in second run despite errors

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#683]
how to reproduce

- start 3bot server
- add a malfunctioned package. this will fail
- add it again. this will install the package (change its state to installed)

**Comment by m-motawea** [comment]
fixed on branch https://github.com/threefoldtech/jumpscaleX_core/tree/development_fixPackageAdd commit https://github.com/threefoldtech/jumpscaleX_core/pull/686/commits/4e9c7011301eadeff3c2746e963803f15621c682

**Comment by john-kheir** [comment]
Verified
