### ISSUE TITLE
jsx install on ubuntu breaks: container does not have jsx script in /tmp

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#687]
In the install process there is:
```
+ ssh -oStrictHostKeyChecking=no -t root@localhost -A -p 9000 bash -e /tmp/script_3bot.sh
```

Which executes in the container.
```
3BOTDEVEL:3bot:tmp: ls -asl
total 16
4 drwxrwxrwx 1 root root 4096 Mar 30 09:28 .
4 drwxr-xr-x 1 root root 4096 Mar 30 09:27 ..
4 -rw-r--r-- 1 root root  585 Mar 29 05:32 script_3botdev.sh
4 -rw-r--r-- 1 root root   78 Mar 30 09:28 script_3bot.sh
3BOTDEVEL:3bot:tmp: more script_3bot.sh 
set -e

cd /tmp
python3 jsx configure --sshkey id_rsa -s
python3 jsx install 
3BOTDEVEL:3bot:tmp: 
```
In the container there is no jsx python script in /tmp

**Comment by weynandkuijpers** [comment]
When you execute the install script again `/tmp/jsx sdk` it does workand get;s through the whole install

**Comment by weynandkuijpers** [comment]
PS - It's the script from the unstable branch.

**Comment by xmonader** [comment]
For installation we curl into `/tmp/jsx`
```bash
curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX_core/development/install/jsx.py?$RANDOM > /tmp/jsx;
chmod +x /tmp/jsx;
```
it's up to the user to put into somewhere that's in his $PATH, e.g /usr/bin/jsx instead
if you do a restart your /tmp directory will lose `/tmp/jsx` file so that also might happen on restart and you will have to curl it again.

**Comment by rkhamis** [comment]
@weynandkuijpers `/tmp` is cleared everytime you restart your machine. that's it function. you either have to re-curl or put it elsewhere

**Comment by rkhamis** [comment]
oops. @xmonader just replied with same

**Comment by rkhamis** [comment]
Hope this answers your question. closing this issue

**Comment by xmonader** [comment]
I had a talk with @weynandkuijpers problem is in `sdk` command as it executes  this 
```
+ ssh -oStrictHostKeyChecking=no -t root@localhost -A -p 9000 bash -e /tmp/script_3bot.sh

``` 
in the container and script_3bot.sh assumes there's /tmp/jsx file in the container itself

**Comment by despiegk** [comment]
the jsx tool always upload automatically, if not then the issue is there

**Comment by m-motawea** [comment]
fixed upload of jsx & InstallTools.py commit: https://github.com/threefoldtech/jumpscaleX_core/commit/edbdd31217beef4409cf1fc71f926ba5c0cd753e

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
