### ISSUE TITLE
Revisiting docs

### ISSUE THREAD

**Issue by alichaddad** [threefoldtech/jumpscaleX_core#689]
The following docs need to be revisited/updated:
- [x] [builder.md](https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/howto/Create%20a%20new%20Builder.md) Fixed in 10.4
- [ ] [perftest.md](https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/howto/perftest.md)
- [x] [profile.md](https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/howto/profile.md) (Improve the docs not clear) Fixed in 10.4
- [x] [sandbox_python_zeroos_container.md] (https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/howto/sandbox_python_zeroos_container.md)  Fixed in 10.4
- [ ] [sandbox_python.md](https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/howto/sandbox_python.md)
- [ ] [Base classes docs](https://github.com/threefoldtech/jumpscaleX_core/tree/unstable/docs/Internals/baseclasses)
- [ ] [Base types docs](https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/Internals/basetypes/)
- [ ] [Gedis internal](https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/Internals/gedis/code_generation_objects_gedis.md)
- [x] [packages docs](https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/packages/)

**Comment by RafyAmgadBenjamin** [comment]
```package docs``` done
- I have unified the documentation  for packages in `jumpscale_theebot` repo and `jumpscale_core`
- add the missing parts in  `jumpscale_theebot` repo
- cleaned the `packages` documentation in `jumpscale_core` and made it refer to   `jumpscale_theebot`

### commits 
https://github.com/threefoldtech/jumpscaleX_core/commit/6f7a2bd8cd83c47446a7909b9cd989053ef55058
https://github.com/threefoldtech/jumpscaleX_core/commit/f651c9cebdd6738e81fcd6115b710437fadb84d7

https://github.com/threefoldtech/jumpscaleX_threebot/commit/af0eaf83f57c5d96486058625535be32b01dabf2
https://github.com/threefoldtech/jumpscaleX_threebot/commit/0828f485aeaaaabfacc34c728fa7c1f7cd30a5a7

**Comment by RafyAmgadBenjamin** [comment]
I have updated some stuff in the package thanks to @abom 
### commit
https://github.com/threefoldtech/jumpscaleX_threebot/commit/96d26f70fb8cce2ed56ca1ffe1a49c328740591a
