### ISSUE TITLE
SDK: Jupyter notebook does not work

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#691]
For communications and demonstration purposes we need to have the jupyter (notebook functionality up and running.

The new tokonomy was announced yesterday in a call to the community and we need to be able to demonstrate this.  Demonstration starts on the 1/4/2020 (no joke!)

The easiest way to have the jumpscale libraries available in the jupyter notebook is to make the jupyter notebook work in the SDK.

Currently when you install packages you get:
![image](https://user-images.githubusercontent.com/13766992/78002329-5a15e000-7337-11ea-860a-a5525c572e19.png)

**Comment by rkhamis** [comment]
should be fixed by https://github.com/threefoldtech/jumpscaleX_threebot/issues/490, but let's re-verify

**Comment by john-kheir** [comment]
should be working now 
![Screenshot from 2020-04-01 09-35-21](https://user-images.githubusercontent.com/15011431/78110985-3c5e7e80-73fc-11ea-9caf-334ec7ceac18.png)
