### ISSUE TITLE
Use executor in docker operations

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/jumpscaleX_core#693]
Make sure to use executor in InstallTools instead of scp in all jsx docker operations

**Comment by ahelsayd** [comment]
commit https://github.com/threefoldtech/jumpscaleX_core/commit/2f3873247e894e2505ef89e54563ee273f439100

**Comment by Pishoy** [comment]
verified 
```
curl https://raw.githubusercontent.com/threefoldtech/jumpscaleX_core/development/install/jsx.py?$RANDOM > /tmp/jsx;
chmod +x /tmp/jsx;
/tmp/jsx container-install
```
