### ISSUE TITLE
3bot container identities

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#698]
Finer control over your indentifies on your containers

`jsx container-install` will take a new optional argument `--identity` which will default to `default` this will create a docker volume mount on the host so that the same identity is reused in your containers (unless otherwise specified with the `--identity` option)

We will drop secret from `jumpscale_config.toml` and request entering at first launch of kosmos and store this inside redis

**Comment by grimpy** [comment]
Existing feature documentation:
https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/howto/docker_installer/share_identity.md

We will adapt this so that during installation by default we will copy our key to /sandbox/myhost/keys/<identity_name>/...

During install if no identity is passed but we do have a var/containers/shared/keys/<identify> we will use the existing one or ask if there are multiple.

**Comment by Pishoy** [comment]
verified
