### ISSUE TITLE
better bootstrap jsx alternative [unstable]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#702]
## aim

- 1 command jsx tool for anyone to start with grid sdk
- don't use click, use a nice shell directly with python

## implementation

- have 1 file packaged pyinstaller
- installtools file get's still downloaded & embedded on fly
- make sure required libs are in the package for the installtools to work
- don't use ipython, way too big
- ptpython is probably the way to go
- need to customize the experience: 
    - show doc strings
    - don't show _ methods & properties
    - be end user human friendly, not for developers !
    - auto completion
    - colors
- would be nice to have still debugger support

## requirements

- <30 MB size after packaging

## remarks

- see install dir, there is already 3sdk.spec file
    - to run ''' pyinstaller 3sdk.spec'''
- see first implementation in 3sdk in install folder of jumpscale
    - we prob need copy of the KosmosShell implementation for this usecase

**Comment by despiegk** [comment]
![image](https://user-images.githubusercontent.com/6021844/78468657-41803e00-771a-11ea-8860-ac5483b8fe07.png)

dont show the self.
end users don't need this

![image](https://user-images.githubusercontent.com/6021844/78468669-58269500-771a-11ea-8962-d250feab2b73.png)

needs to be case sensitive

on root only show the objects which have lower case e.g. d, j, ...

we want to have no overload for our users

**Comment by despiegk** [comment]
3sdk is starting point

**Comment by despiegk** [comment]
## basics for everyone

sdk start/stop/shell/kosmos. --delete --identity=...

## for experts

launch with flag: --expert

builder ...
container start/stop/export/import

**Comment by Dina-Abd-Elrahman** [comment]
- Verified.
