### ISSUE TITLE
seems issue in j.me

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#704]
![image](https://user-images.githubusercontent.com/6021844/78500820-fcc7c780-7758-11ea-85d9-c14653660bde.png)

these 2 keys should be different?
the verify key should be the one which is public and can go everwhere

check the j.myidentities.test()

**Comment by m-motawea** [comment]
fixed in commit: https://github.com/threefoldtech/jumpscaleX_core/commit/f4be728416645ba72320e1fe281e88d661ccb1da

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
