### ISSUE TITLE
Gaps in my understanding and questions that I need to understand (and cannot find documentation for)

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#708]
Open questions are:
1.  For now we install the jumpscale SDK local.  After installation there is a blank environment ready to take for a spin.  probably still working on it but how do you get you identity in the SDK.  What I do is:
```python
ipython
from Jumpscale import j
j.clients.explorer.default_addr_set('explorer.grid.tf')
j.tools.threebot_init_my_threebot()
<<answer questions>>
```
2. how do I get two accounts on this threebot - 
4. what are the two secret keys stored in the container - jumscale_confif.toml one and the /sandbox/cfg/keys.  Need to have a description that we can present with what they do and whatfor they are used.
5.  how do I bring in the 24 world seed to get access to my wallet (and i understand this will change with the stellar BD
6. how do I store and secure the secret key safely - I installed the container 50 times and lost the keys and I am sure that other external people will do the same. I need to describe the necessity to store there keys safely (next to the  24 see wallet).
7. this used to work fine - but no more - ID issue, or do I use the zosv2.0 sal lib wrong (specifically the node selection section):
```
# Load the zero-os sal and reate empty reservation method
zos = j.sal.zosv2
r = zos.reservation_create()

demo_ip_range="172.20.0.0/16"
demo_port=8030
demo_network_name="demo_network_name_01"

# create overlay network definition in datastructure called "network"
network = zos.network.create(r, ip_range=demo_ip_range, network_name=demo_network_name)

nodes_salzburg = zos.nodes_finder.nodes_search(farm_id=12775) # (IPv6 nodes)
nodes_vienna_1 = zos.nodes_finder.nodes_search(farm_id=82872) # (IPv6 nodes)
nodes_belgium = zos.nodes_finder.nodes_search(farm_id=1) # (IPv4 nodes, to be used as ingress/egress point.  These are not webgatewaysm, just nodes connected to the internet with IPv4 addresses)

# nodes_all = nodes_salzburg + nodes_vienna_1 + nodes_belgium + nodes_munich
nodes_all = nodes_salzburg[5:8] + nodes_vienna_1[5:8] + nodes_belgium[:2]

# make sure to set a new port
for i, node in enumerate(nodes_all):
    if zos.nodes_finder.filter_is_up(node):
        iprange = f"172.20.{i+10}.0/24"
        zos.network.add_node(network, node.node_id , iprange, wg_port=demo_port)
        print("Node number: ", i, node.node_id, ":", iprange)
    else:
        print("Node", node.node_id,"is not up")
```
8.  Need to describe the process of keeping the installed SDK up to spec. The jumpscale codebase is going to improve rapidly so what do I do on a daily base to make sure to keep up updated with a released - stable version and updates.  Is it a `pull` of a specific branch in `/sandbox/code/github/threefoldfoudnation`?  or something else.
9. We have to decide what the branch name is to go public with?
10. How do I stop and start the docker container on my local laptop.  Do I need to give / provide a `save` commend to store the current state of play in the container?
11.  What is the difference between the kosmos shell and ipython (with the `from Jumpscale import j` included).  Why should I use the kosmos shell?

**Comment by xmonader** [comment]
Q1 to Q7 all of the answers will be obsoleted when we merge the branch unstable_identity (should make life easier) and the flow will be exhaustively documented.

8- The user of the SDK should stick to a release "a tag" 10.4, 10.4.1, 10.5 .. etc never pulling code from a branch.

9- We go with master branch (on tag 10.4)

10- normally your state is stored within the configmanager (any objects you create in jumpscale) and save they will be available when you go to kosmos again

11- for kosmos and ipython I updated the documentation for kosmos https://github.com/threefoldtech/jumpscaleX_core/blob/4db77652430e2a27bd6cc00508ffe72d7c206ad3/docs/kosmos/shell.md#kosmos-vs-ipython 

so In python you basically don't get to work jumpscale world of objects because it's built on (tree hierarchy)

**Comment by xmonader** [comment]
for Questions 1-7 there's a decent doc covering everything now, including recovering with your words too.
https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/Identity.md#creating-multiple-identities

closing
