### ISSUE TITLE
build new container [unstable]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#709]
- use our jsx builder tools to build new container
- make sure following is in
    - mdbooks (can be apt install or rust build)
    - zola (see https://github.com/getzola/zola, build with rust)
- all on [unstable]
    - use syncer to sync to central server then build
- push the new container

**Comment by xmonader** [comment]
Moving to blocked because unstable_identity not ready yet.

**Comment by xmonader** [comment]
@despiegk pushed a new image already.
