### ISSUE TITLE
identity management blocks if you enter the wrong secret

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#716]
branch: unstable

I tried to follow the documentation how to configure the new identity manager : https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/Identity.md

![2020-04-10_1898x1085_scrot](https://user-images.githubusercontent.com/303164/78969815-322d3600-7b08-11ea-9efe-2905e1d36563.png)

So it seems I enter the wrong secret (which secret ? we don't know no information about it...)

I then retried to start kosmos with `jsx kosmos -n zaibon.3bot` but always get the same error directly. No chance to enter another secret.

**Comment by zaibon** [comment]
Even when entering kosmos normally and then trying `j.me.configure() ` save error 

![2020-04-10_1983x1112_scrot](https://user-images.githubusercontent.com/303164/78970100-d57e4b00-7b08-11ea-812e-4b38de350f23.png)

**Comment by xmonader** [comment]
that's not an issue anymore right? you delete `/sandbox/cfg/bcdb_config` already no?

**Comment by waleedhammam** [comment]
I've killed redis and used different secret and now gives different error

![Screenshot from 2020-04-11 10-18-22](https://user-images.githubusercontent.com/10658229/79038942-dd5bef00-7bdd-11ea-94ba-7eacc27e84f3.png)

**Comment by waleedhammam** [comment]
The key is now saved in redis, 
![Screenshot from 2020-04-11 10-21-35](https://user-images.githubusercontent.com/10658229/79038997-3f1c5900-7bde-11ea-8f0f-8e88e578acee.png)

key name is: "threebot.secret.encrypted"
should we implement something called identity reset to delete that key, or it's not in the flow ?

**Comment by waleedhammam** [comment]
updated the docs with secret  @ https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/docs/Identity.md

**Comment by waleedhammam** [comment]
If you entered a wrong secret just delete the key from redis 

```
3BOTDEVEL:3bot:~: redis-cli
127.0.0.1:6379> KEYS *
1) "threebot.secret.encrypted"
127.0.0.1:6379> del "threebot.secret.encrypted"
(integer) 1
127.0.0.1:6379> 

```

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
