### ISSUE TITLE
fix threebotserver start with multiple identites

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#717]
- configure 3bot
- start with j.servers.threebot.start()

you can pass identity as a parm if not it should take the default

you will find the following error

![Screenshot from 2020-04-11 17-19-24](https://user-images.githubusercontent.com/10658229/79047706-9d662d80-7c18-11ea-91cb-65d78efdfd4d.png)

**Comment by waleedhammam** [comment]
fixed in https://github.com/threefoldtech/jumpscaleX_core/commit/9fb4763725dd43460c0cdac63c8821d89b922566, https://github.com/threefoldtech/jumpscaleX_core/commit/86c142591b9349f4a76854c9136e68f7c889050d

works ok now

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
