### ISSUE TITLE
Identity threebot name is changed to lower case 

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/jumpscaleX_core#721]
https://github.com/threefoldtech/jumpscaleX_core/blob/3c6ca936a1ab5cd5a432e4f36e2a73a210c41e85/JumpscaleCore/me/Me.py#L38

If the threebot name contains both upper and lower case letters, the registration to the phonebook fails when the identity is already saved there because locally the name is lower cased.

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/79068261-ddcfb500-7cc5-11ea-81fd-a6fb099e4365.png)

**Comment by xmonader** [comment]
https://github.com/threefoldtech/zos/issues/706
