### ISSUE TITLE
Make 3sdk work on windows and package it [unstable_windows_support]

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#722]
Validate that 3sdk works on windows and package it

**Comment by waleedhammam** [comment]
- Current progress in installation.
it created the container, cloned the repos, created identity
- working executing the system env.

![image](https://user-images.githubusercontent.com/10658229/79135350-7f7f0100-7daf-11ea-9ef3-c1ebe34bd6e1.png)

**Comment by waleedhammam** [comment]
Almost getting it to work, still have an issue with interactive executor on windows.

![image](https://user-images.githubusercontent.com/10658229/79233881-b6b1e880-7e69-11ea-835f-fb596fe6652d.png)

![image](https://user-images.githubusercontent.com/10658229/79233910-c03b5080-7e69-11ea-8ef9-b788361d0b6d.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
