### ISSUE TITLE
simulator error

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#723]
![image](https://user-images.githubusercontent.com/6021844/79110578-0fef1e80-7d7b-11ea-933c-67153ab50db8.png)

can we do something about this error msg?

also is there a way to always open up the right tabs?
I believe there is a trick with a json file or something when starting the notebook

**Comment by xmonader** [comment]
should be fixed using 
```
3BOTDEVEL:3bot:~: jupyter serverextension enable --py jupyterlab_code_formatter
Enabling: jupyterlab_code_formatter
- Writing config: /root/.jupyter
    - Validating...
      jupyterlab_code_formatter  OK
```

**Comment by m-motawea** [comment]
fixed in commit: https://github.com/threefoldtech/jumpscaleX_libs/commit/bc73c31ebae44c87f9916bd1ba0b878e9eacbf93

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
