### ISSUE TITLE
provide a (long) in Jumpscale schema

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscaleX_core#726]
In Python an int can be of arbitrary size  but in capnp it needs to be defined and sometimes it does not suffice:
```
capnp/dynamic.c++:1694: failed: expected T(value) >= 0 && (unsigned long long)T(value) == value; Value out-of-range for
        requested type.; value = 4830549717811202
```

**Comment by m-motawea** [comment]
Added ```int64``` type in commit: https://github.com/threefoldtech/jumpscaleX_core/commit/90c35667ef835ad9d3546087a83fd351af4f5d35

![image](https://user-images.githubusercontent.com/32568986/79209163-54de8800-7e43-11ea-8e47-388689c6c39b.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
