### ISSUE TITLE
can't install jumpscale using package build 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/jumpscaleX_core#727]
following the docs here https://github.com/threefoldtech/jumpscaleX_core/blob/unstable/install/README.md#build , to install 3sdk ,and when try to build the package i got this error: 
![Screenshot from 2020-04-14 10-07-24](https://user-images.githubusercontent.com/26298009/79201324-2d35f280-7e38-11ea-9444-ec072ca02901.png)

**Comment by grimpy** [comment]
@hossnys are you sure the `locale` is setup correctly on this node?

**Comment by hossnys** [comment]
i retired again and it works successfully now , so going to close this issue.

![Screenshot from 2020-04-15 11-19-19](https://user-images.githubusercontent.com/26298009/79320875-c59ca780-7f0a-11ea-8e25-0284e65c5089.png)
