### ISSUE TITLE
save object twice with same name [development_bcdb_sqlite]

### ISSUE THREAD

**Issue by BolaNasr** [threefoldtech/jumpscaleX_core#73]
kosmos -p ``` j.data.bcdb.test()```

some where need update in storclient but it's add with same name and name should be unique and give me this error

![image](https://user-images.githubusercontent.com/10259267/64598616-554c0780-d3b8-11e9-87f6-52bb2a0c20d1.png)

**Comment by ahmedelsayed-93** [comment]
should be fixed by this commit
https://github.com/threefoldtech/jumpscaleX_core/commit/f64e437666141146b798c722f236ad0803bc9280
