### ISSUE TITLE
can't install jumpscale using released binary 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/jumpscaleX_core#730]
when installing jumpscale using this binary here https://github.com/threefoldtech/jumpscaleX_core/releases/download/v10.4-rc4/3sdk-linux-amd64 , i got this error on DO vm when do :

```container threebot```

![Screenshot from 2020-04-14 13-18-38](https://user-images.githubusercontent.com/26298009/79219453-99255480-7e52-11ea-8919-93446ef18705.png)

**Comment by rkhamis** [comment]
no longer an issue
