### ISSUE TITLE
3sdk handle exception better in none expert mode

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#731]
Only show error message no full stracktraces

**Comment by waleedhammam** [comment]
added at: https://github.com/threefoldtech/jumpscaleX_core/commit/458e1f4cd060ce2f00809f2d35173e94d36cabe1

example 
![Screenshot from 2020-04-27 11-39-21](https://user-images.githubusercontent.com/10658229/80358318-819b9200-887c-11ea-8451-a316dd7aa2cb.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
