### ISSUE TITLE
explicitly mention that words should be coming from 3bot connect app

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#734]
explicitly mention that words should be coming from 3bot connect app in everywhere that asks for words.

**Comment by ranatrk** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/358aa45298684ae69aa1a5262d571cb843c76461

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/79350609-f8a96000-7f37-11ea-8f65-6be0bd589424.png)
