### ISSUE TITLE
rebuild the image to include codeserver + zerotier client binaries 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#735]
- rebuild the image to include codeserver + zerotier client binaries

**Comment by BolaNasr** [comment]
i updated the image
 https://hub.docker.com/layers/threefoldtech/3bot2/latest/images/sha256-7b00d02077088dc710d06aa81961f5df507f49317e0e6a40df4fddc204999ec4?context=repo

added codeserver and zerotier-cli binaries

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
