### ISSUE TITLE
add exit option to the 3sdk install shell

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#740]
The 3sdk command-line tool doe not have an exit function.  The only way out is <cntrl>-D

Can we add an exit command?

**Comment by grimpy** [comment]
![image](https://user-images.githubusercontent.com/143869/79441662-d0713e00-7fd7-11ea-80e0-0d7144a55dc0.png)

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/4cd6cb25c7aa8894d1c3580828d544d088f8f10a

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
