### ISSUE TITLE
3sdk improvements for containers and builders

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#743]
- [x] implement wireguard command
- [x] base and sdk in builder
- [x] add zerotier option for simulator start
- [x] remove old commented code
- [x] implement host install

**Comment by m-motawea** [comment]
PR: https://github.com/threefoldtech/jumpscaleX_core/pull/760

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
