### ISSUE TITLE
couldn't container install identity="" email="" words=""

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#744]
Was trying container install from 3sdk

seems like words wasn't passed

![Screenshot from 2020-04-16 13-31-01](https://user-images.githubusercontent.com/10658229/79451275-95c2d200-7fe6-11ea-8cab-55a76aeb7d50.png)

I did `args words val="mywords"` the value was passed then

**Comment by m-motawea** [comment]
fixed in commit: https://github.com/threefoldtech/jumpscaleX_core/commit/7da53cfdc2948e980024bc7a6f3584bc645945f3

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
