### ISSUE TITLE
code quality: use python or jumpscale primitives

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#746]
![image](https://user-images.githubusercontent.com/6021844/79526038-a31ea180-8064-11ea-8f15-cb1f872bc033.png)

- executing bash to get something done in relation to file manipulation is not right

is in mdbook.py

the module is called mdbook but we are doing things for generating wiki's for packages, would have been more logical to have a sal for mdbook which is only mdbook specific then use that sal on packages tool lib, where we can generate from there.

**Comment by BolaNasr** [comment]
- changed all bash behavior to use ```j.sal.fs```
- create load_all function to load all books of packages loaded
    - ```j.tools.mdbook.load_all() ```
- create new class called ```Packgesdocs2mdbook``` to generate all mdbook needed from packages docs by 
     - ```j.tools.packgesdocs2mdbook.generate_index_book()```
     -  ``` j.tools.packgesdocs2mdbook.generate_summaries()```

![image](https://user-images.githubusercontent.com/10259267/80116031-c3c78980-8585-11ea-9f05-5861dd891c6e.png)
