### ISSUE TITLE
review the ask methods in 3sdk [development_install]

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#752]
Please review the flow for interaction and params passed to each command and make sure they are never overwritten.

It's very misleading and doesn't respect the passed parameters 
e.g

https://github.com/threefoldtech/jumpscaleX_core/blob/69bc7773180d02536791c3185408b79456d0d197/install/threesdk/lib/SDKContainers.py#L59

should be `identity = self._identity_ask(identity)` and self._identity_ask returns identity if passed or to be `identity = identity or self._identity_ask()`

https://github.com/threefoldtech/jumpscaleX_core/blob/69bc7773180d02536791c3185408b79456d0d197/install/threesdk/lib/SDKContainers.py#L11

**Comment by waleedhammam** [comment]
The flow seems OK,

if self.args.identity has something will return it, 
if not identity will ask
if identity will return it

![Screenshot from 2020-04-21 11-08-11](https://user-images.githubusercontent.com/10658229/79847729-69c99700-83c0-11ea-9600-4ff0f84ac70c.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
