### ISSUE TITLE
simulator error

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#754]
Cannot install simulator using this command `p.threefold.simulator.install()` from 3bot shell. 

![error](https://user-images.githubusercontent.com/21218053/79882246-94ccde80-83f2-11ea-8ea6-a61e0f7db62a.jpg)

![error](https://user-images.githubusercontent.com/21218053/79882356-bded6f00-83f2-11ea-8a38-57d91d33d0be.jpg)

Branch: `development`

**Comment by xmonader** [comment]
please add the package using packagemanager/package_add method. (this will create the locations for openresty)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
