### ISSUE TITLE
Can't install jsx using 3sdk (non-interactive)

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#755]
**branch:** development 
**commit:** c99a93e849f64e65ac91f393a5e3473d60386977

### Steps
`./3sdk container install testnr=1 identity=test`

### Result
Asking for secret, and can't pass it in the same line or in another line.

![image](https://user-images.githubusercontent.com/41957921/79887759-b1214900-83fb-11ea-9106-fa645a484711.png)

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/6e8455daeacb6a43e0028ce8c4863afe3c82ed98

**Comment by AhmedHanafy725** [comment]
**Verified** 
![image](https://user-images.githubusercontent.com/41957921/79893416-5809e300-8404-11ea-9693-8cf4b89de622.png)
