### ISSUE TITLE
jumpscale  10.4 release has no binary assets 

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#757]
Only have a source code asset here https://github.com/threefoldtech/jumpscaleX_core/releases

Writing the installation manual for jumpscale SDK we have always had the option to do "from source code" and "binary" install option.  Can we add the binaries or do we need to change the installation instructions?

**Comment by hteibler** [comment]
and in Documentation
https://github.com/threefoldtech/jumpscaleX_core/releases 
link does not exist!
https://github.com/orgs/threefoldtech/projects/68

**Comment by rkhamis** [comment]
yes, I was just going to add them. I released quite late.

**Comment by rkhamis** [comment]
all done! and the links works with me @hteibler
