### ISSUE TITLE
shell does not show errors any longer (try except) [development_stabilize]

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/jumpscaleX_core#76]
![image](https://user-images.githubusercontent.com/6021844/64635034-007faf80-d3ff-11e9-9b63-38834465e1ea.png)

when calling as kosmos script it works ok

![image](https://user-images.githubusercontent.com/6021844/64635096-260cb900-d3ff-11e9-92b9-aed24bddc013.png)

**Comment by despiegk** [comment]
call by 
```
 kosmos 'j.servers.threebot.get("default", executor="tmu")'
```

that one works ok

**Comment by despiegk** [comment]
has the newest code in for kosmos shell

**Comment by abom** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/ba9096761750c18b2a44996ec45dcc4aa588bcf5

**Comment by Dina-Abd-Elrahman** [comment]
- verified. 

![ff](https://user-images.githubusercontent.com/21218053/64921192-646bf480-d7c0-11e9-86cf-f6b298c13aa0.png)
