### ISSUE TITLE
container kosmos asks for identity words if there's multiple containers everytime

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/jumpscaleX_core#761]
![Screenshot from 2020-04-23 12-39-36](https://user-images.githubusercontent.com/10658229/80090265-86500580-855f-11ea-989d-84239019329e.png)

**Comment by waleedhammam** [comment]
pr at: https://github.com/threefoldtech/jumpscaleX_core/pull/764/files

**Comment by Pishoy** [comment]
verified 
![image](https://user-images.githubusercontent.com/21987477/80311338-675fa680-87df-11ea-9218-f58c5ae98c0d.png)

```
commit 932b50ba592e7b0151d7cd8137e32e90dbb2233f (HEAD -> development, origin/development, origin/HEAD)
Author: waleed <waleed.hammam@gmail.com>
Date:   Sun Apr 26 11:03:15 2020 +0200

    fix docker pull for windows
```
