### ISSUE TITLE
For new 3botconnect identity registrations require 2x input of 24 word seed

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#762]
I have made a lot of mistakes in the first time registration of a number of  3botconnect identities.  To make sure other people to not fall in the same trap (believing that they have entered the correct 24-word sequence and blaming the software for being buggy) maybe at first input ask twice for the 24-word seed input.

**Comment by grimpy** [comment]
I feel people will just copy paste it the 2nd time around so this would just be an annoyence instead.
@rkhamis what do you think?

**Comment by rkhamis** [comment]
I agree with @grimpy. they would just paste it, don't you think, @weynandkuijpers

**Comment by weynandkuijpers** [comment]
hmmmmm --okay - fair point. But then what would be a good strategy to no allows people to enter a typo. Can we do a check (hash?) that is also presented in the app on the phone (x digit code) that verifies the the words were entered correctly.

PS> tlaking / thinking about this only makes sense if going forward the "manual" entry of the 24 words is mandatory. If it it temporary (local SDK install) then pet's close the issue - not worth the effort.
