### ISSUE TITLE
502 Bad Gateway on SDK Examples page in threebot admin dashboard (v10.4)

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/jumpscaleX_core#767]
Reproduce steps:
1. Install Jumpscale SDK 10.4 https://github.com/threefoldtech/jumpscaleX_core/releases/tag/v10.4
2. Remove old threebot container
3. Launch new threebot container
4. Go to "SDK examples" page
5. Click "Install required packages" and wait until page refreshes
Result: "502 Bad Gateway" page
Expected Result: SDK Examples page.

**Comment by rkhamis** [comment]
already fixed in latest 
https://github.com/threefoldtech/jumpscaleX_core/issues/773
