### ISSUE TITLE
expose package_author from the ThreebotPackage

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/jumpscaleX_core#771]
Currently I can access the author package from an actor using`self.package._package_author`.
Exposing it as a `package_author` property would be a lot cleaner.

**Comment by dmahmouali** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_core/commit/651abe6bdb10f6b8a1dec097ef7019a0b7d5c492

- [x] exposed

**Comment by AhmedHanafy725** [comment]
**Verified**

by debugging in an actor, was able to get `package_author` from `self` directly.

![image](https://user-images.githubusercontent.com/41957921/80712071-ab112380-8af1-11ea-9d50-8777427009fc.png)
