### ISSUE TITLE
SDK examples show "502 Bad Gateway"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#773]
![image](https://user-images.githubusercontent.com/13766992/80302237-264c9f80-87a9-11ea-94cb-639b3889211a.png)

**Comment by waleedhammam** [comment]
fixed at: https://github.com/threefoldtech/jumpscaleX_libs/commit/41563d8c839e0c22186f147384225ae22cfeffcf

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
