### ISSUE TITLE
chatflow network deployment results in error

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#776]
- SDK installed with the latest binary for macOS
- SDK version: JSX Version: v10.5rc1-45-g753dcb54

```
The following error occured: {"error":"invalid account address: horizon error: \"Resource Missing\" - check horizon.Error.Problem for more information"}
```

![image](https://user-images.githubusercontent.com/13766992/80469670-2aabc080-8941-11ea-8e40-e006e05bd4e2.png)

Earlier today I also received a similar error message with included this "horizon error" message when someone was using the kosmos shell to create his farm.  He sent a screen shot:

![IMAGE 2020-04-28 11:15:02](https://user-images.githubusercontent.com/13766992/80469907-84ac8600-8941-11ea-8ad6-ce9cf0f94aa9.jpg)

The executed code was:
```
j.clients.explorer.default_addr_set('explorer.grid.tf')
explorer = j.clients.explorer.explorer
farm = explorer.farms.new()
farm.name = 'dec_hk_t1'
farm.threebot_id = j.me.tid
wallet_address = farm.wallet_addresses.new()
wallet_address.asset = 'TFT'
wallet_address.address = '0150e156f3650986ecbbf6013c3c7d81ada901d308d031a73fe1a482a07e11682e6f0cf2963913'
farm.email = 'colinonthemove@hotmail.com'
farm_id = explorer.farms.register(farm)
print(farm_id)
````
I have asked him to sent me the output of `j.me` but did not receive an answer.

**Comment by DylanVerstraete** [comment]
`wallet_address.address = '0150e156f3650986ecbbf6013c3c7d81ada901d308d031a73fe1a482a07e11682e6f0cf2963913'`

This is a tfchain address, we don't support that anymore. We are migrated to stellar now so this should be a valid stellar address.

**Comment by weynandkuijpers** [comment]
Okay - clear - we should have communicated that....  This is a farmer that had trouble over the last coupe of days getting 3sdk installed - now it's working and he cannot register - has to have a stellar wallet....  Okay - I'll let him know.
