### ISSUE TITLE
SDK installation improvement

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/jumpscaleX_core#781]
We have received feedback that a part of the user base is having issue when deploying the 3SDK containers.

Reported issues:
- the current installation does change branches silently. We want to change that and ask the user if he wants to change branch or not. 
  - he wants to change, and have clean repo => no problem
  - he wants to change, have dirty repo
    - he to keep his changes. we commit and pull ?
    - he doesn't want to keep his changes. we do a reset
  - he doesn't want to change => we do nothing but things can break. Need to warn he is on its own cause we have no way to know what change he has.

In all these flows, if at any point we detect a conflict. We stop. warn the user we cannot do anything and he needs to fix the conflict or reset code to a know version.

**Comment by waleedhammam** [comment]
PR at: https://github.com/threefoldtech/jumpscaleX_core/pull/787

Scenarios:
![image](https://user-images.githubusercontent.com/10658229/80612500-58296480-8a3c-11ea-975b-8f9d86d44af3.png)

Test a scenario
![Screenshot from 2020-04-29 17-07-04](https://user-images.githubusercontent.com/10658229/80612533-611a3600-8a3c-11ea-806a-f6715174e827.png)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
