### ISSUE TITLE
3sdk binary for windows has multiple issues

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/jumpscaleX_core#783]
Testing with  customer , 3sdk v10.5 and  faced these issues :

```container threebot``` : 

![image](https://user-images.githubusercontent.com/25789724/80598865-07653c00-8a3b-11ea-9d29-e82fcd98948d.png)
 
he already generated and added the keys but had to rename his keys in this format

after above step he had error to install Git , so we should put in docs to have it pre-installed or should install it:

![image](https://user-images.githubusercontent.com/25789724/80599310-c9b4e300-8a3b-11ea-8266-17a95ba8f28f.png)

After installing Git he got this : 

![image](https://user-images.githubusercontent.com/25789724/80599420-f36e0a00-8a3b-11ea-9eb8-12647d0b825c.png)

Also tried with ```container install``` : 

![image](https://user-images.githubusercontent.com/25789724/80599561-2f08d400-8a3c-11ea-9c9e-3bcb65bb9e37.png)

then tried deleting sandbox dir from his windows machine , deleted container and made ```container install``` , then got this, 

![image](https://user-images.githubusercontent.com/25789724/80599711-68d9da80-8a3c-11ea-9438-5bd3a581565d.png)

It says installed , but when tried to do container shell , it shows a blank screen.

**Comment by waleedhammam** [comment]
- As you mentioned

- First problem is no longer relevant in 10.5.1
- Second problem Added git as requirement to docs
- Third problem
- Fourth and fifth problem is because git is not properly configured because windows using clrf by default and we should use lf, check git configuring part for windows in docs

Updated docs at: https://github.com/threefoldtech/jumpscaleX_core/commit/a0595d107c6dbfa06ac2002c09a951d9625b5152

Docs at: https://github.com/threefoldtech/jumpscaleX_core/blob/development/docs/3sdk/3sdk_install.md

**Comment by siddiquagig** [comment]
I was previously testing it from the customers PC who had Windows 10 PRO Enterprise Edition.

Currently tried on Windows 10 Home PC and since Docker for Windows is only supported on 10 PRo or Enterprise versions  , i had to use the Docker toolbox :

![image](https://user-images.githubusercontent.com/25789724/80748365-de75a180-8b35-11ea-86ac-0a58096d389d.png)

So when 3SDK v10.5.1 is executed i get this : 

![image](https://user-images.githubusercontent.com/25789724/80749322-52fd1000-8b37-11ea-8027-82e429c2bcd0.png)

**Comment by waleedhammam** [comment]
> I was previously testing it from the customers PC who had Windows 10 PRO Enterprise Edition.
> 
> Currently tried on Windows 10 Home PC and since Docker for Windows is only supported on 10 PRo or Enterprise versions , i had to use the Docker toolbox :
> 
> ![image](https://user-images.githubusercontent.com/25789724/80748365-de75a180-8b35-11ea-86ac-0a58096d389d.png)
> 
> So when 3SDK v10.5.1 is executed i get this :
> 
> ![image](https://user-images.githubusercontent.com/25789724/80749322-52fd1000-8b37-11ea-8027-82e429c2bcd0.png)

yeah as you mentioned 
Only supported on docker for windows here: https://docs.docker.com/docker-for-windows/install/

**Comment by xmonader** [comment]
@siddiquagig you moved it from verification to blocked because you have Windows Home? that's not what blocked status is used for.

**Comment by waleedhammam** [comment]
@siddiquagig why in progress ? There's nothing can be done, docker on windows is only supported for pro or enterprise

**Comment by waleedhammam** [comment]
Updated docs at: https://github.com/threefoldtech/jumpscaleX_core/blob/development/docs/3sdk/3sdk_install.md#requirments-for-windows

for windows requirements we need to fulfill all of these

Windows 10 64-bit: Pro, Enterprise, or Education (Build 15063 or later).
Hyper-V and Containers Windows features must be enabled.
The following hardware prerequisites are required to - successfully run Client Hyper-V on Windows 10:
64 bit processor with Second Level Address Translation (SLAT)
4GB system RAM
BIOS-level hardware virtualization support must be enabled - in the BIOS settings
