### ISSUE TITLE
how to interact with bcdb running in docker container from macOS host

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscaleX_core#79]
On Linux it probably works by using the configured network bridge, on macOS this does not work however (https://docs.docker.com/docker-for-mac/networking/). The recommended way is to publish/forward your port but this wouldn't really help for ports not configured by the install script.

Would like to talk from my host machine to a redisdb server, as a bcdb connector, running in my 3bot connector on port 6380.

**Comment by zgorizzo69** [comment]
--host doesn't work on macos and -P option don't expose ports opened dynamically inside the container. 
The docker recommendation is to expose/publish ports. In the docker install we already expose ports like this by default 8010-8014:8000-8004.
We could modifiy the install script ( with a special argument option) to a larger portion of ports like 6100-8150:6000-8050 . It will be the responsability of the user to make sure they don't interfere with services running on their host

**Comment by GlenDC** [comment]
Apparently the way to do this is to use the wireguard support provided by JSX.

Going to close this as that answered my questions.
