### ISSUE TITLE
3sdk Windows issue : error when installing container

### ISSUE THREAD

**Issue by siddiquagig** [threefoldtech/jumpscaleX_core#794]
We have customer , who has issues with the v10.5.2 Windows binary.

OS : Windows 10 Pro Machine.

He has installed Docker Desktop , configured git bash accordingly and also started the ssh server and agent on his windows.

Then Generated a new key without a passphrase and added it.

Gets this error :

```
error: Could not load sshkey without passphrase (C:\Users\Gebhard Beck/.ssh/id_ecdsa)
```

![image](https://user-images.githubusercontent.com/25789724/80827511-26a7c900-8bf5-11ea-90cc-ac53508a5509.png)

![image](https://user-images.githubusercontent.com/25789724/80827832-64a4ed00-8bf5-11ea-910b-e58f04967f3d.png)

We also tried giving a passkey when generating a key but same error and also deleted all previous keys and made a new one.

Window version : 
![image](https://user-images.githubusercontent.com/25789724/80831662-4a224200-8bfc-11ea-8cd4-dc7b387162f2.png)

**Comment by waleedhammam** [comment]
> ![image](https://user-images.githubusercontent.com/25789724/80827511-26a7c900-8bf5-11ea-90cc-ac53508a5509.png)
> 

Sure you didn't create a passcode ? not even a space ?
I can see from here it asks about it ?

**Comment by siddiquagig** [comment]
@waleedhammam , We also tried giving a passkey when generating a key but same error and also deleted all previous keys and made a new one.

**Comment by waleedhammam** [comment]
Can you show me something like the screenshot above ?
And make sure to do ssh-add -D to unload all

**Comment by waleedhammam** [comment]
@siddiquagig Please check https://github.com/threefoldtech/jumpscaleX_core/blob/development/docs/3sdk/3sdk_windows.md

**Comment by siddiquagig** [comment]
Thanks @waleedhammam 

Tried again , with all things setup and configured.

But now am getting this when did ```container threebot```


![image](https://user-images.githubusercontent.com/25789724/80915543-fcc0e480-8d63-11ea-9677-f1d8f20c226b.png)


also git is configured from the cmd :

![image](https://user-images.githubusercontent.com/25789724/80915556-1d893a00-8d64-11ea-85e8-6fd6cd942241.png)


and previous container and sandbox dir was deleted too before doing ```container threebot``` again: 

![image](https://user-images.githubusercontent.com/25789724/80915575-3bef3580-8d64-11ea-9b6f-abc43285ea2f.png)

**Comment by waleedhammam** [comment]
@siddiquagig ssh issues is not relevant anymore, can you update with the latest please ?

**Comment by waleedhammam** [comment]
PR at: https://github.com/threefoldtech/jumpscaleX_core/pull/806/files

The problem was because windows doesn't have symbolic links. I couldn't reproduce on my machine because I had some external tools

Tested on vanilla windows @dmahmouali and worked OK

**Comment by siddiquagig** [comment]
Just tested with the latest sdk provided , but we still have the error , i could provide you with the machine access if you like 

![image](https://user-images.githubusercontent.com/25789724/81206457-32243700-8fdd-11ea-9acd-6a759fe60021.png)

**Comment by waleedhammam** [comment]
merged into development, please try again

**Comment by siddiquagig** [comment]
@waleedhammam thanks, it worked now

![image](https://user-images.githubusercontent.com/25789724/81210948-b37ec800-8fe3-11ea-9432-75cc3815e09e.png)
