### ISSUE TITLE
Remarks on the 3sdk install process

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/jumpscaleX_core#797]
General remarks coming from an installation of the 3sdk installation:
- [x] when you have started the 3sdk (with a version number  in the filename if you have downloaded it, without if you have compiled it) you should be able to see / query the version number.
- [x] what is the difference between `container start ....` and `container threebot .....`
- [x] If the container with the sdk is running and you connected to `https://localhost:4010` the left menu needs to get a scrollbar - if the window is too small it does not allow you to get to the bottom menu items.

**Comment by grimpy** [comment]
ill handle the versioning thing...

**Comment by AhmedSa-mir** [comment]
I'll handle the menubar scrolling

**Comment by AhmedSa-mir** [comment]
commit: https://github.com/threefoldtech/jumpscaleX_threebot/commit/068279169a0c1f8eb4b7258dbc6b45351c02f116

Fixed the menubar scrolling issue

**Comment by grimpy** [comment]
to answer "what is the difference between container start .... and container threebot ....."

The only diffrence was the way you pass parameters around, that being said I removed container threebot in favour of the new threeebot subcommand

**Comment by AhmedHanafy725** [comment]
**Verified**
1- Version is now on the latest release.

![image](https://user-images.githubusercontent.com/41957921/82209297-56e9aa00-990d-11ea-816a-8ee761e7a605.png)

2- There is no more `container threebot`, now `container` and `threebot` are to different commands.

![image](https://user-images.githubusercontent.com/41957921/82209708-0292fa00-990e-11ea-86e6-f975d998d0f1.png)

3- scrollbar on the sidebar, zoom in the browser to make sure that scrollbar will appear.

![image](https://user-images.githubusercontent.com/41957921/82210092-b09ea400-990e-11ea-9133-98143a326b35.png)
