### ISSUE TITLE
horizon error when trying to deploy in JSX

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/jumpscaleX_core#802]
I have FreeTFTs in the wallet
and I'm using Freefarm (1)

registered_reservation = zos.reservation_register(r, expiration)  ->

SX> registered_reservation = zos.reservation_register(r, expiration)                                                                                                          
Tue 05 12:35:48 s/explorer/errors.py -  23 - raise_for_status                   : EXCEPTION: 
    HTTPError('424 Client Error: invalid account address: horizon error: "Resource Missing" - check horizon.Error.Problem
        for more information for url: https://explorer.grid.tf/explorer/reservations')
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/JumpscaleLibs/sal/zosv2/ZOSv2.py in reservation_register
    123    return self._explorer.reservations.create(reservation)
/sandbox/lib/jumpscale/JumpscaleLibs/clients/explorer/reservations.py in create
    16    resp = self._session.post(self._base_url, json=reservation._ddict)
/usr/local/lib/python3.7/dist-packages/requests/sessions.py in post
    578    return self.request('POST', url, data=data, json=json, **kwargs)
/usr/local/lib/python3.7/dist-packages/requests/sessions.py in request
    530    resp = self.send(prep, **send_kwargs)
/usr/local/lib/python3.7/dist-packages/requests/sessions.py in send
    650    r = dispatch_hook('response', hooks, r, **kwargs)
/usr/local/lib/python3.7/dist-packages/requests/hooks.py in dispatch_hook
    31    _hook_data = hook(hook_data, **kwargs)
/sandbox/lib/jumpscale/JumpscaleLibs/clients/explorer/errors.py in raise_for_status
    23    raise HTTPError(http_error_msg, response=resp)
-----------------------------

Tue 05 12:35:48 s/explorer/errors.py -  23 - raise_for_status                   : EXCEPTION: 
    HTTPError('424 Client Error: invalid account address: horizon error: "Resource Missing" - check horizon.Error.Problem
        for more information for url: https://explorer.grid.tf/explorer/reservations')
--TRACEBACK------------------
<stdin> in <module>
    1    
/sandbox/lib/jumpscale/JumpscaleLibs/sal/zosv2/ZOSv2.py in reservation_register
    123    return self._explorer.reservations.create(reservation)
/sandbox/lib/jumpscale/JumpscaleLibs/clients/explorer/reservations.py in create
    16    resp = self._session.post(self._base_url, json=reservation._ddict)
/usr/local/lib/python3.7/dist-packages/requests/sessions.py in post
    578    return self.request('POST', url, data=data, json=json, **kwargs)
/usr/local/lib/python3.7/dist-packages/requests/sessions.py in request
    530    resp = self.send(prep, **send_kwargs)
/usr/local/lib/python3.7/dist-packages/requests/sessions.py in send
    650    r = dispatch_hook('response', hooks, r, **kwargs)
/usr/local/lib/python3.7/dist-packages/requests/hooks.py in dispatch_hook
    31    _hook_data = hook(hook_data, **kwargs)
/sandbox/lib/jumpscale/JumpscaleLibs/clients/explorer/errors.py in raise_for_status
    23    raise HTTPError(http_error_msg, response=resp)
-----------------------------

424 Client Error: invalid account address: horizon error: "Resource Missing" - check horizon.Error.Problem for more information for url: https://explorer.grid.tf/explorer/reservations
JSX>

**Comment by zaibon** [comment]
This error is cause the wallet address of one of the farm used in the reservation is not valid. This prevent the reservation to be paid so the explorer refuses it directly.

The error message has been improve to be more user friendly already: https://github.com/threefoldtech/tfexplorer/commit/09a28823f75877af64faa53dea793d197aa066f1
