### ISSUE TITLE
Starting Threebot Container Fails with Docker run error

### ISSUE THREAD

**Issue by gneumann333** [threefoldtech/jumpscaleX_core#816]
After following the instructions for installation i get this error:

_Which network would you like to register to?
make your choice (mainnet,testnet,devnet,none): mainnet
what is your threebot name (identity)?
guido_neumann
What is the email address associated with your identity?
guido_neumann@outlook.com
Copy the phrase from your 3bot Connect app here.
...
please provide secret (to locally encrypt your container):
please provide secret (to locally encrypt your container) (confirm):
 - SSH PORT ON: 9000
 - Docker machine gets created:_

**Error in executing docker run --name=3bot --hostname=3bot -d -p 9005-9009:8005-8009 -p 7000:80 -p 5000:8888 -p 4000:443 -p 9001:9001/udp -p 9000:22 --device=/dev/net/tun --cap-add=NET_ADMIN --cap-add=SYS_ADMIN --cap-add=DAC_OVERRIDE --cap-add=DAC_READ_SEARCH -v C:\Users\Gneum\sandbox\code:/sandbox/code -v C:\Users\Gneum\sandbox\myhost:/sandbox/myhost threefoldtech/3bot2 /sbin/my_init: Traceback:
Unable to find image 'threefoldtech/3bot2:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/threefoldtech/3bot2/manifests/latest: Get https://auth.docker.io/token?account=guidoneumann&scope=repository%3Athreefoldtech%2F3bot2%3Apull&service=registry.docker.io: unexpected EOF.
See 'docker run --help'.**

3sdk>

- In the Myhost Folder there is just the SSH key folder sofar
- Please update Prerequisites
- I assume i need the latest 3bot files locally?
- What File would i need?
- Woudnt i be better to pull them directly from github?

Best regards

Guido

**Comment by gneumann333** [comment]
I think we are quite close to get this working and i would be happy to trouble shoot this with one of your programmers in a zoom session if possible.

**Comment by BolaNasr** [comment]
Dear @gneumann333 ,
that shouldn't happen because  if you don't have image locally it will pull it automatically .
that's exactly happen  with me.

**Comment by Dina-Abd-Elrahman** [comment]
- cannot reproduce.
