### ISSUE TITLE
3sdk should have a requirements check

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/jumpscaleX_core#817]
to avoid having ugly errors like command not found git or docker or whatever we need to validate that all minimal requirements are met before running any commands and point to the docs how to install them.

- [ ] docker
- [ ] ssh  (the tools)
- [ ] git

Original error:

![image](https://user-images.githubusercontent.com/64129/81398711-0c587880-912a-11ea-8ab3-557d10350ca8.png)
should show a meaningful message like 'docker not found on the system please install docker first' with a link to the installation requirements maybe https://sdk.threefold.io/#/3sdk_install?id=requirements or something.

**Comment by Dina-Abd-Elrahman** [comment]
- verified
