### ISSUE TITLE
Make cloning via https less ugly

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#818]
This is most likely caused by try / except in a loop
https://github.com/threefoldtech/jumpscaleX_core/blob/development/install/threesdk/InstallTools.py#L4997

We should detect before going in the loop which of the 2 methods we want to use (git ls-remote could be used to check)

Make sure that in code_github_get we always use the url passed not rely on what is configured in .git/config url

![uglyclone](https://user-images.githubusercontent.com/143869/81412580-5baba280-9144-11ea-8c41-d5332b2e1bc2.jpg)

**Comment by grimpy** [comment]
```
The authenticity of host 'github.com (140.82.118.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? yes
```

This should now be asked

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
