### ISSUE TITLE
Minimize requirements for 3sdk

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#822]
- 3sdk std: no git, no ssh, only dexec on container
- 3sdk expert: what we have now
- hide container commands in none expert mode

In none expert mode we do not mount ~/sandbox in our containers
Git cloning should be done inside the container (in all cases)

We should not rely on ssh to access our container bud instead use docker exec (dexec inside installtools)

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
