### ISSUE TITLE
recheck 3sdk 3bot restart 

### ISSUE THREAD

**Issue by hteibler** [threefoldtech/jumpscaleX_core#835]
changing code in 
/sandbox/code/github/threefoldtech/jumpscaleX_threebot/ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/
doesn't show up in WEB UI

**Comment by rkhamis** [comment]
part of work on https://github.com/threefoldtech/jumpscaleX_threebot/issues/674
