### ISSUE TITLE
Failed to reset changes if no name is specified 

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/jumpscaleX_core#836]
during container install using:
 `container install identity=ayoubm.3bot email="dmahmouayoub@gmail.com" words="kingdom scrub volcano...." 
`

![image](https://user-images.githubusercontent.com/36021484/81692905-62e1f180-945f-11ea-9e52-b1fa022e5ed9.png)

**Comment by grimpy** [comment]
https://github.com/threefoldtech/jumpscaleX_core/commit/7341a478f2e607b6de5a3b82d66de84b34b051d4

**Comment by Pishoy** [comment]
verified in binary 3sdk_v10.5.3_linux_x86_64
