### ISSUE TITLE
Support for updates of 3sdk / containers

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#838]
Make it possible for users of 3sdk to know when there are updates available and allow them to upgrade by means of the 3sdk:

- [x] When issuing the `--version` or `version` command we will inform the user if there is a new version available.

- [x] An extra command `update` will be added to do an update (this will update all repos of all known containers) and update the 3sdk binary itself

- [x] In the admin panel a check will be added to inform the user about a new update

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
