### ISSUE TITLE
Wireguard invalid key in generated config

### ISSUE THREAD

**Issue by GlenDC** [threefoldtech/jumpscaleX_core#84]
The TOML config generated by the `jsx wireguard` command contains a key that my wireguard client downloaded from the official Apple Store doesn't accept.

```
saveConfig = true
```

When I delete that line it does work and allows me to add the VPN.

With that line included I get an error dialog box saying that `saveConfig` is not a recognized key. It does so while also listing all recognized keys. This key is not even remotely in that list.

**Comment by grimpy** [comment]
Note: saveconfig is an option of wg-quick not of wg itself.

**Comment by GlenDC** [comment]
It's the first time I use Wireguard, so not sure what wg-quick is or what I need to do with the config. All I know is that I've been told that using wireguard I can use this config to connect to my container JSX machine.

I also know from trial-and-error that when I remove that line with "saveConfig" that the config does get accepted by my Wireguard client.

**Comment by serboctor** [comment]
The `SaveConfig` is part of the configuration that jumpscale uses for wiregaurd. This configuration is not meant to be used for connecting using the client. There is a different configuration for that. I explained to @GlenDC how he can get this configuration. I'll close this for now. @GlenDC feel free to open it if you have more issues.

**Comment by GlenDC** [comment]
I tried it from MacOS instead of from my docker container, as explained by @serboctor.

It seems to work mostly, also using brew (a MacOS package manager) to install missing tools. At the end I get however a config on the STDOUT that is not useable:

```
[Interface]
Address = 10.10.10.2/24
PrivateKey = {WIREGUARD_CLIENT_PRIVKEY}

[Peer]
PublicKey = {WIREGUARD_SERVER_PUBKEY}
Endpoint = localhost:{WIREGUARD_PORT}
AllowedIPs = 10.10.10.0/24
PersistentKeepalive = 25
```

**Comment by serboctor** [comment]
Fixed by https://github.com/threefoldtech/jumpscaleX_core/commit/7ee065035f5b5761b5b53a109ff0ec85cba240d6

**Comment by serboctor** [comment]
@GlenDC tested the fix and verified it worked for him.
