### ISSUE TITLE
Installation: install jsx insystem fails on ubuntu18.04

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#854]
### Step
1- Download latest 3sdk binary from [releases](https://github.com/threefoldtech/jumpscaleX_core/releases)
2- `chmod +x  3sdk_v10.5.3_linux_x86_64`
3- install jsx 
```bash 
./3sdk_v10.5.3_linux_x86_64 --expert install
```
### Result 
![image](https://user-images.githubusercontent.com/41957921/82203909-454fd480-9904-11ea-8c3f-7f22d6a4d678.png)

**Comment by m-motawea** [comment]
The error is caused by invalid metadata for `appstream`.
possible solutions are recreating `\tmp` dir or removing `appstream`

**Comment by waleedhammam** [comment]
it's also defined as a bug in ubuntu https://www.linuxquestions.org/questions/ubuntu-63/apt-get-update-error-4175622466/, https://askubuntu.com/questions/894519/ubuntu-16-04-appstreamcli-error-while-get-update

**Comment by waleedhammam** [comment]
Can't reproduce after building locally from the latest master. the problem was there with the latest binary

![Screenshot from 2020-05-27 15-31-48](https://user-images.githubusercontent.com/10658229/83025266-37e6c880-a02f-11ea-8bb5-017634e9825e.png)

**Comment by AhmedHanafy725** [comment]
**Verified**

![image](https://user-images.githubusercontent.com/41957921/83027663-a8421980-a030-11ea-901f-c327ed7429ae.png)
