### ISSUE TITLE
Mixing of 3sdk --expert can get you in trouble

### ISSUE THREAD

**Issue by grimpy** [threefoldtech/jumpscaleX_core#862]
When you create a threebot with --expert enable you container will moutn the code inside your container from ~/sandbox/code

if you afterwards start the same container with `pull=true` withouth expert mode it might deleted all your code on the host.

This behaviour is ofcourse undesirable.

When pulling code we need to detect if our container we are pulling from has coded mounted or not instead of relying on the `--expert` flag

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
