### ISSUE TITLE
GE: Main Green Edge ThreeBot stopped working with no apparent cause/change 

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/jumpscaleX_core#868]
We use my ThreeBot on my iMac to manage our Green Edge farms and wallets. It was working fine until yesterday when it just stopped. Please refer to my command line below to see the steps I tried to take to fix the problem.

This is high priority for us as we have quite some management to do on our farms in the coming days and weeks, and this ThreeBot is the only one that can do it.

The following commands result in errors:
> threebot browser
> threebot restart
> threebot stop
> threebot start

![Screenshot 2020-05-21 at 09 59 41](https://user-images.githubusercontent.com/1249806/82537356-365a6380-9b4a-11ea-9b53-e62ce71e2687.png)
![Screenshot 2020-05-21 at 09 59 13](https://user-images.githubusercontent.com/1249806/82537367-39555400-9b4a-11ea-9b6d-8c4f3f8e1a53.png)
![Screenshot 2020-05-21 at 10 01 45](https://user-images.githubusercontent.com/1249806/82537379-3c504480-9b4a-11ea-9db2-709019f74fb7.png)

**Comment by joefoxton** [comment]
@rkhamis That's great news.

Should I just wait for the next version? When do you think it will be out?

Or should we try to fix this on my machine with the current version? I definitely don't want to be without access to our farm management for too long.

I'll be more careful to stop all containers before a reboot, though rarely the machine reboots of its own accord (eg. when doing a mac os update). Should I turn off automatic updates? If so, it might be an idea to put this warning in the documentation.

**Comment by rkhamis** [comment]
@joefoxton I'll create a hotfix now and ask you to update.
you needn't turn off the automatic updates on your Mac then

**Comment by joefoxton** [comment]
Awesome. Thank you.

**Comment by rkhamis** [comment]
@joefoxton what version of the 3sdk are you using?

it's already part of the released 10.5.3
https://github.com/threefoldtech/jumpscaleX_threebot/issues/674

**Comment by joefoxton** [comment]
I'm using 10.5.3

**Comment by joefoxton** [comment]
I tried again, showing the full flow... 

![Screenshot 2020-05-21 at 11 59 03](https://user-images.githubusercontent.com/1249806/82547714-77f30a80-9b5a-11ea-9310-c5bb3cdbe261.png)

![Screenshot 2020-05-21 at 12 01 08](https://user-images.githubusercontent.com/1249806/82547930-c902fe80-9b5a-11ea-9a71-f90b2c545e3e.png)

![Uploading Screenshot 2020-05-21 at 11.55.22.png…]()

**Comment by joefoxton** [comment]
Another symptom... when I start 3sdk, it looks like it launches two identical processes. Is this right? 

![Screenshot 2020-05-21 at 12 06 47](https://user-images.githubusercontent.com/1249806/82548679-f7350e00-9b5b-11ea-8bd1-02e5018ad4da.png)

**Comment by rkhamis** [comment]
hotfixed on master.
