### ISSUE TITLE
No option to choose HDD/SSD storage space during ubuntu installation[mainnet]

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/jumpscaleX_core#870]
During the "chat flow" to create a ubuntu container I am never asked to pick how much storage I would like and it only gives 250Mb by default.

Which is not enough to even update the system properly and install like 1 package.

**Comment by BolaNasr** [comment]
It's already exist 
https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py#L51
please update your code

**Comment by MathiasDeWeerdt** [comment]
> It's already exist
> https://github.com/threefoldtech/jumpscaleX_threebot/blob/development/ThreeBotPackages/tfgrid_solutions/tfgrid_solutions/chatflows/ubuntu_deploy.py#L51
> please update your code

Not on mainnet using the latest 3sdk release.

**Comment by rkhamis** [comment]
@MathiasDeWeerdt it should be there. are you sure you don't need to update?

**Comment by MathiasDeWeerdt** [comment]
> @MathiasDeWeerdt it should be there. are you sure you don't need to update?

I am currently using the latest release.

![image](https://user-images.githubusercontent.com/7256303/83852542-3f376180-a714-11ea-88db-6b2675f41597.png)

**Comment by Pishoy** [comment]
verfied
