### ISSUE TITLE
Secret containing special characters make fail local container encryption

### ISSUE THREAD

**Issue by archit3kt** [threefoldtech/jumpscaleX_core#872]
Hi, during my first threebot start launch, I specified a secret with special characters

Here is the command line result :

"...
- make sure jumpscale code is on local filesystem
- install jumpscale for identity:myusername.3bot
- Configure secret

/tmp/script_dockerexecutor.sh: line 5: %{LHs!: No such file or directory
/tmp/script_dockerexecutor.sh: line 5: 9X/Jf:: No such file or directory

Could not execute: docker exec -ti 3bot bash -c 'bash -e /tmp/scipt_dockerexecutor.sh'
"

After this, loading again threebot start from "- make sure jumpscale code is on local filesystem" and fails again with the same error message. Any guidance ?

Btw, why can't we copy paste from the shell ?

**Comment by archit3kt** [comment]
Loading in expert mode and stopping the working container allowed me to put once again the good arguments (secret without special characters) to create the threebot container.

Still there should be a check on allowed characters when we specify the secret

**Comment by grimpy** [comment]
This is an escaping bug, all kind of characters should be allowed

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
