### ISSUE TITLE
3sdk Windows - Version and Update

### ISSUE THREAD

**Issue by gneumann333** [threefoldtech/jumpscaleX_core#885]
Hello,

I downloaded the latest version of 3sdk from the website (v10.6rc1)
Installation work perfectly
When i open the 3sdk Webpage i had a notification that there is a newer Version available
I checked the Version in the command line on got this

![image](https://user-images.githubusercontent.com/39131062/83490322-2169c280-a4b0-11ea-9361-0f507be8242b.png)

seems to be the latest Version but is not properly recognized.
Also the 3sdk update does not work, or where would i have to execute that?

**Comment by m-motawea** [comment]
`3sdk update` command is run from the command line not the shell.
![image](https://user-images.githubusercontent.com/32568986/83513439-145dcb00-a4d2-11ea-95fa-9ec703b4c0f9.png)

**Comment by AhmedHanafy725** [comment]
**Verified** 

With the latest version for 3sdk on [releases](https://github.com/threefoldtech/jumpscaleX_core/releases)

+ Ubuntu

![image](https://user-images.githubusercontent.com/41957921/83644503-a557a380-a5b1-11ea-9972-1640e5f68060.png)

+ Windows

![image](https://user-images.githubusercontent.com/41957921/83646708-4e070280-a5b4-11ea-8d46-3f2be2f01b62.png)

![image](https://user-images.githubusercontent.com/41957921/83646736-595a2e00-a5b4-11ea-9535-ebb8141cc3a5.png)

+ Also in admin dashboard 

![image](https://user-images.githubusercontent.com/41957921/83646963-9faf8d00-a5b4-11ea-9e6d-b3dffdfe43bb.png)
