### ISSUE TITLE
Deleting a network, doesn't really delete it

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/jumpscaleX_core#892]
The network just pops back up if I restart the container.

**Comment by zaibon** [comment]
can you give more information please? reservation ID, network name...

**Comment by BolaNasr** [comment]
i deleted network from admin and then i can't ping any solutions using this network 
So , it works good.

**Comment by Pishoy** [comment]
I already delete the network but it is still shown in network tab in chatflow while the container is not reachable as the network is deleted, below is reservation id

http://explorer.testnet.grid.tf/explorer/reservations/461633

- jsx version 
```
root@3bot:/sandbox/code/github/threefoldtech/jumpscaleX_threebot# git log -1
commit 48b9f9876e494526e2a9c1450805f77a203dd7d7 (HEAD -> development, origin/development, origin/HEAD)
Merge: 118975c a362fc7
Author: Bola E.Nasr <bola.nasr@live.com>
Date:   Sun Jun 14 05:04:48 2020 -0700

    Merge pull request #768 from threefoldtech/development_flist_check
    
    check about md5 flist

```

**Comment by zaibon** [comment]
@Pishoy check that the reservation ID is actually the same. Because of the way how the admin panel deals with network, you can have multiple reservation modifying the same network.

**Comment by Pishoy** [comment]
sorry, network reservation is `461631`

**Comment by zaibon** [comment]
I mean check the reservation ID, then delete it. If it still shows, check the reservation ID again. Most probably it will not be the same.

**Comment by Pishoy** [comment]
works now!

**Comment by zaibon** [comment]
@Pishoy What do you mean `works now`?

**Comment by Pishoy** [comment]
after I tried network deletion (reservation id  461631)  again, it works 

also, I did the same steps again and worked now

not sure what was the issue, seems connection issue 

 - threebot logs tmux 

![image](https://user-images.githubusercontent.com/21987477/85027498-4af63f80-b17a-11ea-9aa1-ffa91bc225da.png)

**Comment by zaibon** [comment]
This seems weird, I'm re-opening, there are still things to figure out here.

**Comment by grimpy** [comment]
https://github.com/threefoldtech/js-sdk/issues/48 relates to let's backport this fix

**Comment by ranatrk** [comment]
The fix suggested and implemented, is recursively linking each updated network with its parent network by saving the parent reservation id in the metadata of the child. In case the network is to be cancelled from the admin dashboard, all its parent networks will be cancelled as well and so the previous version of the network(in an older reservation) will not reappear.

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
