### ISSUE TITLE
Exposing TCP port doesnt seem to work

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/jumpscaleX_core#893]
Attempting to expose port a TCP port. But it doesn't seem to be working once I went through the wizard. (Using the domain assigned by the wizard)

**Comment by zaibon** [comment]
can you give more information please? reservation ID, network name...

**Comment by MathiasDeWeerdt** [comment]
@zaibon 
I just tried this again today with a ubuntu container and the expose function doesn't seem to be working.

Network: Reservation id: 9961
Ubuntu: Reservation id: 9958
Expose Solution: Reservation id: 9962

Running a service using port 25565 on the ubuntu container and trying to acces it through: testserver.tfgw-prod-05.gateway.tf:25565

But nothing seems to be running there if I try to telnet to it.
![image](https://user-images.githubusercontent.com/7256303/84761548-daa8bc00-afc9-11ea-9ad8-12783b4a813f.png)

**Comment by grimpy** [comment]
You can not use reverse_proxy for any arbitrary tcp port. we support 3 kind of services
plain http (host headers) https and tls services the last to use we sni to make the redirect happen.

**Comment by MathiasDeWeerdt** [comment]
> You can not use reverse_proxy for any arbitrary tcp port. we support 3 kind of services
> plain http (host headers) https and tls services the last two we check sni to make the redirect happen.

Oh, is there planned support to add this functionality, because we would need this to deploy our FFC solution to the grid correctly.

**Comment by grimpy** [comment]
@zaibon correct me if I'm wrong but I don't think there is currently anyway to do this except by using public ipv6 on a container within the network? For people with ipv4 stack there is no solutions afaik

**Comment by zaibon** [comment]
> You can not use reverse_proxy for any arbitrary tcp port. 

Well that is half true. You can expose any TCP port, but if this is not HTTP, then you need to support SNI. Cause without it there is no way for the gateway to know where to proxy the traffic.

@MathiasDeWeerdt What is the service you are trying to expose ?
