### ISSUE TITLE
3sdk: explorer argument doesn't reflect in installation

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#894]
### Steps
1- Download latest binary from [releases](https://github.com/threefoldtech/jumpscaleX_core/releases).
2- Start 3sdk.
3- Set explorer argument.
```python
args explorer val=none
```
4- Start threebot.
```python
threebot start
```
### Expected Result
don't ask for identity as explorer is `none`.

### Actual Result
![image](https://user-images.githubusercontent.com/41957921/84013953-e832c600-a979-11ea-97a6-c1095ee425a8.png)

**Comment by BolaNasr** [comment]
Commit : https://github.com/threefoldtech/jumpscaleX_core/commit/5db8c53df5bd5271a4727cfaaad2bca4fa1a202f

**Comment by AhmedHanafy725** [comment]
It didn't ask for identity at that point, but it asks for after creating the container.

![image](https://user-images.githubusercontent.com/41957921/84122101-373f3080-aa38-11ea-93cd-c0916ac7badc.png)

**Comment by BolaNasr** [comment]
Fixed https://github.com/threefoldtech/jumpscaleX_core/commit/4a29853a45e192aee645638d46c4aaac0bd4baeb

**Comment by AhmedHanafy725** [comment]
**Verified**
**Branch:**: development
**Commit:** 4a29853a45e192aee645638d46c4aaac0bd4baeb

![image](https://user-images.githubusercontent.com/41957921/84260808-eeac7380-ab1a-11ea-82da-4e39e197e893.png)
