### ISSUE TITLE
secret option doesn't work in container install in 3sdk

### ISSUE THREAD

**Issue by Dina-Abd-Elrahman** [threefoldtech/jumpscaleX_core#895]
when I pass secret as an option in command container install it asked me for a secret again.

![ff](https://user-images.githubusercontent.com/21218053/84645913-9eaa2400-af01-11ea-9b27-f8dfaabce6ab.png)

**Comment by grimpy** [comment]
I can't reproduce this this does however happen if this identity exists under ~/sandbox/myhost/identities/ and was encrypted with another secret

**Comment by Dina-Abd-Elrahman** [comment]
- it's working now.
