### ISSUE TITLE
Deployed a flist and it seems unstable

### ISSUE THREAD

**Issue by MathiasDeWeerdt** [threefoldtech/jumpscaleX_core#896]
Deployed a flist, but the "CoreX service" / "server" seems to be unstable / unreachable. (My own network is stable and has no issues.)

![image](https://user-images.githubusercontent.com/7256303/84646899-06ad3a00-af03-11ea-9217-77edf6e77cb9.png)

![image](https://user-images.githubusercontent.com/7256303/84646974-1c226400-af03-11ea-8ce6-e93c3d5aa44a.png)

**Comment by zaibon** [comment]
@MathiasDeWeerdt Can you please always give the reservation ID when you open an issue. 

If you are using node `CBDY1Fu4CuxGpdU3zLL9QT5DGaRkxjpuJmzV6V5CBWg4` as access point for you network, there were some issue in the network causing what you see there. This was solved yesterday.
Can you confirm that you are using this node or not please.

**Comment by MathiasDeWeerdt** [comment]
Deployed a ubuntu container today and that seems to be working. I dont know which node I was using I just let the chat flow pick one out for me.
