### ISSUE TITLE
SAL.FS: isAsciiFile returns True all the time

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/jumpscaleX_core#90]
### Steps:
1- `j.sal.fs.isAbsolute("test.py")`
2- `os.path.isabs("test.py")`

### Expected Result:
`False` for both steps.

### Actual Result:
1- `j.sal.fs.isAbsolute("test.py")`
Result: `True`
2- `os.path.isabs("test.py")`
Result: `False`

**Comment by ahmedelsayed-93** [comment]
fixed https://github.com/threefoldtech/jumpscaleX_core/commit/5a9dcc57248de8e922b811de6ea24838533aa95b

**Comment by AhmedHanafy725** [comment]
**Verified**
```
JSX> j.sal.fs.isAbsolute("test.py")                                                                  
False

JSX> j.sal.fs.isAbsolute("/tmp/test.py")                                                             
True

```
