### ISSUE TITLE
GE: Feature Request: select, copy, paste, and scroll in the SDK & Kosmos shell

### ISSUE THREAD

**Issue by joefoxton** [threefoldtech/jumpscaleX_core#902]
It would be great if the SDK & Kosmos shells allowed you to select, copy and paste text, as well as scrolling to see the history.

This is a bit more than "nice to have" as it dampens our ability to collaborate or get work done fast.

**Comment by grimpy** [comment]
@joefoxton I guess the shift thing is indeed terminal dependant it works on most terminals I know, but I have no idea about mac tbh. In all cases it will be improved in next version

**Comment by joefoxton** [comment]
Good to hear!

**Comment by Dina-Abd-Elrahman** [comment]
- verified.
