### ISSUE TITLE
odoo server : database_list, database_reset 

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#92]
# database_listt:

## Steps 
- Install odoo server and start it 
- Create new database
   data_base= odoo_server.databases.new()
-  set new name and password for created database
-  save odoo_server.save()
## result 
- new server didin't exist in database_list  only the default one which created through installl 
- When you try to login to ceated_data base will result the following error
```
JSX> cl.databases_list()                                                                             
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/odoo/OdooClient.py", line 195, in databases_list
    return self.client.db.list()
  File "/sandbox/lib/jumpscale/JumpscaleLibs/clients/odoo/OdooClient.py", line 35, in client
    password=self.password_,
  File "/usr/local/lib/python3.6/dist-packages/erppeek.py", line 490, in __init__
    self.login(user, password=password, database=db)
  File "/usr/local/lib/python3.6/dist-packages/erppeek.py", line 581, in login
    (database, dbs))
erppeek.Error: Database 'dina' does not exist: ['odoo_test']

```
## database reset 
return the following error 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/sandbox/lib/jumpscale/JumpscaleLibsExtra/servers/odoo/OdooServer.py", line 91, in databases_reset
    data = {"master_pwd": db.db_secret_, "name": db}
AttributeError: 'str' object has no attribute 'db_secret_'

'str' object has no attribute 'db_secret_'
```
same if we give database_create , reset=True

**Comment by ranatrk** [comment]
currently refactoring odoo_server as there is also another issue where the startup_cmd includes creating a new db and so when starting or stopping a new db is created therefore needs refactoring

**Comment by ranatrk** [comment]
Refactor odoo server:
https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/f7d180d7b451bc667599034f4df2d1fa54e1981f

notes:
-Start will init the base db needed to start odoo with the admin_login and admin_passwd_ of odoo server instance
-If new databases are created using `odoo_server.databases.new()` , `odoo_server.databases_create()` needs to follow it to create the new databases in postgres

**Comment by Pishoy** [comment]
can we make first database_list() shows the default databases that should be exist before creating Bishoytest database as below ?
![image](https://user-images.githubusercontent.com/21987477/65605165-f0dc9b00-dfa8-11e9-9da1-a581d636c2fc.png)

**Comment by ranatrk** [comment]
Changed implementation of `databases_list()` :
https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/e028726b0f0052678e2c09d3a2062ca648056434

**Comment by Pishoy** [comment]
verified
```
 JSX> odoo_server.databases_list()                                                                                                                                                                           
  datname  
-----------
 postgres
 odoo_test
 template1
 template0
(4 rows)

[' postgres', ' odoo_test', ' template1', ' template0']

JSX> obj = odoo_server.databases.new()                                                                                                                                                                      
JSX> obj.name='Bishoytest'                                                                                                                                                                                  
JSX> odoo_server.databases_create()                                                                                                                                                                         
JSX> odoo_server.databases_list()                                                                                                                                                                           
  datname   
------------
 postgres
 odoo_test
 template1
 template0
 Bishoytest
(5 rows)

[' postgres', ' odoo_test', ' template1', ' template0', ' Bishoytest']

```
- js version 
```
3BOTDEVEL:testwikis:jumpscaleX_core: git log -1
commit 010dabee7707afda92655c634f670cbca87c22b3 (HEAD -> development, origin/development, origin/HEAD)
Merge: 647943d 36b074d
Author: serboctor <boctor.sarah@gmail.com>
Date:   Mon Sep 30 12:07:04 2019 +0200

    Merge pull request #112 from threefoldtech/development_save
    
    Refactor deletion flow
```

**Comment by Dinaamagdy** [comment]
database reset :
in docs : 
```databases_reset(self, db_name=None) 
 
remove all databases 
:retun

but actually it doesn't remove anything , I can get all created databases in database_list and login inside it

**Comment by Pishoy** [comment]
database creation is not working as below:
```
JSX> odoo_server = j.servers.odoo.default                                                                                                                                                                   
JSX> odoo_server.databases_list()                                                                                                                                                                           
  datname  
-----------
 postgres
 odoo_test
 template1
 template0
(4 rows)

['postgres', 'odoo_test', 'template1', 'template0']

JSX> obj = odoo_server.databases.new()                                                                                                                                                                      
JSX> obj.name = 'BishoyTest'                                                                                                                                                                                
JSX> odoo_server.databases_create()                                                                                                                                                                         
JSX> odoo_server.databases_list()                                                                                                                                                                           
  datname  
-----------
 postgres
 odoo_test
 template1
 template0
(4 rows)

['postgres', 'odoo_test', 'template1', 'template0']

JSX>                                                                                                                                                                                                        
3BOTDEVEL:ubuntu-s-1vcpu-1gb-nyc1-01:~: kosmos 
Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.odoo.server.1
Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.odoo.server.db.1
Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.postgres.client
Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
Mon 14 15:39:11 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:system
JSX> odoo_server = j.servers.odoo.default                                                                                                                                                                   
JSX> odoo_server.databases_list()                                                                                                                                                                           
  datname  
-----------
 postgres
 odoo_test
 template1
 template0
(4 rows)

['postgres', 'odoo_test', 'template1', 'template0']

```
jsx version
```
commit 8dd47be3cfd3ce24f016631800535dd1d9288984 (HEAD -> development, origin/development, origin/HEAD)
Merge: 3858e7e 3a82e31
Author: dinaamagdy <magdyd@codescalers.com>
Date:   Mon Oct 14 14:32:13 2019 +0200

    Merge branch 'development' of https://github.com/threefoldtech/jumpscaleX_core into development
```

**Comment by ranatrk** [comment]
> database creation is not working as below:
> 
> ```
> JSX> odoo_server = j.servers.odoo.default                                                                                                                                                                   
> JSX> odoo_server.databases_list()                                                                                                                                                                           
>   datname  
> -----------
>  postgres
>  odoo_test
>  template1
>  template0
> (4 rows)
> 
> ['postgres', 'odoo_test', 'template1', 'template0']
> 
> JSX> obj = odoo_server.databases.new()                                                                                                                                                                      
> JSX> obj.name = 'BishoyTest'                                                                                                                                                                                
> JSX> odoo_server.databases_create()                                                                                                                                                                         
> JSX> odoo_server.databases_list()                                                                                                                                                                           
>   datname  
> -----------
>  postgres
>  odoo_test
>  template1
>  template0
> (4 rows)
> 
> ['postgres', 'odoo_test', 'template1', 'template0']
> 
> JSX>                                                                                                                                                                                                        
> 3BOTDEVEL:ubuntu-s-1vcpu-1gb-nyc1-01:~: kosmos 
> Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.circle.2
> Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.bcdb.acl.user.2
> Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.odoo.server.1
> Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.odoo.server.db.1
> Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.postgres.client
> Mon 14 15:39:11 BCDB.py              - 446 - bcdb                               : load model:jumpscale.startupcmd.1
> Mon 14 15:39:11 BCDB.py              -  87 - bcdb                               : BCDB INIT DONE:system
> JSX> odoo_server = j.servers.odoo.default                                                                                                                                                                   
> JSX> odoo_server.databases_list()                                                                                                                                                                           
>   datname  
> -----------
>  postgres
>  odoo_test
>  template1
>  template0
> (4 rows)
> 
> ['postgres', 'odoo_test', 'template1', 'template0']
> ```
> 
> jsx version
> 
> ```
> commit 8dd47be3cfd3ce24f016631800535dd1d9288984 (HEAD -> development, origin/development, origin/HEAD)
> Merge: 3858e7e 3a82e31
> Author: dinaamagdy <magdyd@codescalers.com>
> Date:   Mon Oct 14 14:32:13 2019 +0200
> 
>     Merge branch 'development' of https://github.com/threefoldtech/jumpscaleX_core into development
> ```

If the admin password in  /sandbox/cfg/odoo.conf is old, then access is denied when creating the databases using databases_create(). It's because the admin password saved there was different from the one saved in the new instance. If deleted and a new installation is done on a clean environment it works fine.

**Comment by ranatrk** [comment]
> database reset :
> in docs :
> 
> ```
>  
> remove all databases 
> :retun
> 
> but actually it doesn't remove anything , I can get all created databases in database_list and login inside it
> same if i give create_datbase:reset=True
> ```

Fix : https://github.com/threefoldtech/jumpscaleX_libs_extra/commit/e27fb6d70d16f63ebee989b7a088bfa45b3ff4ea

**Comment by Pishoy** [comment]
verified successfully
