### ISSUE TITLE
some servers need  refactoring

### ISSUE THREAD

**Issue by Dinaamagdy** [threefoldtech/jumpscaleX_core#94]
some servers need refactoring 
- flaskserver
- gid_capacity
- raft
- sanic

**Comment by zaibon** [comment]
gid_capacity is planned to be deprecated pretty soon. so no need to rework it.

**Comment by serboctor** [comment]
@Dinaamagdy Can you add more info? what needs to be refactored? are they not following the correct baseclasses? are they producing errors? If you found any errors, can you add them to the ticket.

**Comment by Dinaamagdy** [comment]
@serboctor 
here rana specify that this servers need refactor
https://github.com/threefoldtech/jumpscaleX_core/issues/30#issuecomment-529518737

**Comment by serboctor** [comment]
@rkhamis said flask and sanic can be removed too. And specs for raft aren't clear yet and isn't a priority right now.
