### ISSUE TITLE
Testing: JSx clients

### ISSUE THREAD

**Issue by 0xIslamTaha** [threefoldtech/jumpscaleX_core#97]
**Description**
We need to test different functions under JumpscaleX_core/JumpscaleCore/clients/X to make sure that it is working as expected.

**Steps to accomplish the task**

- Gather all the requirements for each client and list them in the traceability matrix.
- Design the test cases according to those requirements and report them in TestQuality
- Execute the test cases and report different bugs (Manual execution)
- Automate those test cases

**What should be delivered?**
1- Traceability matrix
2- Test cases description in testquality
3- Automation test cases

**Comment by Dina-Abd-Elrahman** [comment]
- sshkey client:

- tested manually. 
- created 2 issues with the bugs which i found. https://github.com/threefoldtech/jumpscaleX_core/issues/116, https://github.com/threefoldtech/jumpscaleX_core/issues/117
- test cases: 9840c8ab34f882fb6736740fb391ea4c94de1d5c, branch: ` client_testing `
@Dinaamagdy is reviewing the code now  https://github.com/threefoldtech/jumpscaleX_core/pull/118

**Comment by Dina-Abd-Elrahman** [comment]
- working now on zero-os client, reading the code and do the manual testing

**Comment by Dina-Abd-Elrahman** [comment]
- hold working on zero-os client from yesterday as per @rkhamis  it's under-development now and it will changed so no need for automated test for it now.

**Comment by Dina-Abd-Elrahman** [comment]
- yesterday I'm done with manual testing for Digitalocean client, and i found some bugs 

https://github.com/threefoldtech/jumpscaleX_libs/issues/18
https://github.com/threefoldtech/jumpscaleX_libs/issues/19
https://github.com/threefoldtech/jumpscaleX_libs/issues/20

- today I will start in automated testing.

**Comment by Dina-Abd-Elrahman** [comment]
- DigitalOcean client test cases 4bad07b5beaa339b5930696577a91fd3ae86489a
